      SUBROUTINE ERNGAA(T,Z,ISPIN,NSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*2 SPCASE(2)
      INTEGER A,B
      DIMENSION T(NSIZE),Z(NSIZE)
      COMMON /FLAGS/ IFLAGS(100)
      DATA SPCASE /'AA','BB'/
      CALL GETALL(T,NSIZE,1,43+ISPIN)
      X=SDOT(NSIZE,Z,1,T,1)
      IF(IFLAGS(1).GE.10)THEN
       WRITE(6,310)SPCASE(ISPIN), X
      ENDIF
310   FORMAT(T3,'W(mbej) ',A2,' contribution = ',F14.10,' a.u.')
C
C AUGMENT THE T2 INCREMENT AND PUT IT OUT TO DISK.
C
      RETURN
      END
