      SUBROUTINE MKTRAN(X,T1,NVRT,NOCC,NBAS)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION T1(NVRT,NOCC),X(NBAS,NBAS)
      CALL ZERO(X,NBAS*NBAS)
      DO 10 IBAS=1,NBAS
       X(IBAS,IBAS)=1.0D0
10    CONTINUE
      DO 20 I=1,NOCC
       DO 21 J=1,NVRT
        X(I,J+NOCC)=-T1(J,I)
        X(J+NOCC,I)=T1(J,I)
21     CONTINUE
20    CONTINUE
      RETURN
      END
