      SUBROUTINE ORTHOGMO(VECIN,VECOUT,S,TMP1,TMP2,TMP3,NBAS,ISPIN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VECIN(NBAS,NBAS),VECOUT(NBAS,NBAS),S(NBAS,NBAS)
      DIMENSION TMP1(*),TMP2(*),TMP3(*)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      CHARACTER*1 ISP(2)
      DATA ISP/'A','B'/
      DATA ONE,ZILCH,ONEM/1.0D0,0.0D0,-1.0D0/
      NBAS2=NBAS*NBAS
      CALL PUTREC(20,'JOBARC','SCFEVEC'//ISP(ISPIN),NBAS2*IINTFP,
     &            VECIN)
      CALL GETREC(20,'JOBARC','AOOVRLAP',NBAS2*IINTFP,S)
      CALL AO2MO2(S,TMP1,TMP2,TMP3,NBAS,NBAS,ISPIN)
      CALL EIG (TMP1,TMP2,NBAS,NBAS,0)
      CALL INVSQT(TMP1,NBAS+1,NBAS)
      CALL XGEMM('N','N',NBAS,NBAS,NBAS,ONE,TMP2,NBAS,
     &           TMP1,NBAS,ZILCH,TMP3,NBAS)
      CALL XGEMM('N','T',NBAS,NBAS,NBAS,ONE,TMP3,NBAS,
     &           TMP2,NBAS,ZILCH,TMP1,NBAS)
      CALL GETREC(20,'JOBARC','SCFEVEC'//ISP(ISPIN),NBAS2*IINTFP,
     &            TMP2)
      CALL XGEMM('N','N',NBAS,NBAS,NBAS,ONE,TMP2,NBAS,
     &           TMP1,NBAS,ZILCH,VECOUT,NBAS)
      RETURN
      END
