      SUBROUTINE PCCD_WTWTW(ICORE,MAXCOR,IUHF)
C
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM,TWO
      DIMENSION ICORE(MAXCOR)
      DATA ONE /1.0/
      DATA ONEM /-1.0/
      DATA TWO /2.0/

CSSS      CALL SAXLST(ICORE,MAXCOR,54,123,123,TWO,ONEM)
      CALL SAXLST(ICORE,MAXCOR,58,125,125,TWO,ONEM)
      CALL QUIKAB2(ICORE,MAXCOR,IUHF)

      RETURN
      END
