
      SUBROUTINE PCCD_UPDAT1(T1INC,T1OLD,NSIZ,LIST1,LIST2)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION T1OLD(NSIZ),T1INC(NSIZ)
      DATA ONE /1.0/
      CALL GETLST(T1OLD,1,1,1,LIST1,LIST2)
      CALL SAXPY(NSIZ,ONE,T1INC,1,T1OLD,1)
      CALL PUTLST(T1OLD,1,1,1,LIST1,LIST2)
      RETURN
      END
