      SUBROUTINE EVCAO(AOSO,EVEC,SCR,NBAS,IUHF)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION AOSO(NBAS,NBAS),EVEC(NBAS,NBAS),SCR(NBAS,NBAS)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA IONE /1/
C
      CALL GETREC(20,'JOBARC','SCFEVCA0',NBAS*NBAS*IINTFP,EVEC)
      CALL GETREC(20,'JOBARC','AO2SO   ',NBAS*NBAS*IINTFP,AOSO)
C
      CALL MXM(AOSO,NBAS,EVEC,NBAS,SCR,NBAS)
      CALL PUTREC(20,'JOBARC','EVECAO_A',NBAS*NBAS*IINTFP,SCR)
      CALL PUTREC(20,'JOBARC','AOEVEC_A',NBAS*NBAS*IINTFP,SCR)
      IF(IUHF.EQ.1) THEN
        CALL GETREC(20,'JOBARC','SCFEVCB0',NBAS*NBAS*IINTFP,EVEC)
        CALL MXM(AOSO,NBAS,EVEC,NBAS,SCR,NBAS)
        CALL PUTREC(20,'JOBARC','EVECAO_B',NBAS*NBAS*IINTFP,SCR)
        CALL PUTREC(20,'JOBARC','AOEVEC_B',NBAS*NBAS*IINTFP,SCR)
      ENDIF
C
      RETURN
      END
