      SUBROUTINE PCCD_RNGDRV(ICORE,MAXCOR,LISTW,LISTT,CALMOD,MAXSIZ,
     &                       INCREM,LSTSCR)
      IMPLICIT INTEGER (A-Z)
      LOGICAL SPINAD
      CHARACTER*3 CALMOD
      DIMENSION ICORE(MAXCOR)
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      SPINAD=.FALSE.
      IF(IFLAGS(11).EQ.0)SPINAD=.TRUE.
C
C LOOP OVER IRREPS.
C
       DO 100 IRREP=1,NIRREP
        DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        DISSYQ=DISSYT
        NUMSYQ=NUMSYW
        if (NUMSYQ*DISSYQ.LT.0) call trap_intovf('RNGDRV',1)
        MAXSIZ=MAX(NUMSYQ*DISSYQ,MAXSIZ)
        I000=1
        I010=I000+IINTFP*NUMSYQ*DISSYQ
        I020=I010+IINTFP*NUMSYT*DISSYT
        I030=I020+IINTFP*DISSYW*NUMSYW
C
C CAN WE DO IT IN CORE?
C
        if (I030.LT.0) call trap_intovf('RNGDRV',2)
        IF(I030.LT.MAXCOR)THEN
C
C FORM THE SYMMETRY PACKED Q VECTOR.
C
         CALL PCCD_RNGPRD(ICORE(I020),ICORE(I010),ICORE(I000),
     &                    ICORE(I030),MAXCOR-I030, 
     &                    DISSYW,NUMSYW,DISSYT,NUMSYT,DISSYQ,NUMSYQ,
     &                    LISTW,LISTT,IRREP,CALMOD,SPINAD)
        ELSE
         CALL INSMEM('RNGDRV',I030,MAXCOR)
        ENDIF
C
C 
        IF(CALMOD.EQ.'WxT')THEN
         CALL TRANSP(ICORE(I000),ICORE(I010),NUMSYQ,DISSYQ)
c YAU : old
c        CALL ICOPY(IINTFP*NUMSYQ*DISSYQ,ICORE(I010),1,ICORE(I000),1)
c YAU : new
         CALL DCOPY(NUMSYQ*DISSYQ,ICORE(I010),1,ICORE(I000),1)
c YAU : end
         ITMP=NUMSYQ
         NUMSYQ=DISSYQ
         DISSYQ=ITMP
        ENDIF
C
C AUGMENT Q(ABAB) AND DUMP IT TO DISK.
C
        IF(INCREM.EQ.1)THEN
         CALL GETLST(ICORE(I020),1,NUMSYQ,1,IRREP,LSTSCR)
         CALL VADD(ICORE(I020),ICORE(I020),ICORE(I000),
     &             DISSYQ*NUMSYQ,1.D0)
         IF(SPINAD)CALL MPMT(ICORE(I020),NUMSYQ)
         CALL PUTLST(ICORE(I020),1,NUMSYQ,1,IRREP,LSTSCR)
c YAU : old
c        CALL ICOPY(IINTFP*DISSYQ*NUMSYQ,ICORE(I020),1,ICORE(I000),1)
c YAU : new
         CALL DCOPY(DISSYQ*NUMSYQ,ICORE(I020),1,ICORE(I000),1)
c YAU : end
        ELSE
         IF(SPINAD)CALL MPMT(ICORE(I000),NUMSYQ)
         CALL PUTLST(ICORE(I000),1,NUMSYQ,1,IRREP,LSTSCR)
        ENDIF
100    CONTINUE
       RETURN
       END
