      SUBROUTINE PCCD_FORMG1(ICORE,MAXCOR,IUHF,FACT)

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,DISSYL,DISSYT,POP,VRT
      DIMENSION ICORE(MAXCOR)
      COMMON /SYM/ POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
      MXCOR=MAXCOR

      NVRTSQ=NF2AA 
      I000=MXCOR+1-NVRTSQ*IINTFP
      MXCOR=MXCOR-NVRTSQ*IINTFP
      CALL ZERO(ICORE(I000),NVRTSQ)

      ISPIN=1
      LISTT=46
      ISAME=.FALSE.
      LISTL=146

      DO 200 IRREP=1,NIRREP
        DISSYL=IRPDPD(IRREP,ISYTYP(1,LISTL))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYL=IRPDPD(IRREP,ISYTYP(2,LISTL))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        I001=1
        I002=I001+IINTFP*NUMSYL*DISSYL
        I003=I002+IINTFP*NUMSYT*DISSYT
        I004=I003+IINTFP*NUMSYT*DISSYT
        IF(MIN(NUMSYT,NUMSYL,DISSYT,DISSYL).NE.0) THEN
         I005=I004+3*IINTFP*MAX(DISSYT,DISSYL,NUMSYL,NUMSYT)
         IF(I005.GT.MXCOR) CALL INSMEM('G1AB',I005,MXCOR)
C
          CALL G1AB(ICORE(I001),ICORE(I002),ICORE(I003),ICORE(I000),
     &              ISAME,ISPIN,POP(1,ISPIN),POP(1,3-ISPIN),
     &              VRT(1,ISPIN),VRT(1,3-ISPIN),NVRTSQ,DISSYL,DISSYT,
     &              NUMSYL,NUMSYT,LISTL,LISTT,IRREP,ICORE(I004),IUHF,
     &              FACT)
        ELSE
        ENDIF
200   CONTINUE
      CALL PUTLST(ICORE(I000),1,1,1,1,192)

      RETURN
      END
