      SUBROUTINE PDCC_LADCONT(Z,T2,W,NDISSTRT,NAODIS,IOFFT2,IUHF,
     &                        NPASS,IRREPX,LISTZ0,LISTT0)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD
      DIMENSION Z(*),T2(*),W(*),NDISSTRT(8),IOFFT2(8),NAODIS(8)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/AOSYM/IAOPOP(8),IOFFAO(8),IOFFV(8,2),IOFFO(8,2),
     &             IRPDPDAO(8),IRPDPDAOS(8),ISTART(8,8),ISTARTMO(8,3)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      DATA ONE,ZILCH /1.0D0,0.0D0/
C
C CONTRACT CONTRIBUTING W ELEMENTS WITH T2 VECTOR
C
      FACT=ONE
      ISPIN=3
      IF(NPASS.EQ.1)FACT=ZILCH
       LISTT=LISTT0+ISPIN
       LISTZ=LISTZ0+ISPIN
       IOFFW=1
       DO 30 IRREPAB=1,NIRREP
        IRREPIJ=DIRPRD(IRREPAB,IRREPX)
        NDSSIZ=IRPDPDAO(IRREPAB)
        NUMDIS=IRPDPD(IRREPIJ,ISYTYP(2,43+ISPIN))
        IOFFT=NDISSTRT(IRREPAB)
        CALL GETLST(T2,1,NUMDIS,1,IRREPIJ,LISTT)
        CALL GETLST(Z ,1,NUMDIS,1,IRREPIJ,LISTZ)
        NROW=IRPDPDAO(IRREPAB)
        NSUM=NAODIS(IRREPAB)
        NCOL=IRPDPD(IRREPIJ,ISYTYP(2,43+ISPIN))
        CALL XGEMM('N','N',NROW,NCOL,NSUM,ONE,W(IOFFW),NROW,T2(IOFFT),
     &             NROW,FACT,Z,NROW)
        IOFFW=IOFFW+NROW*NSUM
        CALL PUTLST(Z ,1,NUMDIS,1,IRREPIJ,LISTZ)
30     CONTINUE
C
      RETURN
      END
