      SUBROUTINE PCCD_LRNGPRD(W,T,Q,SCR,DISSYW,NUMSYW,DISSYT,NUMSYT,
     &                        DISSYQ,NUMSYQ,LISTW,LISTT,IRREP,
     &                        SPINAD,MAXCOR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL SPINAD,MBPT4,BREDUNDANT
      INTEGER DISSYT,DISSYW,DISSYQ
      DIMENSION W(numsyw*dissyw),T(numsyt*dissyt),Q(numsyq*dissyq)
      DIMENSION SCR(MAXCOR)
C
      COMMON /FLAGS2/IFLAGS2(500)
      COMMON /INFO/ NOCC(2),NVRTO(2)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA TWO/2.D0/
      DATA AZERO,HALFM,ONE,ONEM /0.D0,-0.5D0,1.D0,-1.D0/

      CALL GETLST(T,1,NUMSYT,1,IRREP,LISTT)
      IF (SPINAD) CALL DSCAL(NUMSYT*DISSYT,2.0D0,T,1)

C Here listt is 137 L2(Ij,Ab) AI,bj(11,22). List 139 is L2(Ij||Ab)
C Aj,bI(12,21)

      FACT = ONE
      IF(SPINAD)THEN
          CALL GETLST(W,1,NUMSYT,1,IRREP,139)
          CALL SAXPY(NUMSYT*DISSYT,ONEM,W,1,T,1)
          LISTW = 56
          FACT  = HALFM
      ENDIF
C
      CALL GETLST(W,1,NUMSYW,2,IRREP,LISTW)

      CALL XGEMM('N','T',DISSYT,DISSYW,NUMSYW,FACT,T,DISSYT,
     &           W,DISSYW,AZERO,Q,DISSYQ)

      RETURN
      END
