      
      SUBROUTINE SETMET(IUHF)
C
C DETERMINES IN PARTICULAR WHETHER A FULL INTEGRAL TRANSFORMATION
C IS REQUIRED OR A PARTIAL TRANSFORMATION SUFFICES.
C
C     DOALL = .TRUE.    ....    FULL INTEGRAL TRANSFORMATION
C     NOABCD = .TRUE.   ....    PARTIAL INTEGRAL TRANSFORMATION
C     ABIJ = .TRUE.     .....   MBPT(2) SINGLE POINT ENERGY
C                               INTEGRAL TRANSFORMATION (N.Y.I.)
CEND
      IMPLICIT INTEGER(A-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      LOGICAL DOALL,ABIJ,NOABCD
      COMMON/METH/MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      COMMON/FLAGS/IFLAGS(100)
      COMMON/FLAGS2/IFLAGS2(500)
      COMMON/DOINTS/DOALL,ABIJ,NOABCD
C
      EQUIVALENCE(METHOD,IFLAGS(2))
C
      DOALL=.TRUE.
      NOABCD=.FALSE.
      ABIJ=.FALSE.
      MBPT2=.FALSE.
      MBPT3=.FALSE.
      M4DQ=.FALSE.
      M4SDQ=.FALSE.
      M4SDTQ=.FALSE.
      CCD=.FALSE.
      QCISD=.FALSE.
      CCSD=.FALSE.
      UCC=.FALSE.
C
      IF(METHOD.EQ.0) THEN
C
C HF FREQUENCY CALCULATIONS, WE DO NOT NEED <AB|CD> INTEGRALS
C
       NOABCD=.TRUE.
       DOALL=.FALSE.
C
CWJL/JDW 3/14/94
C  IF THIS IS A TDHF CALCULATION, WE DO NEED EVERYTHING, SO UNDO THESE
C  OPTIONS.
C
      IF(IFLAGS2(103).EQ.1)THEN
        NOABCD=.FALSE.
        DOALL=.TRUE.
      ENDIF
C
      ELSE IF(METHOD.EQ.1) THEN
C
C MBPT(2), WE NEED <AB|CD> ONLY IN CASE OF SECOND DERIVATIVES
C  WE DON'T NEED THEM FOR NMR-SHIFTS
C
       MBPT2=.TRUE.
       IF(IFLAGS(3).EQ.0.AND.IFLAGS(22).EQ.0.AND.
     &    IFLAGS(74).EQ.0) ABIJ=.TRUE.
       IF(IFLAGS(3).LE.1.OR.
     &    (IFLAGS(18).GE.3.AND.IFLAGS(18).LT.9)) THEN
        NOABCD=.TRUE.
        DOALL=.FALSE.
       ENDIF
C
C SG 4/24/96 For P-EOM-MBPT(2) we only need <AB|CD> for gradients
C
       IF (IFLAGS(87) .GT. 0) THEN
         IF ((IFLAGS(87).EQ.7 .OR. IFLAGS(87).EQ.8) .AND.
     &      IFLAGS(3) .EQ. 0) THEN
           NOABCD = .TRUE.
           DOALL = .FALSE.
         ELSE
           NOABCD = .FALSE.
           DOALL = .TRUE.
         ENDIF
       ENDIF
C
      ELSE IF(METHOD.EQ.2) THEN
C
C MBPT(3)
C
       MBPT3=.TRUE.
      ELSE IF(METHOD.EQ.3) THEN
C
C SDQ-MBPT(4)
C
       M4SDQ=.TRUE.
      ELSE IF(METHOD.EQ.4) THEN
C
C MBPT(4)
C
       M4SDQ=.TRUE.
      ELSE IF(METHOD.EQ.5) THEN
C
C CCD
C
       CCD=.TRUE.
      ELSE IF(METHOD.EQ.6) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.7) THEN
       UCC=.TRUE.
      ELSE IF(METHOD.EQ.8) THEN
       CCD=.TRUE.
      ELSE IF(METHOD.EQ.9) THEN
       UCC=.TRUE.
      ELSE IF(METHOD.EQ.10) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.11) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.13) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.14) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.15) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.16) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.21) THEN
       QCISD=.TRUE.
      ELSE IF(METHOD.EQ.22) THEN
       CCSD=.TRUE.
      ELSE IF(METHOD.EQ.23) THEN
       QCISD=.TRUE.
      ELSEIF(METHOD.EQ.24)THEN
       CCD=.TRUE.
      ELSEIF(METHOD.EQ.25)THEN
       CCSD=.TRUE.
      ENDIF
C 
      IF(IFLAGS(83).EQ.1) THEN
       DOALL=.TRUE.
       NOABCD=.FALSE.
      ELSE IF(IFLAGS(83).EQ.2) THEN
       DOALL=.FALSE.
       NOABCD=.TRUE.
      ENDIF
C
C WRITE HEADER TO OUTPUT FILE
C
      IF(IUHF.EQ.0) THEN
C
       IF(DOALL) THEN
C
        write(*,*) ' Full RHF integral transformation'
C
       ELSE
C
        write(*,*) ' Partial RHF integral transformation'
C
       ENDIF
C
      ELSE
C
       IF(DOALL) THEN
C
        write(*,*) ' Full UHF integral transformation'
C
       ELSE
C
        write(*,*) ' Partial UHF integral transformation'
C
       ENDIF
C
      ENDIF
C
      RETURN
      END
