      
      SUBROUTINE MKDSYM
      IMPLICIT INTEGER(A-H,O-Z)
      INTEGER POP,VRT,DIRPRD
C
C THIS ROUTINE FILLS THE COMMON /DSYM/
C FOR A GIVEN IRREP IRREPX
C
CEND
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NJUNK(18)
      COMMON/DSYM/IRREPX,IPERT,NDT(2),NDF1(2),NDF2(2),
     &            IOFFIJ(8,2),IOFFAB(8,2),IOFFAI(8,2)
C
      DO 1000 ISPIN=1,2
C
       NDT(ISPIN)=IRPDPD(IRREPX,8+ISPIN)
       NDF1(ISPIN)=IRPDPD(IRREPX,20+ISPIN)
       NDF2(ISPIN)=IRPDPD(IRREPX,18+ISPIN)
C
       IOFFIJ(1,ISPIN)=1
       IOFFAB(1,ISPIN)=1
       IOFFAI(1,ISPIN)=1
C
       DO 100 IRREPR=1,NIRREP-1
C
        IRREPL=DIRPRD(IRREPX,IRREPR)
C
        IOFFIJ(IRREPR+1,ISPIN)=IOFFIJ(IRREPR,ISPIN)+
     &                  POP(IRREPR,ISPIN)*POP(IRREPL,ISPIN)
        IOFFAB(IRREPR+1,ISPIN)=IOFFAB(IRREPR,ISPIN)+
     &                  VRT(IRREPR,ISPIN)*VRT(IRREPL,ISPIN)
        IOFFAI(IRREPR+1,ISPIN)=IOFFAI(IRREPR,ISPIN)+
     &                  POP(IRREPR,ISPIN)*VRT(IRREPL,ISPIN)
C
100     CONTINUE
C
1000   CONTINUE
C
       RETURN
       END
