      SUBROUTINE OOCTRN(A1,A2,DIS,NUM,SCR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*80 FNAME
      INTEGER DIS
      DIMENSION A1(NUM,DIS),A2(DIS,NUM),SCR(NUM)
C
      CALL GFNAME('SCRATCH ',FNAME,ILENGTH)
      OPEN(UNIT=89,FILE=FNAME(1:ILENGTH),FORM='UNFORMATTED',
     &     ACCESS='SEQUENTIAL')
C
      DO 100 I=1,DIS
       WRITE(89) (A1(J,I),J=1,NUM)
100   CONTINUE
C
      REWIND(UNIT=89)
C
      DO 200 I=1,DIS
       READ(89) (SCR(J),J=1,NUM)
       CALL SCOPY(NUM,SCR,1,A2(I,1),DIS)
200   CONTINUE
C
      CLOSE(UNIT=89,STATUS='DELETE')
C
      RETURN
      END
