      SUBROUTINE ST2324(ICORE,MXCOR)
C
C THIS ROUTINE RESORTS LIST 23 AND 24 AS THEY ARE NEEDED
C FOR MBPT(N) AND CCSD SECOND DERIVATIVE CALCULATIONS. 
C CURRENTLY THE RESORTED LISTS ARE WRITTEN BACK TO
C THE LISTS 23 AND 24.
C
C THIS ROUTINE IS ONLY CALLED FOR UHF AND ROHF.
C
CEND
C 
C CODED APRIL/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      CHARACTER*4 SPCASE(2)
      DIMENSION ICORE(MXCOR)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMPOP/IPRDPD(8,22),ISYTYP(2,500),NJUNK(18)
C
      DATA SPCASE /'AAAA','BBBB'/
C
      DO 1000 ISPIN=1,2
C
       LENGTH=ISYMSZ(ISYTYP(1,22+ISPIN),ISYTYP(2,22+ISPIN))
C
       I001=1
       I002=I001+LENGTH*IINTFP
       I003=I002+LENGTH*IINTFP
       IF(I003.GE.MXCOR) CALL INSMEM('ST2324',I003,MXCOR)
C
       CALL GETALL(ICORE(I001),LENGTH,1,22+ISPIN)
C
       CALL SSTRNG(ICORE(I001),ICORE(I002),LENGTH,LENGTH,
     &             ICORE(I003),SPCASE(ISPIN))
C
       CALL PUTALL(ICORE(I002),LENGTH,1,22+ISPIN)
C
1000  CONTINUE
C
      RETURN
      END
