      SUBROUTINE ABSGRN(U,ABP,ABM,ABPM,ABVEC,AMVEC,ABVEC1,UVAL,UVEC
     X ,WVAL,WVEC,PORT,SVEC,REDVEC,IVRT,IOCC,IVRTS,IOCCS
     X ,DEN,FP,F,E,IA,HMO,EVAL,EVEC,ENRG,UPDATE,
     X ASMALL,ASQUARE,ASCALE,ICONV,MCOMP,XX,IX,NIREP,NSIZ1,NSIZ3,NSIZO,
     X NSIZVO,NINTMX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*1 AXYZ 
      DIMENSION IVRT(NSIZVO),IOCC(NSIZVO)
     X ,IVRTS(NSIZVO,NIREP),IOCCS(NSIZVO,NIREP)
      DIMENSION U(NSIZ1,NSIZO,3),ABP(1),ABM(1),ABPM(1)
     X ,ABVEC(NSIZVO,MCOMP),AMVEC(NSIZVO,MCOMP),ABVEC1(NSIZVO,MCOMP)
     X ,UVEC(1),EVAL(NSIZ1),EVEC(NSIZ1,NSIZ1),ENRG(3,6)
      DIMENSION SVEC(1),REDVEC(1)
      DIMENSION F(NSIZ1,NSIZ1,3),E(NSIZO,NSIZO,3),HMO(NSIZ3,3)
      DIMENSION XX(NINTMX),IX(NINTMX),FP(1),IA(1),DEN(1)
     X ,UVAL(1),WVAL(1),WVEC(1),PORT(1)
      DIMENSION AXYZ(3)
C ....... for linear reduced equation solver
      DIMENSION UPDATE(1),ASMALL(1),ASQUARE(1),ASCALE(1),ICONV(1)
      COMMON /LRDUCE/ CONVI
      COMMON /LRDUC1/ KMAX
      COMMON/SWPPP/INP,IAMO,IFAMO,IINDO,IORTH               
C .........................................
      COMMON/INFOA/NBASIS,NUMSCF,NX,NMO2,NOC,NVT,NVO     
      COMMON/INFSYM/NSYMHF,NSO(8),NOCS(8),NVTS(8),IDPR(8,8),NVOS(8)
     X ,NIJS(8),NIJS2(8),NRDS(8),NIJSR(8)
      COMMON/INFPRS/IPRSYM(12),NPRSYM(8),JPRSYM(8,12)
      COMMON/THRES/ TOLPER,DEGEN,EPSI
      COMMON/THRE1/ NITER,MAXIT
      COMMON/IPRNT/ IOPEV,IOPDA,IOPU,IOPFE,IOPPR,IWRPA
      COMMON/ILINEA/ISALPH,IDALPH
      DATA ZERO,ONE,TWO,THREE,FOUR/0.D0,1.D0,2.D0,3.D0,4.D0/ 
      DATA AXYZ/'x','y','z'/
      SQRT2= SQRT(TWO)
C ... one root required 
C ..... scratch should have length of 2*NVO at least
      WRITE(6,*) ' now in ABSGRN'
      DO 30 MCOM=1,MCOMP
C     write(6,*) 'MCOM = ',MCOM
      DO 21 I=1,NUMSCF              
      DO 21 J=1,NOC
      IJ=(I-1)*I/2+J 
      IF(I.GT.NOC) THEN 
      U(I,J,MCOM)=HMO(IJ,MCOM)
      ELSE                     
      U(I,J,MCOM)=ZERO
      END IF     
   21 CONTINUE        
C     WRITE(6,*) ' U with MCOM = ',MCOM
C     CALL OUTMXD(U(1,1,MCOM),NSIZ1,NBASIS,NOC)       
C     write(6,*) 'NSIZVO ',NSIZVO
C     WRITE(6,*) ' A+B matrix in ABSGRN with IPRSYM = ',IPRSYM(MCOM)
C     CALL OUTMXD(ABP(NIJS2(IPRSYM(MCOM))+1),NVOS(IPRSYM(MCOM)),
C    X NVOS(IPRSYM(MCOM)),NVOS(IPRSYM(MCOM)))               
C     WRITE(6,*) ' (A+B)*(A-B) matrix with IPRSYM = ',IPRSYM(MCOM)
C     CALL OUTMXD(ABPM(NIJS2(IPRSYM(MCOM))+1),NVOS(IPRSYM(MCOM)),
C    X NVOS(IPRSYM(MCOM)),NVOS(IPRSYM(MCOM)))               
C     write(6,*) 'i,ivrt,iocc,abvec'
      IPOSYM=IPRSYM(MCOM)
      NVOSYM=NVOS(IPOSYM)
C     write(6,*) ' IPOSYM,NVOSYM ',IPOSYM,NVOSYM
      DO 11 I=1,NVOSYM
C     ABVEC(I,MCOM)=0.D0
C     ABVEC1(I,MCOM)=0.D0
      IF(NITER.NE.0) THEN  
C     IISYM=IDPR(ISYMO(IVRT(I)),ISYMO(IOCC(I)))      
C     IF(IPRSYM(MCOM).EQ.IISYM) THEN
C     II = IVOS(IVRT(I),IOCC(I),IISYM)
      ABVEC(I,MCOM)= -U(IVRTS(I,IPOSYM),IOCCS(I,IPOSYM),MCOM) 
      ABVEC1(I,MCOM)= -U(IVRTS(I,IPOSYM),IOCCS(I,IPOSYM),MCOM) 
C     write(6,*) I,IVRTS(I,IPOSYM),IOCCS(I,IPOSYM),ABVEC(I,MCOM)
C     END IF
      END IF
   11 CONTINUE
   30 CONTINUE
C .................................. 
      DO 92 MCOM=1,MCOMP
      MCOMS=IPRSYM(MCOM)
      NVOSYM=NVOS(MCOMS)
      NREDUC=NRDS(MCOMS)
C     CALL GRNSTAT(ABP(NIJS2(MCOMS)+1),ABM(NIJS2(MCOMS)+1),ABPM(NIJS2
C    X(MCOMS)+1),UVAL(NIJS(MCOMS)+1),UVEC(NIJS2(MCOMS)+1),WVAL(NIJS
C    X(MCOMS)+1),WVEC(NIJS2(MCOMS)+1),PORT(NIJS2(MCOMS)+1),
C    X ABVEC(1,MCOM),AMVEC(1,MCOM),ABVEC1(1,MCOM),NVOSYM,NREDUC)
      CALL RPA0(SVEC(NIJSR(MCOMS)+1),WVAL(NIJS(MCOMS)+1),REDVEC,
     X ABVEC(1,MCOM),ABVEC1(1,MCOM),NVOSYM,NREDUC)
   92 CONTINUE
      DO 31 MCOM=1,MCOMP    
      MCOMS=IPRSYM(MCOM) 
      DO 15 I=1,NX
      FP(I)=ZERO
   15 DEN(I)=ZERO
      DO 16 I=1,NVO
      IVT=IVRT(I)
      IOC=IOCC(I)
   16 U(IVT,IOC,MCOM)=ZERO
      WRITE(6,*) ' Solution for the linear equation MCOM = ',MCOM
      NVOSYM=NVOS(MCOMS)
C     write(6,*) ' MCOMS,NVOSYM ',MCOMS,NVOSYM
      DO 20 I=1,NVOSYM
      IVT= IVRTS(I,MCOMS)
      IOC= IOCCS(I,MCOMS)
C     U(IVT,IOC,MCOM)= 0.D0
C     IISYM=IDPR(ISYMO(IVT),ISYMO(IOC))      
C     IF(IISYM.EQ.IPRSYM(MCOM)) THEN
C     II = IVOS(IVT,IOC,IISYM)
      U(IVT,IOC,MCOM)=ABVEC(I,MCOM)
C     END IF
      IJD=(IVT-1)*IVT/2+IOC
      DEN(IJD)=TWO*U(IVT,IOC,MCOM)
C     write(6,*) IVT,IOC,U(IVT,IOC,MCOM)
   20 CONTINUE
      IF(IOPU.NE.0) THEN
      WRITE(6,*) ' U1 '
      CALL OUTMXD(U(1,1,MCOM),NSIZ1,NUMSCF,NOC)
      END IF
      DO 18 M=1,3
      ENRG(M,MCOM)= ZERO
      DO 19 I=1,NVO 
      IJD=(IVRT(I)-1)*IVRT(I)/2+IOCC(I)
      ENRG(M,MCOM) = ENRG(M,MCOM) + U(IVRT(I),IOCC(I),MCOM)*HMO(IJD,M)
   19 CONTINUE
      ENRG(M,MCOM) = -ENRG(M,MCOM)*FOUR
   18 CONTINUE
      WRITE(6,*) ' Alpha '
C     WRITE(6,*) ' component = ',MCOM
C     WRITE(6,*) ' Alpha = ',(ENRG(M,MCOM),M=1,3)
      WRITE(6,200) AXYZ(MCOM),AXYZ(1),ENRG(1,MCOM),AXYZ(MCOM)
     X ,AXYZ(2),ENRG(2,MCOM),AXYZ(MCOM),AXYZ(3),ENRG(3,MCOM)
  200 FORMAT(1H ,2A1,' = ',F20.10,'  ',2A1,' = ',F20.10,'  ',
     X 2A1,' = ',F20.10)
      IF(ISALPH.EQ.0) THEN
      IF(IFAMO.EQ.0) THEN
      CALL FMOK(DEN,FP,XX,IX,NINTMX,IA)
      ELSE
      CALL DENSP(NBASIS,NVO,IVRT,IOCC,EVEC,ABVEC(1,MCOM),DEN)
      IF(IINDO.EQ.0) THEN
      CALL FNOK(DEN,EVEC,FP,NBASIS,NSIZ1,XX,IX,NINTMX,IA)
      ELSE
      CALL FINDO(NBASIS,NVO,IVRT,IOCC,EVEC,DEN,FP)
      END IF
      END IF
      IJ=0
      DO 100 I=1,NUMSCF
      DO 100 J=1,I
      F(I,J,MCOM)=ZERO
      IJ=IJ+1
      IJL=(J-1)*NUMSCF+I
      IF(IFAMO.EQ.0) IJL=IJ
      F(I,J,MCOM)= HMO(IJ,MCOM)+FP(IJL)
      F(J,I,MCOM)=F(I,J,MCOM)
  100  CONTINUE
      IF(IOPFE.NE.0) THEN
      WRITE(6,*) '  f-matrix ,component = ',MCOM
      CALL OUTMXD(F(1,1,MCOM),NSIZ1,NUMSCF,NUMSCF)
      END IF
      DO 26 I=1,NOC
      DO 26 J=1,NOC
      E(I,J,MCOM)=F(I,J,MCOM)
   26 CONTINUE
      END IF
   31 CONTINUE
      ABAR=(ENRG(1,1)+ENRG(2,2)+ENRG(3,3))/THREE
      DELA= SQRT((ENRG(1,1)-ENRG(2,2))**2
     X          +(ENRG(2,2)-ENRG(3,3))**2
     X          +(ENRG(3,3)-ENRG(1,1))**2)/SQRT2
      WRITE(6,*) '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
      WRITE(6,*) ' Average Alpha = ',ABAR
      WRITE(6,*) ' Delta Alpha = ',DELA
      WRITE(6,*) '>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>'
      IF(ISALPH.NE.0) STOP
      RETURN
      END
