      DOUBLE PRECISION FUNCTION TRACEP(A,B,N)
C     IMPLICIT REAL*8 (A-H,O-Z)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C     ----- TRACE OF PRODUCT OF 2 SYMMETRIC MATRICES
C           -A- AND -B- STORED LINEARLY -----
      DIMENSION A(2),B(2)
      DATA ZERO,TWO /0.0D+00,2.0D+00/
      TRACEP=ZERO
      K=0
      DO 20 I=1,N
      DO 10 J=1,I
      K=K+1
   10 TRACEP=TRACEP+A(K)*B(K)*TWO
   20 TRACEP=TRACEP-A(K)*B(K)
      RETURN
      END
