      SUBROUTINE TGCAL (PWP,TGAM,NCQRS,NNN3,IFPL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL IFPL(3)
      DIMENSION PWP(NCQRS,NNN3,3),TGAM(NCQRS)
      CALL ZERO (TGAM,NCQRS)
      DO 30 I=1,3
      IF (IFPL(I)) GO TO 30
      DO 10 J=2,NNN3
      DO 10 K=1,NCQRS
   10 PWP(K,J,I) = PWP(K,J-1,I) * PWP(K,1,I)
      DO 20 K=1,NCQRS
   20 TGAM(K) = TGAM(K) + PWP(K,2,I)
   30 CONTINUE
      RETURN
      END
