C
      SUBROUTINE COMPPR(PROP, DENS, PRPINT, NSIZ, IUHF)
C 
C THIS ROUTINE READS A LIST OF PROPERTY INTEGRALS AND THE DENSITY
C MATRIX AND COMPUTES THE PARTICULAR PROPERTY.
C      
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      CHARACTER*32 CRAP
      DIMENSION DENS(NSIZ, NSIZ), PRPINT(NSIZ, NSIZ),
     &          BUF(600), IBUF(600)
      DIMENSION IXX(2)
      EQUIVALENCE (PRPNUC,IXX(1))
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      NNM1O2(IX) = (IX*(IX-1))/2
      IEXTI(IX)  = 1 + (-1+INT(DSQRT(8.D0*IX+0.999D0)))/2
      IEXTJ(IX)  = IX - NNM1O2(IEXTI(IX))
      FACT       = 2.00D+00 - DFLOAT(IUHF)
C 
C READ IN THE PROPERTY INTEGRALS
C
      CALL ZERO (PRPINT, NSIZ*NSIZ)
1     READ(30) BUF, IBUF, NUT
      
      DO 10 I = 1, NUT
         INDI = IEXTI(IBUF(I))
         INDJ = IEXTJ(IBUF(I))
         PRPINT(INDI, INDJ) = BUF(I)
         PRPINT(INDJ, INDI) = BUF(I)
 10   CONTINUE
C
      IF(NUT .EQ. 600) GOTO 1
C
C COMPUTE THE PROPERTY
C
      PROP = PROP + SDOT(NSIZ*NSIZ, DENS, 1, PRPINT, 1)*FACT
C
      RETURN
      END
