       SUBROUTINE SOLVESMALL(N, ASMALL, YSMALL, ZSMALL,
     &    ZOUT, Y1, Z, HZ, NPERT, NDIM, SCR, MAXCOR)
C
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      LOGICAL CHECK
      DIMENSION ASMALL(N,N), YSMALL(N,NPERT), ZSMALL(N,NPERT),
     &   ZOUT(NDIM,NPERT), Y1(NDIM, NPERT), Z(NDIM, N),
     &   HZ(NDIM, N), SCR(MAXCOR)
C
      COMMON /FLAGS/ IFLAGS(100)
C
      DATA ONE,ONEM,ZILCH,TWO /1.0D0,-1.0D0,0.0D0,2.0D0/
C
C CONSTRUCT SMALL QUANTITIES
C
      CALL XGEMM('T', 'N', N, NPERT, NDIM, ONE, Z, NDIM,
     &   Y1, NDIM, ZILCH, YSMALL, N)
        CALL XGEMM('T', 'N', N, N, NDIM, ONE, Z, NDIM,
     &     HZ, NDIM, ZILCH, ASMALL, N)
C
C  INVERT ASMALL
C
        CALL MINV(ASMALL,N, N, SCR, DET, TOL, 0, 1)
C
C  CONSTRUCT SOLUTION
C
        CALL XGEMM('N', 'N', N, NPERT, N, ONE, ASMALL, N,
     &     YSMALL, N, ZILCH, ZSMALL, N)
C
C  CHECK SOLUTION
C
        CHECK = IFLAGS(1) .GE. 5
        IF (CHECK) THEN
          CALL XGEMM('T', 'N', N, N, NDIM, ONE, Z, NDIM,
     &       HZ, NDIM, ZILCH, ASMALL, N)
          CALL XGEMM('N', 'N', N, NPERT, N, ONEM, ASMALL, N,
     &       ZSMALL, N, ONE, YSMALL, N)
          DIFF = 0.0D0
          DO I = 1, N
            DO J= 1, NPERT
              DIFF = DIFF + ABS(YSMALL(I,J))
            ENDDO
          ENDDO
          WRITE(6,*) ' RESIDUAL IN ASMALL', DIFF
C          CALL OUTPUT(YSMALL,1,N, 1, NPERT, N, NPERT,1)
        ENDIF
C
C  CONSTRUCT FULL SOLUTION VECTOR
C
        CALL XGEMM('N', 'N', NDIM, NPERT, N, ONE, Z, NDIM,
     &     ZSMALL, N, ZILCH, ZOUT, NDIM)
C
      RETURN
      END
