      SUBROUTINE DHBIAJK0(ICORE,MAXCOR,IUHF,IRREPZ,LISTZ0,LISTW0,
     &                    FACT,FACTI)
C
C ADDS EITHER DIFFERENTIATED OR UNDIFFERENTIATED INTEGRALS TO THE
C W(IA,JK) QUANTITY.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR),I0T(2)
      DOUBLE PRECISION ONE,ONEM,ZILCH,FACT,FACTI
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      COMMON/SYMLOC/ISYMOFF(8,8,25)
C
      DATA ONE,ONEM,ZILCH /1.0D0,-1.0D0,0.0D0/
C
      DO 10 ISPIN=4,4-3*IUHF,-1
       LISTZ=LISTZ0+ISPIN
       LISTW=LISTW0+ISPIN
       ISIZEZ=IDSYMSZ(IRREPZ,ISYTYP(1,LISTZ),ISYTYP(2,LISTZ))
       I000=1
       I010=I000+IINTFP*ISIZEZ
       I020=I010+IINTFP*ISIZEZ
       CALL GETALL(ICORE(I010),ISIZEZ,IRREPZ,LISTZ)
       CALL GETALL(ICORE(I000),ISIZEZ,IRREPZ,LISTW)
       CALL SSCAL(ISIZEZ,FACTI,ICORE(I000),1)
       CALL SAXPY (ISIZEZ,FACT,ICORE(I010),1,ICORE(I000),1)
C       call checksum("Hbijka",ICORE(I000),ISIZEZ,S)
       CALL PUTALL(ICORE(I000),ISIZEZ,IRREPZ,LISTZ)
10    CONTINUE
C
      RETURN
      END
