      SUBROUTINE ADDDT(DENS,SCR,NSIZE,NIRREP,NUM,LIST,ISPIN)
C
C  THIS ROUTINE ADDS THE TRIPLE CONTRIBUTION
C  TO THE OCC-OCC (VIRT-VIRT) PART OF THE
C  DENSITY.
C
CEND
C
C CODED 6/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION DENS(1),SCR(1),NUM(8)
C
      CALL GETLST(SCR,1,1,1,ISPIN,LIST)
C
C  LOOP OVER ALL IRREPS
C
      IOFF1=0
      IOFF2=0
      DO 100 IRREP=1,NIRREP
C
       N=NUM(IRREP)
C
       DO 150 I=1,N
C
       DENS(IOFF1+I+(I-1)*N)=DENS(IOFF1+I+(I-1)*N)+SCR(IOFF2+I)
C
150    CONTINUE 
C
       IOFF1=IOFF1+N*N
       IOFF2=IOFF2+N
C
100   CONTINUE
C
      RETURN
      END
