      SUBROUTINE PHBARXC2(N1, N1AA, X1IN, X1OUT, SCR, MAXCOR,
     &   IUHF, ISIDE, IRREPX)
C
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      DIMENSION SCR(MAXCOR), X1IN(N1), X1OUT(N1)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/EXTRAP/MAXEXP,NREDUCE,NTOL,NSIZEC
C
      CALL ZERO(SCR, NSIZEC)
      CALL SCOPY(N1,X1IN,1,SCR,1)
      CALL UPDATES(IRREPX,SCR,444,0,IUHF)
      CALL HBARXC2(SCR, MAXCOR*IINTFP, IUHF, ISIDE, IRREPX,
     &   .TRUE., .TRUE. , .TRUE. , .FALSE.)
      CALL GETLST(X1OUT, 1,1,1,3, 490)
      IF (IUHF .NE. 0) CALL GETLST(X1OUT(N1AA+1),1,1,1,4,490)
C
      I000 = 1
      I010 = I000 + NSIZEC
      I020 = I010 + NSIZEC
C
      CALL LOADVEC2(IRREPX,SCR,MAXCOR,IUHF,490,2,460,NSIZEC,
     &              .FALSE.)
      CALL GETLST(SCR(I010),1,1,1,1,472)
      DO I = N1, NSIZEC - 1
        SCR(I000 + I) = - SCR(I000+I) / SCR(I010+I)
      ENDDO
      CALL ZERO(SCR, N1)
      CALL UPDATES(IRREPX,SCR,444,0,IUHF)
      CALL HBARXC2(SCR, MAXCOR*IINTFP, IUHF, ISIDE, IRREPX,
     &   .TRUE., .TRUE. , .TRUE. , .FALSE.)
      CALL SCOPY(N1, X1OUT,1,SCR,1)
      CALL GETLST(X1OUT, 1,1,1,3, 490)
      IF (IUHF .NE. 0) CALL GETLST(X1OUT(N1AA+1),1,1,1,4,490)
      DO I = 1, N1
        X1OUT(I) = X1OUT(I) + SCR(I)
      ENDDO
C
      RETURN
      END
