      SUBROUTINE SPINAD56(ICORE,MAXCOR,IUHF)
C
C THIS ROUTINE SPIN ADAPTS THE RING INTERMEDIATES
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL CIS,EOMCC,FULDIAG,INCORE,READGUES
      DOUBLE PRECISION ONE,ZILCH,ONEM,HALF,HALFM,TWO
      DIMENSION ICORE(MAXCOR),IOFFO(2),IOFFV(2)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREP0(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/METH/CIS,EOMCC,FULDIAG,INCORE,READGUES
      COMMON/INFO/NOCCO(2),NVRTO(2)
C 
      DATA ONE,ONEM /1.0D0,-1.0D0/
      DATA ZILCH,HALF,HALFM,TWO /0.0D0,0.5D0,-0.5D0,2.0D0/
C
      LIST1=56
      LIST2=58
      LIST3=56
C
C READ IN ALL OF THE TWO-PARTICLE CONTRIBUTIONS, RESORT THEM AND
C HOLD IN CORE
C
      DO 100 ISPIN=1,1+IUHF
       IF(IUHF.EQ.0)THEN
        ISIZE=ISYMSZ(ISYTYP(1,56),ISYTYP(2,56))
        I000=1
        I010=I000+ISIZE*IINTFP
        I020=I010+ISIZE*IINTFP
        CALL GETALL(ICORE(I000),ISIZE,1,56)
        CALL GETALL(ICORE(I010),ISIZE,1,58)
        CALL SSCAL(ISIZE,TWO,ICORE(I000),1)
        CALL SAXPY(ISIZE,ONEM,ICORE(I010),1,ICORE(I000),1)
       ELSE
        LISTAA=53+ISPIN
        ISIZE=ISYMSZ(ISYTYP(1,LISTAA),ISYTYP(2,LISTAA))
        I000=1
        I010=I000+ISIZE*IINTFP
        I020=I010+ISIZE*IINTFP
        CALL GETALL(ICORE(I000),ISIZE,1,LISTAA)
C        CALL VMINUS(ICORE(I000),ISIZE)
       ENDIF
C
       LISTDUMP=LIST3
       IF(IUHF.NE.0)LISTDUMP=LISTAA
       CALL PUTALL(ICORE(I000),ISIZE,1,LISTDUMP)
C
100   CONTINUE
C
      RETURN
      END
