      SUBROUTINE CMOI(IRREPP,IUHF,NPERT,LISTOFF,FULL,ABAB,AIAI,
     &                IENTER,IOFF)
C
C  THIS ROUTINE CREATES THE LISTS FOR THE PERTURBED ONE
C  ELECTRON INTEGRAL  MATRIX IN THE MO BASIS.
C
CEND
C
C  CODED JAN/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL FULL,ABAB,AIAI
C
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NJUNK(18)
C
C  LOOP OVER SPIN CASES
C
      IOFFAB=2
      IOFFAI=4
      IF(.NOT.ABAB) IOFFAI=2
      DO 100 ISPIN=1,IUHF+1
C
      IF(FULL) THEN
       CALL UPDMOI(NPERT,IRPDPD(IRREPP,20+ISPIN),IRREPP,
     &             LISTOFF+ISPIN,IENTER,IOFF)
       IF(LISTOFF.EQ.175) THEN
        CALL UPDMOI(NPERT,IRPDPD(IRREPP,20+ISPIN),IRREPP,
     &              LISTOFF+ISPIN+8,IENTER,IOFF)
       ENDIF
       IENTER=0
       IF(ABAB) THEN
        CALL UPDMOI(NPERT,IRPDPD(IRREPP,18+ISPIN),IRREPP,
     &              LISTOFF+IOFFAB+ISPIN,0,0)
       ENDIF
      ENDIF
       IF(AIAI) THEN
        CALL UPDMOI(NPERT,IRPDPD(IRREPP,8+ISPIN),IRREPP,
     &              LISTOFF+IOFFAI+ISPIN,0,0)
       ENDIF
C
100   CONTINUE
C
      RETURN
      END
