      SUBROUTINE CMROHF(IRREPP,NPERT,LISTOFF)
C
C THIS ROUTINE CREATES ADDITIONAL LISTS FOR U(I,J)
C AND U(a,b) REQUIRED FOR ROHF-MBPT[2] SECOND 
C DERIVATIVE CALCULATION
C
CEND
C
C  CODED JUNE/92 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL FULL,ABAB
C
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NJUNK(18)
C
C   U(I,J)^chi
C
      CALL UPDMOI(NPERT,IRPDPD(IRREPP,21),IRREPP,
     &            LISTOFF,0,0)
      IENTER=0
      IOFF=0
C
C   U(a,b)^chi
C
      CALL UPDMOI(NPERT,IRPDPD(IRREPP,20),IRREPP,
     &            LISTOFF+1,0,0)
C
      RETURN
      END
