      SUBROUTINE MKARHF3(IRREP,AMAT,SCRATCH)
C
C   THIS ROUTINE CALCULATES THE A-MATRIX USED IN THE
C   SOLUTION OF THE CPHF EQUATION FOR RHF WAVE FUNCTIONS
C   IN THE CASE OF AN IMAGINARY PERTURBATION.
C   NOTE, ONLY THE BLOCK OF THE A MATRIX CORRESPONDING TO
C   IRREP OF THE PERTURBATION IS REQUIRED. FURTHER,
C   FOR RHF WE ARE USING A SPIN-ADAPTED VERSION.
C   THE FORMULA IS GIVEN BY
C
C   A(AI,BJ) = <AJ||IB> - <AB||IJ>
C
C            = <Aj||Ib> - <Aj||Bi> - <Ab||Ij> + <Ab||Ji>
C
C            = <Ai||Jb> - <Ai||Bj>
C
C               LIST 21    LIST 25
C
C   IRREP : THE IRREP OF THE CONSIDERED PERTURBATION
C   AMAT : WILL RETURN THE CORRESPONDING PART OF THE A MATRIX
C   SCRATCH : SCRATCH VECTOR REQUIRED TO CONSTRUCT THE A MATRIX
C
CEND
C
C   CODED APRIL/91  JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DIRPRD,DISSYW,POP,VRT
      DIMENSION AMAT(1),SCRATCH(1)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NJUNK(6)
C
      DATA ONE,ONEM,TWO /1.0D+0,-1.0D+0,2.0D+0/
C
C   READ IN FIRST THE INTEGRALS <AB//IJ> (ORDERING AI,BJ) 
C   THEY ARE STORED ON LIST 19
C
      LISTW=21
      NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
      DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
C
      CALL GETLST(AMAT,1,NUMSYW,2,IRREP,LISTW)
C
C   NOW SUBTRACTTHE INTEGRALS <AJ//BI> (ORDERING AI,BJ)
C   THEY ARE STORED ON LIST 25
C
      LISTW=25
      NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
      DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
C
      CALL GETLST(SCRATCH,1,NUMSYW,2,IRREP,LISTW)
C
      CALL SAXPY(NUMSYW*DISSYW,ONEM,SCRATCH,1,AMAT,1)
C
C
C  ALL DONE
C
      RETURN
      END      
