      SUBROUTINE G4AA5(GAMMA,BUF,GOFF,DOIRR,LENGAM,ISPIN,FABCI)
C
C THIS ROUTINE PROCESSES THE G<AB,CI> GAMMA LIST
C  AND FILLS OUT THE ABCD SYMMETRY CASE MULLIKEN ORDERED GAMMA FOR 
C  SPIN CASE AAAA.  THIS IS FOR UHF CALCULATIONS ONLY!
C
C
C          12 34        13 24
C        G(AC,BI) <-- g<AB,CI>
C
C          12 34        24 13
C        G(CA,IB) <-- g<AB,CI>
C
C          12 34        31 42
C        G(BI,AC) <-- g<AB,CI>
C
C          12 34        42 31
C        G(IB,CA) <-- g<AB,CI>
C
C          12 34        23 14
C        G(CA,BI) <-- g<AB,CI>
C
C          12 34        14 23
C        G(AC,IB) <-- g<AB,CI>
C
C          12 34        32 41
C        G(IB,AC) <-- g<AB,CI>
C
C          12 34        41 32
C        G(BI,CA) <-- g<AB,CI>
C
C
C ONE MUST BE VERY CAREFUL HERE ABOUT SIGNS SINCE ONLY THOSE
C  IRREP PAIRS PQ ARE ON DISK SUCH THAT P<Q.  THIS MAKES THE
C  LOGIC FOR THIS ROUTINE SLIGHTLY COMPLICATED!  THIS IS HANDLED
C  BY SUBROUTINE GETFAC, WHICH DETERMINES THE SIGN AND REORDERS
C  EACH IRREP QUADRUPLET IN AN APPROPRIATE WAY.  COMPLICATED STUFF.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GAMMA(LENGAM),BUF(1),X,X1,X2 ,FACTOR,FACT
      DOUBLE PRECISION FABIJ,FIJKL,FABCD,FAIBJ,FABCI,FIJKA
      INTEGER GOFF(8,8,8,8),IDID(8),IOFFSL(8)
      INTEGER IOFFSR(8),DOIRR(42,4),IPTR(2),IND(2)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MOPOPS/ MOPOP(8)
C
      INDXF(I,J,N)=I+(J-1)*N
      INDXT(I,J)  =I+(J*(J-1))/2
      NNP1O2(I)   =(I*(I+1))/2
      NNM1O2(I)   =(I*(I-1))/2
C
C CALCULATE HOW MANY UNIQUE ABCD SYMMETRY SETS THERE ARE
C
      IF(NIRREP.EQ.8)THEN
       NUMABCD=42
      ELSEIF(NIRREP.EQ.4)THEN
       NUMABCD=3
      ENDIF
C     
      LISTABCI=126+ISPIN
      DO 100 ICOUNT=1,NUMABCD
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
C
       IOFFSET=GOFF(IRREP1M,IRREP2M,IRREP3M,IRREP4M)
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       MAXL1=MOPOP(IRREP1M)
       MAXL2=MOPOP(IRREP3M)
C
       IRREPGET=DIRPRD(IRREP2M,IRREP4M)
C
       CALL GETFAC2(IRREP1M,IRREP3M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
C          12 34        13 24
C        G(AC,BI) <-- g<AB,CI>
C
       IOFFR=1
       IOFFL=1
       DO 2000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFR=IOFFR+VRT(IRREPB,ISPIN)*POP(IRREPA,ISPIN)
        IF(IRREPB.GT.IRREPA)GOTO 2000
        IOFFSL(IRREPA)=IOFFL
        IOFFL=IOFFL+VRT(IRREPB,ISPIN)*VRT(IRREPA,ISPIN)
2000   CONTINUE
C
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMI=POP(IRREP4M,ISPIN)
       NUMC=VRT(IRREP2M,ISPIN)
       NUMB=VRT(IRREP3M,ISPIN)
       NUMA=VRT(IRREP1M,ISPIN) 
       DO 120 INDXI=1,NUMI
        DO 130 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP2M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 140 INDXB=1,NUMB
          DO 150 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP3M,ISPIN)
           IND(1)=INDXA+POP(IRREP1M,ISPIN)
           GINDXL=INDXF(IND(IPTR(1)),INDC,MAXL1)
           GINDXR=INDXF(IND(IPTR(2)),INDI,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
150       CONTINUE
140      CONTINUE
130     CONTINUE
120    CONTINUE
C
C          12 34        24 13
C        G(CA,IB) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP2M,IRREP4M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP3M)
       IFIRST=IOFFSL(IRREP4M)
       NUMI=POP(IRREP3M,ISPIN)
       NUMC=VRT(IRREP1M,ISPIN)
       NUMB=VRT(IRREP4M,ISPIN)
       NUMA=VRT(IRREP2M,ISPIN) 
       DO 220 INDXI=1,NUMI
        DO 230 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP1M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 240 INDXB=1,NUMB
          DO 250 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP4M,ISPIN)
           IND(1)=INDXA+POP(IRREP2M,ISPIN)
           GINDXL=INDXF(INDC,IND(IPTR(1)),MAXL1)
           GINDXR=INDXF(INDI,IND(IPTR(2)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
250       CONTINUE
240      CONTINUE
230     CONTINUE
220    CONTINUE
C
C          12 34        31 42
C        G(BI,AC) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP3M,IRREP1M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP1M)
       NUMI=POP(IRREP2M,ISPIN)
       NUMC=VRT(IRREP4M,ISPIN)
       NUMB=VRT(IRREP1M,ISPIN)
       NUMA=VRT(IRREP3M,ISPIN) 
       DO 320 INDXI=1,NUMI
        DO 330 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP4M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1M)
         DO 340 INDXB=1,NUMB
          DO 350 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP1M,ISPIN)
           IND(1)=INDXA+POP(IRREP3M,ISPIN)
           GINDXL=INDXF(IND(IPTR(2)),INDI,MAXL1)
           GINDXR=INDXF(IND(IPTR(1)),INDC,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
350       CONTINUE
340      CONTINUE
330     CONTINUE
320    CONTINUE
C
C          12 34        42 31
C        G(IB,CA) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP4M,IRREP2M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP2M)
       NUMI=POP(IRREP1M,ISPIN)
       NUMC=VRT(IRREP3M,ISPIN)
       NUMB=VRT(IRREP2M,ISPIN)
       NUMA=VRT(IRREP4M,ISPIN) 
       DO 420 INDXI=1,NUMI
        DO 430 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP3M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2M)
         DO 440 INDXB=1,NUMB
          DO 450 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP2M,ISPIN)
           IND(1)=INDXA+POP(IRREP4M,ISPIN)
           GINDXL=INDXF(INDI,IND(IPTR(2)),MAXL1)
           GINDXR=INDXF(INDC,IND(IPTR(1)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
450       CONTINUE
440      CONTINUE
430     CONTINUE
420    CONTINUE
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       IRREPGET=DIRPRD(IRREP2M,IRREP3M)
C
       IOFFR=1
       IOFFL=1
       DO 3000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFR=IOFFR+VRT(IRREPB,ISPIN)*POP(IRREPA,ISPIN)
        IF(IRREPB.GT.IRREPA)GOTO 3000
        IOFFSL(IRREPA)=IOFFL
        IOFFL=IOFFL+VRT(IRREPB,ISPIN)*VRT(IRREPA,ISPIN)
3000   CONTINUE
C
C          12 34        23 14
C        G(CA,BI) <-- g<AB,CI>
C
C
       CALL GETFAC2(IRREP2M,IRREP3M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMI=POP(IRREP4M,ISPIN)
       NUMC=VRT(IRREP1M,ISPIN)
       NUMB=VRT(IRREP3M,ISPIN)
       NUMA=VRT(IRREP2M,ISPIN) 
       DO 520 INDXI=1,NUMI
        DO 530 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP1M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 540 INDXB=1,NUMB
          DO 550 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP3M,ISPIN)
           IND(1)=INDXA+POP(IRREP2M,ISPIN)
           GINDXL=INDXF(INDC,IND(IPTR(1)),MAXL1)
           GINDXR=INDXF(IND(IPTR(2)),INDI,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
550       CONTINUE
540      CONTINUE
530     CONTINUE
520    CONTINUE
C
C          12 34        14 23
C        G(AC,IB) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP1M,IRREP4M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP3M)
       IFIRST=IOFFSL(IRREP4M)
       NUMI=POP(IRREP3M,ISPIN)
       NUMC=VRT(IRREP2M,ISPIN)
       NUMB=VRT(IRREP4M,ISPIN)
       NUMA=VRT(IRREP1M,ISPIN) 
       DO 620 INDXI=1,NUMI
        DO 630 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP2M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 640 INDXB=1,NUMB
          DO 650 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP4M,ISPIN)
           IND(1)=INDXA+POP(IRREP1M,ISPIN)
           GINDXL=INDXF(IND(IPTR(1)),INDC,MAXL1)
           GINDXR=INDXF(INDI,IND(IPTR(2)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
650       CONTINUE
640      CONTINUE
630     CONTINUE
620    CONTINUE
C
C          12 34        32 41
C        G(IB,AC) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP3M,IRREP2M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP2M)
       NUMI=POP(IRREP1M,ISPIN)
       NUMC=VRT(IRREP4M,ISPIN)
       NUMB=VRT(IRREP2M,ISPIN)
       NUMA=VRT(IRREP3M,ISPIN) 
       DO 720 INDXI=1,NUMI
        DO 730 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP4M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2M)
         DO 740 INDXB=1,NUMB
          DO 750 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP2M,ISPIN)
           IND(1)=INDXA+POP(IRREP3M,ISPIN)
           GINDXL=INDXF(INDI,IND(IPTR(2)),MAXL1)
           GINDXR=INDXF(IND(IPTR(1)),INDC,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
750       CONTINUE
740      CONTINUE
730     CONTINUE
720    CONTINUE
C
C          12 34        41 32
C        G(BI,CA) <-- g<AB,CI>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP4M,IRREP1M,IPTR,FACTOR)
       FACT=FABCI*FACTOR
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP1M)
       NUMI=POP(IRREP2M,ISPIN)
       NUMC=VRT(IRREP3M,ISPIN)
       NUMB=VRT(IRREP1M,ISPIN)
       NUMA=VRT(IRREP4M,ISPIN) 
       DO 820 INDXI=1,NUMI
        DO 830 INDXC=1,NUMC
         INDI=INDXI
         INDC=INDXC+POP(IRREP3M,ISPIN)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTABCI)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1M)
         DO 840 INDXB=1,NUMB
          DO 850 INDXA=1,NUMA
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXB+POP(IRREP1M,ISPIN)
           IND(1)=INDXA+POP(IRREP4M,ISPIN)
           GINDXL=INDXF(IND(IPTR(2)),INDI,MAXL1)
           GINDXR=INDXF(INDC,IND(IPTR(1)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
850       CONTINUE
840      CONTINUE
830     CONTINUE
820    CONTINUE
C

100   CONTINUE
      RETURN
      END
