      SUBROUTINE G4AA2(GAMMA,BUF,GOFF,DOIRR,LENGAM,ISPIN,FIJKA)
C
C THIS ROUTINE PROCESSES THE G<IJ,KA> GAMMA LIST
C  AND FILLS OUT THE ABCD SYMMETRY CASE MULLIKEN ORDERED GAMMA FOR 
C  SPIN CASE AAAA.  THIS IS FOR UHF CALCULATIONS ONLY!
C
C
C          12 34        13 24
C        G(IK,JA) <-- g<IJ,KA>
C
C          12 34        24 13
C        G(KI,AJ) <-- g<IJ,KA>
C
C          12 34        31 42
C        G(JA,IK) <-- g<IJ,KA>
C
C          12 34        42 31
C        G(AJ,KI) <-- g<IJ,KA>
C
C          12 34        23 14
C        G(KI,JA) <-- g<IJ,KA>
C
C          12 34        14 23
C        G(IK,AJ) <-- g<IJ,KA>
C
C          12 34        32 41
C        G(AJ,IK) <-- g<IJ,KA>
C
C          12 34        41 32
C        G(JA,KI) <-- g<IJ,KA>
C
C
C ONE MUST BE VERY CAREFUL HERE ABOUT SIGNS SINCE ONLY THOSE
C  IRREP PAIRS PQ ARE ON DISK SUCH THAT P<Q.  THIS MAKES THE
C  LOGIC FOR THIS ROUTINE SLIGHTLY COMPLICATED!  THIS IS HANDLED
C  BY SUBROUTINE GETFAC, WHICH DETERMINES THE SIGN AND REORDERS
C  EACH IRREP QUADRUPLET IN AN APPROPRIATE WAY.  COMPLICATED STUFF.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GAMMA(LENGAM),BUF(1),X,X1,X2 ,FACTOR,FACT
      DOUBLE PRECISION FABIJ,FIJKL,FABCD,FAIBJ,FABCI,FIJKA
      INTEGER GOFF(8,8,8,8),IDID(8),IOFFSL(8)
      INTEGER IOFFSR(8),DOIRR(42,4),IPTR(2),IND(2)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MOPOPS/ MOPOP(8)
C
      INDXF(I,J,N)=I+(J-1)*N
      INDXT(I,J)  =I+(J*(J-1))/2
      NNP1O2(I)   =(I*(I+1))/2
      NNM1O2(I)   =(I*(I-1))/2
C
C CALCULATE HOW MANY UNIQUE ABCD SYMMETRY SETS THERE ARE
C
      IF(NIRREP.EQ.8)THEN
       NUMABCD=42
      ELSEIF(NIRREP.EQ.4)THEN
       NUMABCD=3
      ENDIF
C     
      LISTIJKA=106+ISPIN
      DO 100 ICOUNT=1,NUMABCD
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
C
       IOFFSET=GOFF(IRREP1M,IRREP2M,IRREP3M,IRREP4M)
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       MAXL1=MOPOP(IRREP1M)
       MAXL2=MOPOP(IRREP3M)
C
       IRREPGET=DIRPRD(IRREP2M,IRREP4M)
C
       CALL GETFAC2(IRREP1M,IRREP3M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
C          12 34        13 24
C        G(IK,JA) <-- g<IJ,KA>
C
       IOFFR=1
       IOFFL=1
       DO 2000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFR=IOFFR+POP(IRREPB,ISPIN)*VRT(IRREPA,ISPIN)
        IF(IRREPB.GT.IRREPA)GOTO 2000
        IOFFSL(IRREPA)=IOFFL
        IOFFL=IOFFL+POP(IRREPB,ISPIN)*POP(IRREPA,ISPIN)
2000   CONTINUE
C
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMA=VRT(IRREP4M,ISPIN)
       NUMK=POP(IRREP2M,ISPIN)
       NUMJ=POP(IRREP3M,ISPIN)
       NUMI=POP(IRREP1M,ISPIN) 
       DO 120 INDXA=1,NUMA
        DO 130 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP4M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 140 INDXJ=1,NUMJ
          DO 150 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(IND(IPTR(1)),INDK,MAXL1)
           GINDXR=INDXF(IND(IPTR(2)),INDA,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
150       CONTINUE
140      CONTINUE
130     CONTINUE
120    CONTINUE
C
C          12 34        24 13
C        G(KI,AJ) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP2M,IRREP4M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP3M)
       IFIRST=IOFFSL(IRREP4M)
       NUMA=VRT(IRREP3M,ISPIN)
       NUMK=POP(IRREP1M,ISPIN)
       NUMJ=POP(IRREP4M,ISPIN)
       NUMI=POP(IRREP2M,ISPIN) 
       DO 220 INDXA=1,NUMA
        DO 230 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP3M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 240 INDXJ=1,NUMJ
          DO 250 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(INDK,IND(IPTR(1)),MAXL1)
           GINDXR=INDXF(INDA,IND(IPTR(2)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
250       CONTINUE
240      CONTINUE
230     CONTINUE
220    CONTINUE
C
C          12 34        31 42
C        G(JA,IK) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP3M,IRREP1M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP1M)
       NUMA=VRT(IRREP2M,ISPIN)
       NUMK=POP(IRREP4M,ISPIN)
       NUMJ=POP(IRREP1M,ISPIN)
       NUMI=POP(IRREP3M,ISPIN) 
       DO 320 INDXA=1,NUMA
        DO 330 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP2M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1M)
         DO 340 INDXJ=1,NUMJ
          DO 350 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(IND(IPTR(2)),INDA,MAXL1)
           GINDXR=INDXF(IND(IPTR(1)),INDK,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
350       CONTINUE
340      CONTINUE
330     CONTINUE
320    CONTINUE
C
C          12 34        42 31
C        G(AJ,KI) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP4M,IRREP2M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP2M)
       NUMA=VRT(IRREP1M,ISPIN)
       NUMK=POP(IRREP3M,ISPIN)
       NUMJ=POP(IRREP2M,ISPIN)
       NUMI=POP(IRREP4M,ISPIN) 
       DO 420 INDXA=1,NUMA
        DO 430 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP1M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2M)
         DO 440 INDXJ=1,NUMJ
          DO 450 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(INDA,IND(IPTR(2)),MAXL1)
           GINDXR=INDXF(INDK,IND(IPTR(1)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
450       CONTINUE
440      CONTINUE
430     CONTINUE
420    CONTINUE
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       IRREPGET=DIRPRD(IRREP2M,IRREP3M)
C
       IOFFR=1
       IOFFL=1
       DO 3000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFR=IOFFR+POP(IRREPB,ISPIN)*VRT(IRREPA,ISPIN)
        IF(IRREPB.GT.IRREPA)GOTO 3000
        IOFFSL(IRREPA)=IOFFL
        IOFFL=IOFFL+POP(IRREPB,ISPIN)*POP(IRREPA,ISPIN)
3000   CONTINUE
C
C          12 34        23 14
C        G(KI,JA) <-- g<IJ,KA>
C
C
       CALL GETFAC2(IRREP2M,IRREP3M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMA=VRT(IRREP4M,ISPIN)
       NUMK=POP(IRREP1M,ISPIN)
       NUMJ=POP(IRREP3M,ISPIN)
       NUMI=POP(IRREP2M,ISPIN) 
       DO 520 INDXA=1,NUMA
        DO 530 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP4M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 540 INDXJ=1,NUMJ
          DO 550 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(INDK,IND(IPTR(1)),MAXL1)
           GINDXR=INDXF(IND(IPTR(2)),INDA,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
550       CONTINUE
540      CONTINUE
530     CONTINUE
520    CONTINUE
C
C          12 34        14 23
C        G(IK,AJ) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP1M,IRREP4M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP3M)
       IFIRST=IOFFSL(IRREP4M)
       NUMA=VRT(IRREP3M,ISPIN)
       NUMK=POP(IRREP2M,ISPIN)
       NUMJ=POP(IRREP4M,ISPIN)
       NUMI=POP(IRREP1M,ISPIN) 
       DO 620 INDXA=1,NUMA
        DO 630 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP3M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 640 INDXJ=1,NUMJ
          DO 650 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(IND(IPTR(1)),INDK,MAXL1)
           GINDXR=INDXF(INDA,IND(IPTR(2)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
650       CONTINUE
640      CONTINUE
630     CONTINUE
620    CONTINUE
C
C          12 34        32 41
C        G(AJ,IK) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP3M,IRREP2M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP2M)
       NUMA=VRT(IRREP1M,ISPIN)
       NUMK=POP(IRREP4M,ISPIN)
       NUMJ=POP(IRREP2M,ISPIN)
       NUMI=POP(IRREP3M,ISPIN) 
       DO 720 INDXA=1,NUMA
        DO 730 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP1M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2M)
         DO 740 INDXJ=1,NUMJ
          DO 750 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(INDA,IND(IPTR(2)),MAXL1)
           GINDXR=INDXF(IND(IPTR(1)),INDK,MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
750       CONTINUE
740      CONTINUE
730     CONTINUE
720    CONTINUE
C
C          12 34        41 32
C        G(JA,KI) <-- g<IJ,KA>
C
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       CALL GETFAC2(IRREP4M,IRREP1M,IPTR,FACTOR)
       FACT=FIJKA*FACTOR
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP1M)
       NUMA=VRT(IRREP2M,ISPIN)
       NUMK=POP(IRREP3M,ISPIN)
       NUMJ=POP(IRREP1M,ISPIN)
       NUMI=POP(IRREP4M,ISPIN) 
       DO 820 INDXA=1,NUMA
        DO 830 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP2M,ISPIN)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1M)
         DO 840 INDXJ=1,NUMJ
          DO 850 INDXI=1,NUMI
           X=BUF(IPOS)*FACT
           IPOS=IPOS+1
           IND(2)=INDXJ
           IND(1)=INDXI
           GINDXL=INDXF(IND(IPTR(2)),INDA,MAXL1)
           GINDXR=INDXF(INDK,IND(IPTR(1)),MAXL2)
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
850       CONTINUE
840      CONTINUE
830     CONTINUE
820    CONTINUE
C

100   CONTINUE
      RETURN
      END
