      SUBROUTINE G4AB2(GAMMA,BUF,GOFF,DOIRR,LENGAM,FIJKA)
C
C THIS ROUTINE PROCESSES THE g<Ij,Ka> GAMMA LISTS AND FILLS
C  OUT THE ABCD SYMMETRY CASE MULLIKEN ORDERED GAMMA.
C
C FOR THIS, THE FOLLOWING SYMMETRIZATION IS REQUIRED:
C
C         12 34      12 34      21 34
C       G(IK,ja) = g(IK,ja) + g(KI,ja)
C
C         13 24      13 24      23 14
C       G<Ij,Ka> = g<Ij,Ka> + g<Kj,Ia>
C
C IN ADDITION, IT IS NECESSARY TO PUT IN BOTH OOOV, OVOO, OOVO AND
C  VOOO PARTS, RESULTING IN A TOTAL OF EIGHT CONTRIBUTIONS.
C
C NOTE THAT ABCD IN MULLIKEN CORRESPONDS TO ACBD IN DIRAC.  NOTE ALSO THAT
C  ALL ELEMENTS OF GAMMA WHICH ARE PROCESSED HERE COME FROM DPD LISTS
C  FOR IRREPS 2-h, SINCE A.NE.C;B.NE.D.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GAMMA(LENGAM),BUF(1),X,X1,X2 
      DOUBLE PRECISION FABIJ,FAIBJ,FABCD,FIJKL,FABCI,FIJKA
      INTEGER GOFF(8,8,8,8),IDID(8),IOFFSL(8)
      INTEGER IOFFSR(8),DOIRR(42,4)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MOPOPS/ MOPOP(8)
C
      INDXF(I,J,N)=I+(J-1)*N
      INDXT(I,J)  =I+(J*(J-1))/2
      NNP1O2(I)   =(I*(I+1))/2
C
C CALCULATE HOW MANY UNIQUE ABCD SYMMETRY SETS THERE ARE
C
      IF(NIRREP.EQ.8)THEN
       NUMABCD=42
      ELSEIF(NIRREP.EQ.4)THEN
       NUMABCD=3
      ENDIF
C     
      LISTIJKA=110
      DO 100 ICOUNT=1,NUMABCD
       IRREP1D=DOIRR(ICOUNT,1)
       IRREP2D=DOIRR(ICOUNT,3)
       IRREP3D=DOIRR(ICOUNT,2)
       IRREP4D=DOIRR(ICOUNT,4)
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       IOFFSET=GOFF(IRREP1M,IRREP2M,IRREP3M,IRREP4M)
C
       IRREPGET=DIRPRD(IRREP3D,IRREP4D)
C
       IOFFR=1
       IOFFL=1
       DO 2000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+POP(IRREPB,1)*VRT(IRREPA,2)
        IOFFL=IOFFL+POP(IRREPB,1)*POP(IRREPA,2)
2000   CONTINUE
C
C CANONICAL OOOV PART
C
       ILOGREC=IOFFSR(IRREP4D)
       IFIRST=IOFFSL(IRREP2D)
       NUMA=VRT(IRREP4D,2)
       NUMK=POP(IRREP3D,1)
       NUMJ=POP(IRREP2D,2)
       NUMI=POP(IRREP1D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 120 INDXA=1,NUMA
        DO 130 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP4D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2D)
         DO 140 INDXJ=1,NUMJ
          DO 150 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDI,INDK,MOPOP(IRREP1M))
           GINDXR=INDXF(INDJ,INDA,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
150       CONTINUE
140      CONTINUE
130     CONTINUE
120    CONTINUE
C
C CANONICAL OVOO PART
C
       ILOGREC=IOFFSR(IRREP3D)
       IFIRST=IOFFSL(IRREP1D)
       NUMA=VRT(IRREP3D,2)
       NUMK=POP(IRREP4D,1)
       NUMJ=POP(IRREP1D,2)
       NUMI=POP(IRREP2D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 320 INDXA=1,NUMA
        DO 330 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP3D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1D)
         DO 340 INDXJ=1,NUMJ
          DO 350 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDJ,INDA,MOPOP(IRREP1M))
           GINDXR=INDXF(INDI,INDK,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
350       CONTINUE
340      CONTINUE
330     CONTINUE
320    CONTINUE
C
       IRREPGET=DIRPRD(IRREP3D,IRREP2D)
C
       IOFFR=1
       IOFFL=1
       DO 2500 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+POP(IRREPB,1)*VRT(IRREPA,2)
        IOFFL=IOFFL+POP(IRREPB,1)*POP(IRREPA,2)
2500   CONTINUE
C
C CANONICAL OOVO PART
C
       ILOGREC=IOFFSR(IRREP2D)
       IFIRST=IOFFSL(IRREP4D)
       NUMA=VRT(IRREP2D,2)
       NUMK=POP(IRREP3D,1)
       NUMJ=POP(IRREP4D,2)
       NUMI=POP(IRREP1D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 220 INDXA=1,NUMA
        DO 230 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP2D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4D)
         DO 240 INDXJ=1,NUMJ
          DO 250 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDI,INDK,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
250       CONTINUE
240      CONTINUE
230     CONTINUE
220    CONTINUE
C
C CANONICAL VOOO PART
C
       ILOGREC=IOFFSR(IRREP1D)
       IFIRST=IOFFSL(IRREP3D)
       NUMA=VRT(IRREP1D,2)
       NUMK=POP(IRREP4D,1)
       NUMJ=POP(IRREP3D,2)
       NUMI=POP(IRREP2D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 420 INDXA=1,NUMA
        DO 430 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP1D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3D)
         DO 440 INDXJ=1,NUMJ
          DO 450 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDA,INDJ,MOPOP(IRREP1M))
           GINDXR=INDXF(INDI,INDK,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
450       CONTINUE
440      CONTINUE
430     CONTINUE
420    CONTINUE
C
C NOW WE HAVE TO GET THE SYMMETRIZATION PIECE 
C
       IRREPGET=DIRPRD(IRREP1D,IRREP4D)
C
       IOFFR=1
       IOFFL=1
       DO 3000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+POP(IRREPB,1)*VRT(IRREPA,2)
        IOFFL=IOFFL+POP(IRREPB,1)*POP(IRREPA,2)
3000   CONTINUE
C
C OOOV FIRST
C
       ILOGREC=IOFFSR(IRREP4D)
       IFIRST=IOFFSL(IRREP2D)
       NUMA=VRT(IRREP4D,2)
       NUMK=POP(IRREP1D,1)
       NUMJ=POP(IRREP2D,2)
       NUMI=POP(IRREP3D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1120 INDXA=1,NUMA
        DO 1130 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP4D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2D)
         DO 1140 INDXJ=1,NUMJ
          DO 1150 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDK,INDI,MOPOP(IRREP1M))
           GINDXR=INDXF(INDJ,INDA,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1150      CONTINUE
1140     CONTINUE
1130    CONTINUE
1120   CONTINUE
C
C OVOO PART
C
       ILOGREC=IOFFSR(IRREP3D)
       IFIRST=IOFFSL(IRREP1D)
       NUMA=VRT(IRREP3D,2)
       NUMK=POP(IRREP2D,1)
       NUMJ=POP(IRREP1D,2)
       NUMI=POP(IRREP4D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1320 INDXA=1,NUMA
        DO 1330 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP3D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1D)
         DO 1340 INDXJ=1,NUMJ
          DO 1350 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDJ,INDA,MOPOP(IRREP1M))
           GINDXR=INDXF(INDK,INDI,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1350      CONTINUE
1340     CONTINUE
1330    CONTINUE
1320   CONTINUE
C
       IRREPGET=DIRPRD(IRREP1D,IRREP2D)
C
       IOFFR=1
       IOFFL=1
       DO 3500 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+POP(IRREPB,1)*VRT(IRREPA,2)
        IOFFL=IOFFL+POP(IRREPB,1)*POP(IRREPA,2)
3500   CONTINUE
C
C OOVO PART
C
       ILOGREC=IOFFSR(IRREP2D)
       IFIRST=IOFFSL(IRREP4D)
       NUMA=VRT(IRREP2D,2)
       NUMK=POP(IRREP1D,1)
       NUMJ=POP(IRREP4D,2)
       NUMI=POP(IRREP3D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1220 INDXA=1,NUMA
        DO 1230 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP2D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4D)
         DO 1240 INDXJ=1,NUMJ
          DO 1250 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDK,INDI,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1250      CONTINUE
1240     CONTINUE
1230    CONTINUE
1220   CONTINUE
C
C VOOO PART
C
       ILOGREC=IOFFSR(IRREP1D)
       IFIRST=IOFFSL(IRREP3D)
       NUMA=VRT(IRREP1D,2)
       NUMK=POP(IRREP2D,1)
       NUMJ=POP(IRREP3D,2)
       NUMI=POP(IRREP4D,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1420 INDXA=1,NUMA
        DO 1430 INDXK=1,NUMK
         INDA=INDXA+POP(IRREP1D,2)
         INDK=INDXK
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTIJKA)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3D)
         DO 1440 INDXJ=1,NUMJ
          DO 1450 INDXI=1,NUMI
           X=BUF(IPOS)*FIJKA
           IPOS=IPOS+1
           INDI=INDXI
           INDJ=INDXJ
           GINDXL=INDXF(INDA,INDJ,MOPOP(IRREP1M))
           GINDXR=INDXF(INDK,INDI,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1450      CONTINUE
1440     CONTINUE
1430    CONTINUE
1420   CONTINUE
C
C ALL DONE!
C
100   CONTINUE
      RETURN
      END
