      SUBROUTINE GAM1AB(GAMMA,BUF,BUF1,BUF2,SCR1,SCR2,
     &                  LENGAM,IRREPDO,LIST1,LIST2,IUHF,ALASKA)
C
C THIS ROUTINE FORMS THE AAAA SYMMETRY TYPE AO GAMMA LISTS
C  FOR SPIN CASE AB AND WRITES THEM TO THE BACKTRANSFORMATION
C  MOINTS FILE FOR A PARTICULAR IRREP. THIS IS THE INCORE VERSION!
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GAMMA(LENGAM),BUF(*),X,ONE,TWO
      DOUBLE PRECISION BUF1(*),BUF2(*),SCR1(*),SCR2(*)
      DOUBLE PRECISION FABIJ,FAIBJ,FABCD,FIJKL,FABCI,FIJKA
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      LOGICAL MBPT4
      LOGICAL ROHF,MOEQAO,ALASKA
      LOGICAL GABCD,DABCD
      LOGICAL TDA,EOM
C
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MOPOPS/ MOPOP(8)
      COMMON /FACTORS/ FABIJ,FABCD,FIJKL,FAIBJ,FABCI,FIJKA
      COMMON /REF/ ROHF
      COMMON /SIZES/ MOEQAO
      COMMON /IABCD/ IOFFABCD
      COMMON /ABCD/ GABCD,DABCD
      COMMON /EXCITE/ TDA,EOM
      COMMON /STATSYM/IRREPX
C
      DATA ONE,TWO /1.D0,2.D0/
C
      INDXF(I,J,N)=I+(J-1)*N
      INDXT(I,J)  =I+(J*(J-1))/2
      NNP1O2(I)   =(I*(I+1))/2
C
      CALL ZERO(GAMMA,LENGAM)

      call gam1ab1(GAMMA,BUF,BUF1,BUF2,SCR1,SCR2,
     &                  LENGAM,IRREPDO,LIST1,LIST2,IUHF)

      IF(MBPT2)GOTO 2000
      
      IF(TDA)GOTO 2000

      IF((MBPT3.AND.(.NOT.ROHF)).OR.CCD)GOTO 2000

      call gam1ab2(GAMMA,BUF,BUF1,BUF2,SCR1,SCR2,
     &                  LENGAM,IRREPDO,LIST1,LIST2,IUHF)

C
C WRITE DUMP THIS IRREP OF GAMMAS TO DISK
C
2000  CONTINUE
      NUMDIS=NNP1O2(MOPOP(IRREPDO))
      DISSIZ=NUMDIS
      IF(MOEQAO .OR. ALASKA)THEN
       CALL PUTLST(GAMMA,1,NUMDIS,1,LIST1,LIST2)
      ELSE
C
C CODE BELOW REQUIRED FOR CASES WHERE NMO<NAO, SINCE NAO GAMMAS
C EVENTUALLY OVERWRITE LIST (1,1), WHICH HAS THE PHYSICAL DIMENSIONS
C OF THE CORRESPONDING AO GAMMA
C
       IOFF=1
       DO 2001 IDIS=1,NUMDIS
        CALL PUTLST(GAMMA(IOFF),IDIS,1,1,LIST1,LIST2)
        IOFF=IOFF+DISSIZ
2001   CONTINUE
      ENDIF
C     
      RETURN
      END
