      SUBROUTINE TESTG6(CORE,MAXCOR)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DIRPRD,POP,VRT,DISAB,DISAA
      DIMENSION CORE(MAXCOR/2)
C
C   THIS ROUTINE CHECKS THE CONSISTENCY OF THE GAMMA5 INTERMEDIATES
Ca
      COMMON/MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
C
C
      LISTAB=110
      LISTAA=107
      DO 100 IRREP=1,NIRREP
       NUMAB=IRPDPD(IRREP,ISYTYP(2,LISTAB))
       DISAB=IRPDPD(IRREP,ISYTYP(1,LISTAB))
       DISAA=IRPDPD(IRREP,ISYTYP(1,LISTAA))
       I001=1
       I002=I001+NUMAB*DISAB*IINTFP
       I003=I002+NUMAB*DISAB*IINTFP 
       I004=I003+NUMAB*DISAB*IINTFP
       CALL GETLST(CORE(I001),1,NUMAB,1,IRREP,LISTAB)
       CALL SYMTRA2(IRREP,POP(1,1),POP(1,1),DISAB,NUMAB,CORE(I001),
     &              CORE(I002))
       CALL VADD(CORE(I003),CORE(I001),CORE(I002),NUMAB*DISAB,-1.D0)
       CALL GETLST(CORE(I001),1,NUMAB,1,IRREP,LISTAA)
       CALL SYMEXP2(IRREP,POP,DISAB,DISAA,NUMAB,CORE(I001),CORE(I001))
       CALL VADD(CORE(I002),CORE(I003),CORE(I001),NUMAB*DISAB,-1.d0)
       SUM=SDOT(NUMAB*DISAB,CORE(I002),1,CORE(I002),1)
       write(*,*) 'check for irrep ',IRREP,SUM
100   CONTINUE
      RETURN
      END     
