      SUBROUTINE GETSPH(INU)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
C....    DETERMINE WHETHER THIS RUN IS FROM CARTESIANS OR
C....    SPHERICAL HARMONICS.  GET THIS FROM JOBARC INFORMATION!
C
      COMMON /PRTDAT/ IDOSPH, MAXAQN, NSABF
      COMMON /FLAGS/ IFLAGS(100)
      IDOSPH=1
      IF(IFLAGS(62).EQ.1)IDOSPH=0
      RETURN
      END
