      SUBROUTINE GINL12(LIA,GVV,ICORE,MAXCOR,IUHF)
C
C THIS SUBROUTINE CALCULATES THE L(AI) CONTRIBUTION 
C DUE TO THE VIRTUAL-VIRTUAL BLOCK OF THE G INTERMEDIATE 
C
C      L(IA)=  - SUM F,G <GI//FA> G(GF)
C
C WHICH IS NEEDED FOR CCSD GRADIENT CALCULATIONS
C
C THIS ROUTINE USES EXPLICITELY SYMMETRY
C
CEND
C
C CODED SEPTEMBER/90
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION LIA
      INTEGER DIRPRD,DISSYW,POP,VRT
      DIMENSION LIA(1),GVV(1),ICORE(MAXCOR)
      COMMON /SYM/ POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
      MXCOR=MAXCOR 
C
C NEW CODE
C
       CALL VMINUS (LIA,NTAA+IUHF*NTBB)
       CALL DVVINVO(1,LIA,GVV,ICORE,MXCOR,IUHF,27)
       CALL VMINUS (LIA,NTAA+IUHF*NTBB)
C
C OLD CODE
C
c      DO 1000 ISPIN=1,IUHF+1
C
c       IF(ISPIN.EQ.1) THEN
c        IOFFX=1
c        IOFFDA=1
c        IOFFDB=1+NF2AA*IUHF
c       ELSE
c        IOFFX=1+NTAA
c        IOFFDA=1+NF2AA
c        IOFFDB=1
c       ENDIF
C
C  FIRST DO AAAA PART
C
c       IF(IUHF.EQ.1) THEN
C
c        LISTW=26+ISPIN
C
c        DO 100 IRREP=1,NIRREP
C
c         NVRTSQ=0
c         DO 101 IRREPJ=1,NIRREP
c          NVRTSQ=NVRTSQ+VRT(IRREPJ,ISPIN)
c     &            *VRT(DIRPRD(IRREP,IRREPJ),ISPIN)
c101      CONTINUE
C
c         NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
c         DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
C
c         I001=1
c         I002=I001+IINTFP*NVRTSQ*NUMSYW
c         IF(I002.LT.MXCOR) THEN
C
c          CALL LIA2AA(ICORE(I001),GVV(IOFFDA),LIA(IOFFX),ISPIN,
c     &                POP(1,ISPIN),VRT(1,ISPIN),DISSYW,NUMSYW,
c     &                NVRTSQ,LISTW,IRREP)
c         ELSE   
c          CALL INSMEM('LIA2AA',I002,MXCOR)
c         ENDIF
c100     CONTINUE
C
c       ENDIF
cC 
c       LISTW=28+ISPIN
c       IF(IUHF.EQ.0) LISTW=30
C
c       DO 200 IRREP=1,NIRREP
C
c        NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
c        DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
C
c        I001=1
c        I002=I001+IINTFP*NUMSYW*DISSYW
c        IF(IUHF.EQ.0) THEN
c         ITMP=I002
c         I002=ITMP+2*IINTFP*NUMSYW
c        ENDIF
c        IF(I002.LT.MXCOR) THEN
cC
c         CALL LIA2AB(ICORE(I001),GVV(IOFFDB),LIA(IOFFX),ISPIN,
c     &               POP(1,ISPIN),VRT(1,ISPIN),POP(1,3-ISPIN),
c     &               VRT(1,3-ISPIN),DISSYW,NUMSYW,LISTW,IRREP,IUHF,
c     &               ICORE(ITMP))
c        ELSE
c         CALL INSMEM('LIA2AB',I002,MXCOR)
c        ENDIF
c200    CONTINUE
c1000  CONTINUE
      RETURN
      END
