      SUBROUTINE INITSN(ICORE,MAXCOR,IUHF)
C
C   INITIATES THE LIST FOR THE T1 AMPLITUDES AND INCREMENTS
C   AND ZEROS THEM
C
C   IN CASE OF TRIPLE EXCITATIONS (QCISD(T) AND CCSD(T) ONLY)
C   INITIALIZE LISTS WITH THE CONTRIBUTIONS DUE TO TRIPLES
C
CEND
C
C CODED JULY/90 JG JUNE/91 JG
C
      IMPLICIT INTEGER(A-Z)
      LOGICAL TRIPNI1,TRIPNI2,TRIPIT,T3STOR
      DIMENSION ICORE(MAXCOR)
C
      COMMON/TRIPLES/TRIPNI1,TRIPNI2,TRIPIT,T3STOR
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPR(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
C
C  ZERO THE T1 INCREMENTS
C
      IF(TRIPNI2) THEN
C
C The original list (104) is being used eleswhere. They
C were changed to 1-4 from 101-104. Ajith Perera, 04/08

       CALL GETLST(ICORE,1,1,1,1,4)
       CALL PUTLST(ICORE,1,1,1,3,90)
       IF(IUHF.NE.0) THEN
        CALL GETLST(ICORE,1,1,1,2,4)
        CALL PUTLST(ICORE,1,1,1,4,90)
       ENDIF
C
      ELSE
C
       CALL ZERLST(ICORE,NT(1),1,1,3,90)
       IF(IUHF.NE.0) CALL ZERLST(ICORE,NT(2),1,1,4,90)
      ENDIF
C
C  ALL DONE
C
       RETURN
       END
