      SUBROUTINE G4AB4A(GAMMA,BUF,GOFF,DOIRR,LENGAM,FAIBJ)
C
C THIS ROUTINE PROCESSES THE RING GAMMA LISTS AND FILLS
C  OUT THE ABCD SYMMETRY CASE MULLIKEN ORDERED GAMMA FOR 
C  SPIN CASE AABB.  THIS IS FOR UHF CALCULATIONS ONLY!
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GAMMA(LENGAM),BUF(1),X,X1,X2 
      DOUBLE PRECISION FABIJ,FIJKL,FABCD,FAIBJ,FABCI,FIJKA
      INTEGER GOFF(8,8,8,8),IDID(8),IOFFSL(8)
      INTEGER IOFFSR(8),DOIRR(42,4)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MOPOPS/ MOPOP(8)
C
      INDXF(I,J,N)=I+(J-1)*N
      INDXT(I,J)  =I+(J*(J-1))/2
      NNP1O2(I)   =(I*(I+1))/2
C
C CALCULATE HOW MANY UNIQUE ABCD SYMMETRY SETS THERE ARE
C
      IF(NIRREP.EQ.8)THEN
       NUMABCD=42
      ELSEIF(NIRREP.EQ.4)THEN
       NUMABCD=3
      ENDIF
C
      DO 100 ICOUNT=1,NUMABCD
       IRREP1M=DOIRR(ICOUNT,1)
       IRREP2M=DOIRR(ICOUNT,2)
       IRREP3M=DOIRR(ICOUNT,3)
       IRREP4M=DOIRR(ICOUNT,4)
       IOFFSET=GOFF(IRREP1M,IRREP2M,IRREP3M,IRREP4M)
C     
C  FIRST DO LIST 125
C
C          12 34        13 24
C        G(AB,ij) <-- g<Ai,Bj>
C
C          12 34        24 13
C        G(BA,ij) <-- g<Ai,Bj>
C
       LISTAIBJ=125
C
C          12 34        13 24
C        G(AB,ij) <-- g<Ai,Bj>
C
C
       IRREPGET=DIRPRD(IRREP2M,IRREP4M)
       IOFFR=1
       IOFFL=1
       DO 2000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,1)*POP(IRREPA,2)
        IOFFL=IOFFL+VRT(IRREPB,1)*POP(IRREPA,2)
2000   CONTINUE
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMJ=POP(IRREP4M,2)
       NUMB=VRT(IRREP2M,1)
       NUMI=POP(IRREP3M,2)
       NUMA=VRT(IRREP1M,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 120 INDXJ=1,NUMJ
        DO 130 INDXB=1,NUMB
         INDJ=INDXJ
         INDB=INDXB+POP(IRREP2M,1)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 140 INDXI=1,NUMI
          DO 150 INDXA=1,NUMA
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDI=INDXI
           INDA=INDXA+POP(IRREP1M,1)
           GINDXL=INDXF(INDA,INDB,MOPOP(IRREP1M))
           GINDXR=INDXF(INDI,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
150       CONTINUE
140      CONTINUE
130     CONTINUE
120    CONTINUE
C
C          12 34        23 14
C        G(BA,ij) <-- g<Ai,Bj>
C
       IRREPGET=DIRPRD(IRREP1M,IRREP4M)
       IOFFR=1
       IOFFL=1
       DO 1500 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,1)*POP(IRREPA,2)
        IOFFL=IOFFL+VRT(IRREPB,1)*POP(IRREPA,2)
1500   CONTINUE
       ILOGREC=IOFFSR(IRREP4M)
       IFIRST=IOFFSL(IRREP3M)
       NUMJ=POP(IRREP4M,2)
       NUMB=VRT(IRREP1M,1) 
       NUMI=POP(IRREP3M,2)
       NUMA=VRT(IRREP2M,1)
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 420 INDXJ=1,NUMJ
        DO 430 INDXB=1,NUMB
         INDB=INDXB+POP(IRREP1M,1)
         INDJ=INDXJ
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 440 INDXI=1,NUMI
          DO 450 INDXA=1,NUMA
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDI=INDXI
           INDA=INDXA+POP(IRREP2M,1)
           GINDXL=INDXF(INDB,INDA,MOPOP(IRREP1M))
           GINDXR=INDXF(INDI,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
450       CONTINUE
440      CONTINUE
430     CONTINUE
420    CONTINUE
C     
C  NOW DO LIST 126
C
C          12 34        31 42
C        G(IJ,ab) <-- g<aI,bJ>
C
C          12 34        32 41
C        G(JI,ab) <-- g<Ai,Bj>
C
       LISTAIBJ=126
C
C          12 34        31 42
C        G(IJ,ab) <-- g<aI,bJ>
C
       IRREPGET=DIRPRD(IRREP2M,IRREP4M)
       IOFFR=1
       IOFFL=1
       DO 3000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,2)*POP(IRREPA,1)
        IOFFL=IOFFL+VRT(IRREPB,2)*POP(IRREPA,1)
3000   CONTINUE
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP1M)
       NUMJ=POP(IRREP2M,1)
       NUMB=VRT(IRREP4M,2)
       NUMI=POP(IRREP1M,1)
       NUMA=VRT(IRREP3M,2) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1120 INDXJ=1,NUMJ
        DO 1130 INDXB=1,NUMB
         INDJ=INDXJ
         INDB=INDXB+POP(IRREP4M,2)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP1M)
         DO 1140 INDXI=1,NUMI
          DO 1150 INDXA=1,NUMA
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDI=INDXI
           INDA=INDXA+POP(IRREP3M,2)
           GINDXL=INDXF(INDI,INDJ,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDB,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1150       CONTINUE
1140      CONTINUE
1130     CONTINUE
1120    CONTINUE
C
C          12 34        32 41
C        G(JI,ab) <-- g<aI,bJ>
C
       IRREPGET=DIRPRD(IRREP1M,IRREP4M)
       IOFFR=1
       IOFFL=1
       DO 4000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,2)*POP(IRREPA,1)
        IOFFL=IOFFL+VRT(IRREPB,2)*POP(IRREPA,1)
4000   CONTINUE
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP2M)
       NUMJ=POP(IRREP1M,1)
       NUMB=VRT(IRREP4M,2) 
       NUMI=POP(IRREP2M,1)
       NUMA=VRT(IRREP3M,2)
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 1420 INDXJ=1,NUMJ
        DO 1430 INDXB=1,NUMB
         INDB=INDXB+POP(IRREP4M,2)
         INDJ=INDXJ
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP2M)
         DO 1440 INDXI=1,NUMI
          DO 1450 INDXA=1,NUMA
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDI=INDXI
           INDA=INDXA+POP(IRREP3M,2)
           GINDXL=INDXF(INDJ,INDI,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDB,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
1450       CONTINUE
1440      CONTINUE
1430     CONTINUE
1420    CONTINUE
C     
C  NOW DO LIST 118
C
C          12 34        14 32
C        G(BI,aj) <-- g<Bj,aI>
C
C          12 34        23 41
C        G(IB,ja) <-- g<Bj,aI>
C
C          12 34        24 31
C        G(IB,aj) <-- g<Bj,aI>
C
C          12 34        13 42
C        G(BI,ja) <-- g<Bj,aI>
C
       LISTAIBJ=118
C
C          12 34        14 32
C        G(BI,aj) <-- g<Bj,aI>
C
       IRREPGET=DIRPRD(IRREP2M,IRREP3M)
       IOFFR=1
       IOFFL=1
       DO 5000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,2)*POP(IRREPA,1)
        IOFFL=IOFFL+VRT(IRREPB,1)*POP(IRREPA,2)
5000   CONTINUE
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP4M)
       NUMI=POP(IRREP2M,1)
       NUMA=VRT(IRREP3M,2)
       NUMJ=POP(IRREP4M,2)
       NUMB=VRT(IRREP1M,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 2120 INDXI=1,NUMI
        DO 2130 INDXA=1,NUMA
         INDI=INDXI
         INDA=INDXA+POP(IRREP3M,2)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 2140 INDXJ=1,NUMJ
          DO 2150 INDXB=1,NUMB
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDJ=INDXJ
           INDB=INDXB+POP(IRREP1M,1)
           GINDXL=INDXF(INDB,INDI,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
2150       CONTINUE
2140      CONTINUE
2130     CONTINUE
2120    CONTINUE
C
C          12 34        23 41
C        G(IB,ja) <-- g<Bj,aI>
C
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP3M)
       NUMI=POP(IRREP1M,1)
       NUMA=VRT(IRREP4M,2)
       NUMJ=POP(IRREP3M,2)
       NUMB=VRT(IRREP2M,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 3120 INDXI=1,NUMI
        DO 3130 INDXA=1,NUMA
         INDI=INDXI
         INDA=INDXA+POP(IRREP4M,2)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 3140 INDXJ=1,NUMJ
          DO 3150 INDXB=1,NUMB
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDJ=INDXJ
           INDB=INDXB+POP(IRREP2M,1)
           GINDXL=INDXF(INDI,INDB,MOPOP(IRREP1M))
           GINDXR=INDXF(INDJ,INDA,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
3150       CONTINUE
3140      CONTINUE
3130     CONTINUE
3120    CONTINUE
C
C          12 34        24 31
C        G(IB,aj) <-- g<Bj,aI>
C
       IRREPGET=DIRPRD(IRREP1M,IRREP3M)
       IOFFR=1
       IOFFL=1
       DO 6000 IRREPA=1,NIRREP
        IRREPB=DIRPRD(IRREPA,IRREPGET)
        IOFFSR(IRREPA)=IOFFR
        IOFFSL(IRREPA)=IOFFL
        IOFFR=IOFFR+VRT(IRREPB,2)*POP(IRREPA,1)
        IOFFL=IOFFL+VRT(IRREPB,1)*POP(IRREPA,2)
6000   CONTINUE
C
       ILOGREC=IOFFSR(IRREP1M)
       IFIRST=IOFFSL(IRREP4M)
       NUMI=POP(IRREP1M,1)
       NUMA=VRT(IRREP3M,2)
       NUMJ=POP(IRREP4M,2)
       NUMB=VRT(IRREP2M,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 4120 INDXI=1,NUMI
        DO 4130 INDXA=1,NUMA
         INDI=INDXI
         INDA=INDXA+POP(IRREP3M,2)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP4M)
         DO 4140 INDXJ=1,NUMJ
          DO 4150 INDXB=1,NUMB
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDJ=INDXJ
           INDB=INDXB+POP(IRREP2M,1)
           GINDXL=INDXF(INDI,INDB,MOPOP(IRREP1M))
           GINDXR=INDXF(INDA,INDJ,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
4150       CONTINUE
4140      CONTINUE
4130     CONTINUE
4120    CONTINUE
C
C          12 34        13 42
C        G(BI,ja) <-- g<Bj,aI>
C
       ILOGREC=IOFFSR(IRREP2M)
       IFIRST=IOFFSL(IRREP3M)
       NUMI=POP(IRREP2M,1)
       NUMA=VRT(IRREP4M,2)
       NUMJ=POP(IRREP3M,2)
       NUMB=VRT(IRREP1M,1) 
       MAXL=MOPOP(IRREP1M)*MOPOP(IRREP2M)
       DO 5120 INDXI=1,NUMI
        DO 5130 INDXA=1,NUMA
         INDI=INDXI
         INDA=INDXA+POP(IRREP4M,2)
         CALL GETLST(BUF,ILOGREC,1,1,IRREPGET,LISTAIBJ)
         ILOGREC=ILOGREC+1
         IPOS=IOFFSL(IRREP3M)
         DO 5140 INDXJ=1,NUMJ
          DO 5150 INDXB=1,NUMB
           X=BUF(IPOS)*FAIBJ
           IPOS=IPOS+1
           INDJ=INDXJ
           INDB=INDXB+POP(IRREP1M,1)
           GINDXL=INDXF(INDB,INDI,MOPOP(IRREP1M))
           GINDXR=INDXF(INDJ,INDA,MOPOP(IRREP3M))
           GINDX0=INDXF(GINDXL,GINDXR,MAXL)
           GINDX =GINDX0+IOFFSET
           GAMMA(GINDX)=GAMMA(GINDX)+X
5150       CONTINUE
5140      CONTINUE
5130     CONTINUE
5120    CONTINUE
C
100   CONTINUE
      RETURN
      END
