      SUBROUTINE ORDLST(IUATMS,NATOMS,IORDLST,IMEMB,NPOP,NUCTR)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      DIMENSION IORDLST(IUATMS),IMEMB(NATOMS),NPOP(IUATMS),
     &          NUCTR(NATOMS)
C
      ICNT=1
      DO 10 I=1,IUATMS
         KPTRK=IMEMB(ICNT)
         IORDLST(I)=NUCTR(KPTRK)
         DO 20 J=1,NPOP(I)
            ICNT=ICNT+1
   20    CONTINUE
   10 CONTINUE
C
      RETURN
      END
