      SUBROUTINE TTWT(ICORE,MAXCOR,IUHF)
C   
C     CALCULATE THE TdagerWT CONTRIBUTIONS TO T2
C     NOTE THAT SOME DIAGRAMS ARE CALCULATED IN ROUTINES
C     DWMBEJ, QUAD1,QUAD2,QUAD3 BY ROUTINE DT AND THESE
C     WERE ADDED TO DIFERENT INTERMEDIATES
C
C CODED PS JUL/91
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /FLAGS/ IFLAGS(100)
      IF(IFLAGS(1).GE.10)THEN
       WRITE(LUOUT,100)
100    FORMAT(T3,'@TTWT-I, Calculating UCC terms')
       CALL TIMER(1)
      ENDIF
C
C     FACT IS THE MULTIPLIER OF THE TdagerWT TERM (0.5 FOR UCC)
C
      FACT=0.5D0
c& init lists
C
C     FORM G(AE) INTERMIDIATE
C
      CALL FORMG1(ICORE,MAXCOR,IUHF,FACT)
C
C     FIRST CONTRIBUTION
C
      CALL G1INL2(ICORE,MAXCOR,IUHF)
C
C     FORM G(IM)
C
      CALL FORMG2(ICORE,MAXCOR,IUHF,FACT)
C
C     SECOND CONTRIBUTION
C
      CALL G2INL2(ICORE,MAXCOR,IUHF)
C
C     THIRD CONTRIBUTION. CALCULATED DIRECTLY
C
      CALL NWTRM(ICORE,MAXCOR,IUHF,FACT)
C
C     ALL DONE
C
      IF(IFLAGS(1).GE.10)THEN
       CALL TIMER(1)
c       WRITE(LUOUT,102)TIMENEW
102    FORMAT(T3,'@TTWT-I, UCC terms required ',F9.3,
     &           ' seconds.')
      ENDIF
      RETURN
      END
