      SUBROUTINE SPH2CRT(EVEC,ICORE,MAXCOR,IUHF,ISPIN)
C
C THIS ROUTINE TRANSFORMS A SET OF EIGENVECTORS FROM THE
C SPHERICAL HARMONIC TO CARTESIAN REPRESENTATION.  THIS
C IS USED IN THE BACK TRANSFORMATION OF THE MO GAMMAS
C SINCE THEY ARE PROCESSED AND CONTRACTED WITH DERIVATIVE
C INTEGRALS CALCULATED IN THE CARTESIAN REPRESENTATION.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ZILCH,EVEC
C      
      DIMENSION ICORE(MAXCOR),EVEC(1)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /AOPOPS/ AOPOP(8),MOPOP(8),NAO,NAOSPH,NMO
      COMMON /SZAOGM/ AOGMSZ(2,4,100)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /AOOFST/ INDOCC(8,2),INDVRT(8,2)
      COMMON /INFO/   NOCCO(2),NVRTO(2)
C
      DATA ONE /1.0/
      DATA ZILCH /0.0/
C
      NNP1O2(I)=(I*(I+1))/2
C
      IONE=1
      NMO =NOCCO(1)+NVRTO(1)
c      CALL GETREC(20,'JOBARC','NAOBASFN',IONE,NAO) 
c      CALL GETREC(20,'JOBARC','NBASTOT ',IONE,NAOSPH) 
C
C NOW READ THE MATRIX WHICH TRANSFORMS THE SPHERICAL HARMONIC
C EIGENVECTORS TO THE CARTESIAN REPRESENTATION
C
C       C(cartesian) = X C(spherical)
C
      I000=1
      I010=I000+NAOSPH*NAO*IINTFP
      CALL GETREC(20,'JOBARC','CMP2CART',NAOSPH*NAO*IINTFP,
     &            ICORE(I000))
C
C DO THE TRANSFORMATION
C
      IOFF=1
C
      CALL XGEMM('N','N',NAO,NMO,NAOSPH,ONE,ICORE(I000),NAO,
     &           EVEC,NAOSPH,ZILCH,ICORE(I010),NAO)
      CALL SCOPY(NAO*NMO*IINTFP,ICORE(I010),1,EVEC,1)
      RETURN
      END
