 
      SUBROUTINE SQUEZ3(VFULL,VPACK,NSIZE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION VFULL(NSIZE,NSIZE),VPACK(NSIZE*(NSIZE+1)/2)
      ITHRU=0
      DO 10 I=1,NSIZE
       DO 20 J=1,I
        ITHRU=ITHRU+1
        VPACK(ITHRU)=VPACK(ITHRU)+VFULL(I,J)
20     CONTINUE
10    CONTINUE
      RETURN
      END
