      SUBROUTINE DUOLD(DHFSO)
C
C  
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DIRPRD
      LOGICAL SCF,NONHF
      DIMENSION DHFSO(1)
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/BASSYM/NBAS(8),NBASIS,NBASSQ,NBASTT
      COMMON/METHOD/IUHF,SCF,NONHF
C
      DATA TWO /2.0D0/
C
       IND=0
       DO 900 IRREP=1,NIRREP
C
        N=NBAS(IRREP)
C
         DO 800 I=1,N
          DO 800 J=1,I
           IND=IND+1
           IF(I.EQ.J) DHFSO(IND)=TWO*DHFSO(IND)
800      CONTINUE
C
900     CONTINUE
C
       RETURN
       END
