      SUBROUTINE RDSRT(LUFIL,BUF,IBUF,NUT,LEN,NREC)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION BUF(LEN),IBUF(LEN)
      READ(LUFIL,REC=NREC)BUF,IBUF,NUT,ICHAIN
      NREC=ICHAIN
      RETURN
      END
