      SUBROUTINE DFOCK(ICORE,MAXCOR,IUHF)
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      IONE=1
      CALL GETREC(20,'JOBARC','NBASTOT ',IONE,NBAST)
      NBAS=NOCCO(1)+NVRTO(1)
      I000=1
      I010=I000+IINTFP*NBAST*NBAST
      I020=I010+4*IINTFP*NBAST*NBAST
C
C Added on 05/2014 to handle external perturbation logic in focklist
C 
      If (I020 .GE. Maxcor) Call Insmem("@-DFOC",I020, Maxcor)
      ILEFT = (MAXCOR - I020)/IINTFP 

      CALL FOCKLIST(ICORE(I000),ICORE(I010),ICORE(I020), ILEFT,
     &              NBAS,NBAST,IUHF)
      RETURN
      END
