      SUBROUTINE DMOSMT(ICORE,MAXCOR,IUHF)
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      NCOMP=NOCCO(1)+NVRTO(1)
      IONE=1
      CALL GETREC(20,'JOBARC','NBASTOT ',IONE,NBAS)
      I000=1
      I010=I000+NBAS*NCOMP*IINTFP
      I020=I010+NBAS*NCOMP*IINTFP
      I030=I020+NBAS*NBAS*IINTFP
      I040=I030+NBAS*NBAS*IINTFP
      I050=I040+NCOMP*NCOMP*IINTFP
      CALL MOOVLP(ICORE(I000),ICORE(I010),ICORE(I020),ICORE(I030),
     &            ICORE(I040),NBAS,NCOMP)
      RETURN
      END 
