      SUBROUTINE DOUB01(HEFF,ICORE,MAXCOR,IUHF)
C
C DOUBLES AMPLITUDE EQUATION FOR (0,1) FOCK SPACE SECTOR.  THE SPIN
C  ORBITAL EQUATIONS ARE:
C
C   T2(ij,ka) = W(ij,ka) - P(ij) T(im,ka)*F(mj) + W(ij,ke)*F(ae)
C      NN AN      NN AN            NN AN    NN      NN AN    NN
C
C             - T(ij,ma)*HEFF(km) + T(km)*W(ma,ij) 
C                 NN AN       AA      AI    IN NN
C
C             + T(nm,ka)*W(nm,ij) + P(ij) T(mj,ke)*W(ma,ie)
C                 NN AN    NN NN            NN AN    NN NNa
C
C             + THREE BODY TERM
C
C NOTE THAT THIS IS VERY SIMILAR TO THE EQUATION FOR THE EFFECTIVE
C HAMILTONIAN AND THE CODE IS CONSEQUENTLY A PRETTY STRAIGHTFORWARD 
C (AND EXPLICIT) HACKUP.
C  
CEND
      IMPLICIT INTEGER (A-H,O-Z)
      DOUBLE PRECISION ONE,ONEM,ZILCH
      LOGICAL RHF
      DIMENSION ICORE(MAXCOR),HEFF(1)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /FSSYM/ POPA(8,2),POPI(8,2),VRTA(8,2),VRTI(8,2),
     &               NTAN(2),NTNA(2),NTAA(2),
     &               NTIN(2),NTNI(2),NTII(2),
     &               NTAI(2),NTIA(2),
     &               NF1AN(2),NF1AA(2),NF1IN(2),NF1II(2),NF1AI(2),
     &               NF2AN(2),NF2AA(2),NF2IN(2),NF2II(2),NF2AI(2)
C
      DATA ONE/1.0/, ONEM/-1.0/, ZILCH /0.0/
C
      CALL T1INT201(ICORE,MAXCOR,IUHF)
      CALL HINT201 (HEFF,ICORE,MAXCOR,IUHF)
      CALL FMICNT01(ICORE,MAXCOR,IUHF)
      CALL FEACNT01(ICORE,MAXCOR,IUHF)
      CALL HHL01   (ICORE,MAXCOR,IUHF)
      IF(IUHF.EQ.0)THEN
       CALL RHFRNG01(ICORE,MAXCOR,IUHF)
       CALL RHF3BD01(ICORE,MAXCOR,IUHF)
      ELSE
       CALL UHFRNG01(ICORE,MAXCOR,IUHF)
       CALL UHF3BD01(ICORE,MAXCOR,IUHF)
      ENDIF
C
      RETURN
      END
