      SUBROUTINE EXTDRV(ICORE,MAXCOR,IUHF,RLECYC,LAMBDA)
C
C DRIVER FOR EXTRAPOLATION ROUTINES.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION R
      LOGICAL NEWT,SINGLE,LAMBDA
      DIMENSION ICORE(MAXCOR)
      COMMON /RMAT/ R(1000)
      COMMON /FLAGS/ IFLAGS(100)
      SAVE IBOT
C
      rletyp=2
      iflags(12)=10
C
      MAXORD=IFLAGS(12)
      NEWT=.FALSE.
      IF(RLECYC.LE.1)THEN
       CALL EXTLST(ICORE,MAXCOR,IUHF,SINGLE,RLETYP)
       CALL EXTPRT(ICORE,MAXCOR,IUHF,RLECYC,SINGLE,-1,RLETYP,LAMBDA)
       IF(RLECYC.EQ.0)THEN
        WRITE(6,1000)RLETYP+1,MAXORD
1000    FORMAT(T3,'@EXTDRV-I, RLE method #',I1,' will be used to ',
     &            'accelerate convergence.',/,
     &         T13,'Maximum dimension of iterative subspace is ',I3,'.')
        IBOT=0
        RLECYC=1
       ENDIF
       RETURN
      ENDIF
      CALL EXTPRT(ICORE,MAXCOR,IUHF,RLECYC,SINGLE,0,RLETYP,LAMBDA)
      CALL EXTMKR(ICORE,MAXCOR,IUHF,RLECYC,MAXORD,IBOT,SINGLE,RLETYP)
      IF(MOD(RLECYC-1,MAXORD).EQ.0.OR.RLETYP.EQ.2)THEN
       NEWT=.TRUE.
       CALL EXTTAU(ICORE,MAXCOR,IUHF,RLECYC,MAXORD,NEWT,IBOT,SINGLE,
     &             RLETYP)
       IF(RLETYP.NE.2)THEN
        IBOT=IBOT+RLECYC-1
        RLECYC=1
       ELSE
        IBOT=IBOT
       ENDIF
       RETURN
      ENDIF
      CALL EXTTAU(ICORE,MAXCOR,IUHF,RLECYC,MAXORD,NEWT,IBOT,SINGLE,
     &            RLETYP)
      RETURN
      END
