      SUBROUTINE EXTERR(ICORE,MAXCOR,IUHF,RLECYC,MAXORD,IBOT,I,J,
     &                  SINGLE,rletyp)
C
C THIS ROUTINE IS USED TO FORM THE R MATRIX USED IN THE RLE-1 METHOD.
C  PUT THREE T2 VECTORS IN CORE UNTIL WE KNOW WHETHER THIS WORKS OR NOT
C
C THE FORMULA FOR AN R MATRIX ELEMENT IS:
C
C                 (i)   (i-1)      (j)    (j-1)
C      R(I,J) = [T   - T     ] * [T    - T     ]
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      DOUBLE PRECISION R,SDOT,ONEM,ONE,X,FNDLRGAB,TOL
      LOGICAL SINGLE,GETT1V,ALLDONE
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /EXTRAP/ NSIZET(4)
      COMMON /RMAT/ R(1000)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
      COMMON /CONVERGE/ ALLDONE
      COMMON /EXTIO/ IOLDEST
      DATA ONEM /-1.0/
      DATA ONE  / 1.0/
      INDX(I,J)=I+(J-1)*MAXORD
      IGET(I)  =1+MOD(IOLDEST+MAXORD-I,MAXORD+1)
      RSIZE=MIN(RLECYC-1,MAXORD)
      tol=1.d-7
      IF(I.NE.0.AND.J.EQ.0)THEN
       IROW=I
       NLSTI=1+IROW
       DO 200 ICOL=1,RSIZE
        R(INDX(IROW,ICOL))=0.0
200    CONTINUE
       DO 201 ISPIN=4,4-3*IUHF,-1
        SIZET=NSIZET(ISPIN)
        I000=1
        I010=I000+SIZET*IINTFP
        I020=I010+SIZET*IINTFP
        I030=I020+SIZET*IINTFP
        IF(RLETYP.EQ.2)THEN
         CALL GETLST(ICORE(I000),IGET(NLSTI),1,1,ISPIN+4,77)
        ELSE
         CALL GETLST(ICORE(I000),IGET(NLSTI),1,1,ISPIN,77)
        ENDIF
        CALL GETLST(ICORE(I010),IGET(NLSTI-1),1,1,ISPIN,77)
        CALL SAXPY(SIZET,ONEM,ICORE(I010),1,ICORE(I000),1)
        IF(I.EQ.1.AND.IROW.EQ.1)THEN
         X=FNDLRGAB(ICORE(I000),SIZET)
         WRITE(6,100)X
         IF(ABS(X).LT.TOL)ALLDONE=.TRUE.
        ENDIF
        DO 202 ICOL=1,RSIZE  
         IOFF=INDX(IROW,ICOL)
         NLSTJ=1+ICOL
         NLSTJP1=NLSTJ-1
         IF(RLETYP.EQ.2)THEN
          CALL GETLST(ICORE(I010),IGET(NLSTJ),1,1,ISPIN+4,77)
         ELSE
          CALL GETLST(ICORE(I010),IGET(NLSTJ),1,1,ISPIN,77)
         ENDIF
         CALL GETLST(ICORE(I020),IGET(NLSTJ-1),1,1,ISPIN,77)
         CALL SAXPY(SIZET,ONEM,ICORE(I020),1,ICORE(I010),1)
         R(IOFF)=R(IOFF)+SDOT(SIZET,ICORE(I000),1,ICORE(I010),1)
202     CONTINUE
201    CONTINUE
      ELSEIF(I.EQ.0.AND.J.NE.0)THEN
       ICOL=J
       NLSTJ=1+ICOL
       DO 300 IROW=1,RSIZE
        R(INDX(IROW,ICOL))=0.0
300    CONTINUE
       DO 301 ISPIN=4,4-3*IUHF,-1
        SIZET=NSIZET(ISPIN)
        I000=1
        I010=I000+SIZET*IINTFP
        I020=I010+SIZET*IINTFP
        I030=I020+SIZET*IINTFP
        IF(RLETYP.EQ.2)THEN
         CALL GETLST(ICORE(I000),IGET(NLSTJ),1,1,ISPIN+4,77)
        ELSE
         CALL GETLST(ICORE(I000),IGET(NLSTJ),1,1,ISPIN,77)
        ENDIF
        CALL GETLST(ICORE(I010),IGET(NLSTJ-1),1,1,ISPIN,77)
        CALL SAXPY(SIZET,ONEM,ICORE(I010),1,ICORE(I000),1)
        IF(ICOL.EQ.1.AND.J.EQ.1)THEN
         X=FNDLRGAB(ICORE(I000),SIZET)
         WRITE(6,100)X
100      FORMAT(T3,'@EXTERR-I, Largest change in amplitudes: ',
     &          F15.12,'.')
         IF(ABS(X).LT.TOL)ALLDONE=.TRUE.
        ENDIF
        DO 302 IROW=1,RSIZE
         NLSTI=1+IROW
         IOFF=INDX(IROW,ICOL)
         IF(RLETYP.EQ.2)THEN
          CALL GETLST(ICORE(I010),IGET(NLSTI),1,1,ISPIN+4,77)
         ELSE
          CALL GETLST(ICORE(I010),IGET(NLSTI),1,1,ISPIN,77)
         ENDIF
         CALL GETLST(ICORE(I020),IGET(NLSTI-1),1,1,ISPIN,77)
         CALL SAXPY(SIZET,ONEM,ICORE(I020),1,ICORE(I010),1)
         R(IOFF)=R(IOFF)+SDOT(SIZET,ICORE(I000),1,ICORE(I010),1)
302     CONTINUE
301    CONTINUE
      ELSE
       RETURN
      ENDIF
      RETURN
      END
