      SUBROUTINE EXTLST(ICORE,MAXCOR,IUHF,SINGLE,RLETYP)
C
C THIS ROUTINE CREATES THE T AMPLITUDE LISTS USED BY THE 
C  RLE PROGRAM.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /EXTRAP/ NSIZET(4)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
      COMMON /FSSYM/ POPA(8,2),POPI(8,2),VRTA(8,2),VRTI(8,2),
     &               NTAN(2),NTNA(2),NTAA(2),
     &               NTIN(2),NTNI(2),NTII(2),
     &               NTAI(2),NTIA(2),
     &               NF1AN(2),NF1AA(2),NF1IN(2),NF1II(2),NF1AI(2),
     &               NF2AN(2),NF2AA(2),NF2IN(2),NF2II(2),NF2AI(2)
      NRLE=IFLAGS(12)+1
      CALL IZERO(NSIZET,4)
      DO 110 ISPIN=4,4-3*IUHF,-1
       DO 111 IRREP=1,NIRREP
        DISSIZ=IRPDPD(IRREP,ISYTYP(1,95+ISPIN))
        IF(ISPIN.NE.3)THEN
         NUMDIS=FSDPDAN(IRREP,ISYTYP(2,95+ISPIN))
        ELSE
         NUMDIS=FSDPDNA(IRREP,ISYTYP(2,95+ISPIN))
        ENDIF
        NSIZET(ISPIN)=NSIZET(ISPIN)+NUMDIS*DISSIZ
111    CONTINUE
       IF(ISPIN.LT.3.OR.IUHF.EQ.0)THEN
        NSIZET(ISPIN)=NSIZET(ISPIN)+NF1AI(MIN(ISPIN,1+IUHF))
       ENDIF
       CALL UPDMOI(NRLE,NSIZET(ISPIN),ISPIN,77,0,0)
       IF(RLETYP.EQ.2)THEN
        CALL UPDMOI(NRLE,NSIZET(ISPIN),ISPIN+4,77,0,0)
       ENDIF
c       CALL UPDMOI(1,NSIZET(ISPIN),ISPIN,89,0,0)
110   CONTINUE
      RETURN
      END
