
      SUBROUTINE GATHER(LENGTH,A,B,INDX)
C
C FORTRAN EQUIVALENT FOR THE CRAY SCILIB ROUTINE GATHER.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(LENGTH),B(1),INDX(LENGTH)
      DO 10 I=1,LENGTH
       A(I)=B(INDX(I))
10    CONTINUE
      RETURN
      END
