      SUBROUTINE MODHEFF(ICORE,MAXCOR,IUHF,ITYPE)
C
C THIS ROUTINE ADDS OR SUBTRACTS THE DIAGONAL ELEMENTS FROM
C THE ONE-PARTICLE PART OF THE (01) EFFECTIVE HAMILTONIAN
C
C ITYPE > 0 -> - F(pp) added
C ITYPE < 0 -> - F(pp) subtracted
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM,ZILCH,FACT
      CHARACTER*8 LABEL(2)
      DIMENSION ICORE(MAXCOR)
      COMMON/SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      DATA ONE /1.0/
      DATA ZILCH /0.0/
      DATA ONEM/-1.0/
      DATA LABEL /'SCFEVALA','SCFEVALB'/
C
      NBAs=NOCCO(1)+NVRTO(1)
C
      FACT=ZILCH
      IF(ITYPE.GT.0)FACT=ONEM
      IF(ITYPE.LT.0)FACT=ONE
C
      DO 10 ISPIN=1,1+IUHF
       I000=1
       I010=I000+IINTFP*NFMI(ISPIN)
       I020=I010+IINTFP*NFMI(ISPIN)
       CALL GETLST(ICORE(I010),1,1,1,ISPIN,91)
       CALL GETLST(ICORE(I020),1,1,1,ISPIN+2,91) 
       IOFFMI1=I010
       IOFFMI2=I020
       DO 20 IRREP=1,NIRREP
        NOCC=POP(IRREP,ISPIN)
        CALL SAXPY(NOCC,FACT,ICORE(IOFFMI1),NOCC+1,ICORE(IOFFMI2),
     &             NOCC+1) 
        IOFFMI1=IOFFMI1+NOCC*NOCC*IINTFP 
        IOFFMI2=IOFFMI2+NOCC*NOCC*IINTFP 
20     CONTINUE
       CALL PUTLST(ICORE(I020),1,1,1,2+ISPIN,91)
10    CONTINUE
C
      RETURN
      END
