      SUBROUTINE CHECK(ICORE,MAXCOR,IUHF)
C
C   ROUTINE TO CHECK THE GAMMA CONTRIBUTIONS
C
C   THIS ROUTIBE CALCULATES   :
C
C    1/4 SUM I J SUM A B T(IJ,AB) D(IJ,AB) L(IJ,AB)
C
C    SUM I SUM A T(I,A) D(I,A) L(I,A)
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      DIMENSION ICORE(MAXCOR)
      DOUBLE PRECISION E4D,FACTOR,EAA,E4X,SDOT
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON/METH/MBPT2,MBPt3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      EAA=0.0
      E4D=0.0
      FACTOR=1.0
      IF(IUHF.EQ.0)FACTOR=2.0
C
C COMPUTE AB CONTRIBUTION TO E4D.
C
      NLIST=46
      DO 10 IRREP=1,NIRREP
       NDSSYM=IRPDPD(IRREP,ISYTYP(2,NLIST))
       DISSYM=IRPDPD(IRREP,ISYTYP(1,NLIST))
       NSIZE=DISSYM*NDSSYM
       I000=1
       I010=I000+IINTFP*NSIZE
       I020=I010+IINTFP*NSIZE
       CALL GETLST(ICORE(I000),1,NDSSYM,1,IRREP,NLIST)
       CALL GETLST(ICORE(I010),1,NDSSYM,2,IRREP,NLIST+100)
       CALL VECPRD(ICORE(I000),ICORE(I010),ICORE(I000),NSIZE)
       CALL GETLST(ICORE(I010),1,NDSSYM,1,IRREP,66)
       E4X=SDOT(NSIZE,ICORE(I000),1,ICORE(I010),1)
       E4D=E4D+E4X
10    CONTINUE
      write(*,*) 'for ab the contribution is',E4D
C
C COMPUTE AA AND BB (BB FOR UHF ONLY) CONTRIBUTIONS TO E4D.
C
      DO 100 ISPIN=1,1+IUHF
       NLIST=43+ISPIN
       DO 20 IRREP=1,NIRREP
        NDSSYM=IRPDPD(IRREP,ISYTYP(2,NLIST))
        DISSYM=IRPDPD(IRREP,ISYTYP(1,NLIST))
        NSIZE=DISSYM*NDSSYM
        I000=1
        I010=I000+IINTFP*NSIZE
        I020=I010+IINTFP*NSIZE
        CALL GETLST(ICORE(I000),1,NDSSYM,1,IRREP,NLIST)
        CALL GETLST(ICORE(I010),1,NDSSYM,2,IRREP,NLIST+100)
        CALL VECPRD(ICORE(I000),ICORE(I010),ICORE(I000),NSIZE)
        CALL GETLST(ICORE(I010),1,NDSSYM,1,IRREP,63+ISPIN)
        E4X=SDOT(NSIZE,ICORE(I000),1,ICORE(I010),1)
        EAA=EAA+E4X
       write(*,*) ' FOR SPIN',ispin,' CONTRIBUTION IS',EAA
20     CONTINUE
C
C  ADD SINGLES  
C
       IF(CCSD.OR.QCISD) THEN
       NLIST=90
       NSIZE=NT(ISPIN)
       I000=1
       I010=I000+IINTFP*NSIZE
       I020=I010+IINTFP*NSIZE
       CALL GETLST(ICORE(I000),1,1,1,ISPIN,NLIST)
       CALL GETLST(ICORE(I010),1,1,2,ISPIN,NLIST+100)
       CALL VECPRD(ICORE(I000),ICORE(I010),ICORE(I000),NSIZE) 
       CALL GETLST(ICORE(I010),1,1,1,9,63+ISPIN)
       E4X=SDOT(NSIZE,ICORE(I000),1,ICORE(I010),1)
       EAA=EAA+E4X
       ENDIF
       write(*,*) ' FOR SPIN',ispin,' CONTRIBUTION IS',EAA
100   CONTINUE
      E4D=E4D+FACTOR*EAA
      write(*,*) ' T*D*L CONTRIBUTION IS ',E4D
      RETURN
      END
