      SUBROUTINE NWRNGAA(ICORE,MAXCOR,IUHF)
C
C THIS ROUTINE SWITCHES THE ORDERING OF THE AAAA (BBBB) RING
C  INTEGRALS.   NORMALLY, THEY ARE STORED
C
C          <AI||BJ>  A,J ; B,I
C
C THIS ROUTINE CHANGES THIS TO
C
C          <AI||BJ>  A,I ; B,J
C
C AND GOES IN THE OPPOSITE DIRECTION IF THEY ARE ALREADY STORED IN
C  THE LATTER WAY.
C
CEND
      IMPLICIT INTEGER (A-Z)
      CHARACTER*4 SPTYPE(2)
      DIMENSION ICORE(MAXCOR)
      COMMON /SYMPOP2/ IRPDPD(8,22)
      COMMON /SYMPOP/ IRP_DM(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD 
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /SHIFT/ ISHIFT 
      DATA SPTYPE /'AAAA','BBBB'/
      DO 10 ISPIN=1,1+IUHF
       NLIST=22+ISPIN + ISHIFT 
       ISIZE=isyms2(ISYTYP(1,NLIST),ISYTYP(2,NLIST))
       I000=1
       I010=I000+IINTFP*ISIZE
       I020=I010+IINTFP*ISIZE
       I030=I020+2*NOCCO(ISPIN)*NVRTO(ISPIN)
       CALL GETALL2(ICORE(I000),ISIZE,1,NLIST)
       CALL SSTRNG(ICORE(I000),ICORE(I010),ISIZE,ISIZE,ICORE(I020),
     &             SPTYPE(ISPIN))
       CALL PUTALL2(ICORE(I010),ISIZE,1,NLIST)
10    CONTINUE
      RETURN
      END
