
      SUBROUTINE RDABCDAB(W,LENGTH,ITOPADR,ILOWADR,BUF,IBUF,
     &                   IRREPA,IRREPB,IPDSZ,IPDIS,ISYM,IPW,
     &                   NUMIRW,NWDIS,ILNBUF,IUHF,GRAD)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION W,BUF
      LOGICAL GRAD
      DIMENSION W(LENGTH),BUF(ILNBUF),IBUF(ILNBUF)
      DIMENSION IRREPA(*),IRREPB(*),IPDSZ(*),IPDIS(*),ISYM(*)
      DIMENSION IPW(*),NUMIRW(*)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      COMMON/INFO/ NOCCO(2),NVRTO(2)
C
      IUPKI(INTX)=AND(INTX,IALONE)
      IUPKJ(INTX)=AND(ISHFT(INTX,-IBITWD),IALONE)
      IUPKK(INTX)=AND(ISHFT(INTX,-2*IBITWD),IALONE)
      IUPKL(INTX)=AND(ISHFT(INTX,-3*IBITWD),IALONE)
      INDX(I,J,N)=I+(J-1)*N
      INDXA(I,J)=I+(J-1)*J/2
C
C POSITION HF2 FILE AT FIRST INTEGRAL RECORD
C
      CALL SETHF2(1+2*IUHF,BUF,IBUF,ILNBUF,IUHF)
C
      NORBA  =NVRTO(1)
      NORBB  =NVRTO(2)
      NVA  =NVRTO(1)
      NVB  =NVRTO(2)
      NOA  =NOCCO(1)
      NOB  =NOCCO(2)
      IOFFSET=ILOWADR-1
      ITOP   =ITOPADR-IOFFSET
      ICOUNT =0
      CALL ZERO(W,ITOP)
C
C READ IN BATCHES OF INTEGRALS
C
      IF((IUHF.EQ.0).AND.(.NOT.GRAD))THEN
1      READ(25,END=103)BUF,IBUF,NUT
       IF(NUT.EQ.-1)GOTO 103
CDIR$ IVDEP
       DO 11 IK=1,NUT
        I=IUPKK(IBUF(IK))
        J=IUPKL(IBUF(IK))
        K=IUPKI(IBUF(IK))
        L=IUPKJ(IBUF(IK))
C
C ASSURE THAT J>I, L>K.
C
        IF(I.GT.J)THEN
         IT=J
         J=I
         I=IT
        ENDIF
        IF(K.GT.L)THEN
         IT=L
         L=K
         K=IT
        ENDIF
        I=I-NOA
        J=J-NOA
        K=K-NOA
        L=L-NOA
        ITMP=K
        K=J
        J=ITMP
        ILOAD=MIN(I,J,K,L)
        IF(ILOAD.GT.0)THEN
         ICOUNT =ICOUNT+1
C
C WE HAVE AN ABCD INTEGRAL - CALCULATE ITS ABSOLUTE INDEX
C
         I1=INDX(I,J,NORBA)
         I2=INDX(K,L,NORBA)
         I5=INDX(J,I,NORBA)
         I6=INDX(L,K,NORBA)
         I1A=INDXA(I,J)
         I2A=INDXA(K,L)
         I5A=INDXA(J,I)
         I6A=INDXA(L,K)
         IRREPIJ=DIRPRD(IRREPA(I+NOA),IRREPB(J+NOB))
         IOFF=IPW(IRREPIJ)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIJ+NIRREP)
          IF(I.LE.J) THEN
           IADR1=IOFF+ISYM(I1A+NWDIS)-IPDSZ(IRREPIJ)
     &           +NN*(ISYM(I2)-1-IPDIS(IRREPIJ))-IOFFSET
           IF(IADR1.LE.ITOP.AND.IADR1.GT.0)W(IADR1)=BUF(IK)
          ENDIF
          IF(J.LE.I) THEN
           IADR5=IOFF+ISYM(I5A+NWDIS)-IPDSZ(IRREPIJ)
     &           +NN*(ISYM(I6)-1-IPDIS(IRREPIJ))-IOFFSET
           IF(IADR5.LE.ITOP.AND.IADR5.GT.0)W(IADR5)=BUF(IK)
          ENDIF
          IF(K.LE.L) THEN
           IADR2=IOFF+ISYM(I2A+NWDIS)-IPDSZ(IRREPIJ)
     &             +NN*(ISYM(I1)-1-IPDIS(IRREPIJ))-IOFFSET
           IF(IADR2.LE.ITOP.AND.IADR2.GT.0)W(IADR2)=BUF(IK)
          ENDIF
          IF(L.LE.K) THEN
           IADR6=IOFF+ISYM(I6A+NWDIS)-IPDSZ(IRREPIJ)
     &             +NN*(ISYM(I5)-1-IPDIS(IRREPIJ))-IOFFSET
           IF(IADR6.LE.ITOP.AND.IADR6.GT.0)W(IADR6)=BUF(IK)
          ENDIF
         ENDIF
C
         I3=INDX(I,L,NORBA)
         I4=INDX(K,J,NORBA)
         I7=INDX(L,I,NORBA)
         I8=INDX(J,K,NORBA)
         I3A=INDXA(I,L)
         I4A=INDXA(K,J)
         I7A=INDXA(L,I)
         I8A=INDXA(J,K)
         IRREPIL=DIRPRD(IRREPA(I+NOB),IRREPB(L+NOA))
         IOFF=IPW(IRREPIL)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIL+NIRREP)
          IF(I.LE.L) THEN
           IADR3=IOFF+ISYM(I3A+NWDIS)-IPDSZ(IRREPIL)
     &             +NN*(ISYM(I4)-1-IPDIS(IRREPIL)) -IOFFSET
           IF(IADR3.LE.ITOP.AND.IADR3.GT.0)W(IADR3)=BUF(IK)
          ENDIF
          IF(L.LE.I) THEN
           IADR7=IOFF+ISYM(I7A+NWDIS)-IPDSZ(IRREPIL)
     &             +NN*(ISYM(I8)-1-IPDIS(IRREPIL))-IOFFSET
           IF(IADR7.LE.ITOP.AND.IADR7.GT.0)W(IADR7)=BUF(IK)
          ENDIF
          IF(K.LE.J) THEN
           IADR4=IOFF+ISYM(I4A+NWDIS)-IPDSZ(IRREPIL)
     &             +NN*(ISYM(I3)-1-IPDIS(IRREPIL))-IOFFSET
           IF(IADR4.LE.ITOP.AND.IADR4.GT.0)W(IADR4)=BUF(IK)
          ENDIF
          IF(J.LE.K) THEN
           IADR8=IOFF+ISYM(I8A+NWDIS)-IPDSZ(IRREPIL)
     &             +NN*(ISYM(I7)-1-IPDIS(IRREPIL))-IOFFSET
           IF(IADR8.LE.ITOP.AND.IADR8.GT.0)W(IADR8)=BUF(IK)
          ENDIF
C
         ENDIF
C
        ENDIF
C
11     CONTINUE
C
       IF(NUT.NE.-1)GOTO 1
C
103    CONTINUE
C
      ELSEIF(IUHF.EQ.0.AND.GRAD)THEN
2      READ(25,END=203)BUF,IBUF,NUT
       IF(NUT.EQ.-1)GOTO 203
CDIR$ IVDEP
       DO 200 IK=1,NUT
        I=IUPKJ(IBUF(IK))
        J=IUPKI(IBUF(IK))
        K=IUPKL(IBUF(IK))
        L=IUPKK(IBUF(IK))
C
C ASSURE THAT J>I, L>K.
C
        IF(I.GT.J)THEN
         IT=J
         J=I
         I=IT
        ENDIF
        IF(K.GT.L)THEN
         IT=L
         L=K
         K=IT
        ENDIF
        I=I-NOA
        J=J-NOA
        K=K-NOA
        L=L-NOA
        ITMP=K
        K=J
        J=ITMP
        ILOAD=MIN(I,J,K,L)
        IF(ILOAD.GT.0)THEN
         ICOUNT =ICOUNT+1
C
C TERM 1, 2, 5 AND 6
         I1=INDX(I,J,NORBA)
         I2=INDX(K,L,NORBA)
         I5=INDX(J,I,NORBA)
         I6=INDX(L,K,NORBA)
         IRREPIJ=DIRPRD(IRREPA(I+NOA),IRREPB(J+NOB))
         IOFF=IPW(IRREPIJ)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIJ)
          IADR1=IOFF+ISYM(I1)-IPDSZ(IRREPIJ)
     &           +NN*(ISYM(I2)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR1.LE.ITOP.AND.IADR1.GT.0)W(IADR1)=BUF(IK)
          IADR2=IOFF+ISYM(I2)-IPDSZ(IRREPIJ)
     &            +NN*(ISYM(I1)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR2.LE.ITOP.AND.IADR2.GT.0)W(IADR2)=BUF(IK)
          IADR5=IOFF+ISYM(I5)-IPDSZ(IRREPIJ)
     &            +NN*(ISYM(I6)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR5.LE.ITOP.AND.IADR5.GT.0)W(IADR5)=BUF(IK)
          IADR6=IOFF+ISYM(I6)-IPDSZ(IRREPIJ)
     &            +NN*(ISYM(I5)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR6.LE.ITOP.AND.IADR6.GT.0)W(IADR6)=BUF(IK)
         ENDIF
C
C TERM 3, 4, 7 AND 8    
C
         I3=INDX(I,L,NORBA)
         I4=INDX(K,J,NORBA)
         I7=INDX(L,I,NORBA)
         I8=INDX(J,K,NORBA)
         IRREPIL=DIRPRD(IRREPA(I+NOB),IRREPB(L+NOA))
         IOFF=IPW(IRREPIL)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIL)
          IADR3=IOFF+ISYM(I3)-IPDSZ(IRREPIL)
     &            +NN*(ISYM(I4)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR3.LE.ITOP.AND.IADR3.GT.0)W(IADR3)=BUF(IK)
          IADR4=IOFF+ISYM(I4)-IPDSZ(IRREPIL)
     &           +NN*(ISYM(I3)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR4.LE.ITOP.AND.IADR4.GT.0)W(IADR4)=BUF(IK)
          IADR7=IOFF+ISYM(I7)-IPDSZ(IRREPIL)
     &            +NN*(ISYM(I8)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR7.LE.ITOP.AND.IADR7.GT.0)W(IADR7)=BUF(IK)
          IADR8=IOFF+ISYM(I8)-IPDSZ(IRREPIL)
     &            +NN*(ISYM(I7)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR8.LE.ITOP.AND.IADR8.GT.0)W(IADR8)=BUF(IK)
         ENDIF
        ENDIF
200    CONTINUE
       IF(NUT.NE.-1)GOTO 2
203    CONTINUE
C
      ELSEIF(IUHF.EQ.1)THEN
3      READ(25,END=303)BUF,IBUF,NUT
       IF(NUT.EQ.-1)GOTO 303
CDIR$ IVDEP
       DO 300 IK=1,NUT
        I=IUPKK(IBUF(IK))
        J=IUPKL(IBUF(IK))
        K=IUPKI(IBUF(IK))
        L=IUPKJ(IBUF(IK))
C
C ASSURE THAT J>I, L>K.
C
        IF(I.GT.J)THEN
         IT=J
         J=I
         I=IT
        ENDIF
        IF(K.GT.L)THEN
         IT=L
         L=K
         K=IT
        ENDIF
        I=I-NOA
        J=J-NOA
        K=K-NOB
        L=L-NOB
        ITMP=K
        K=J
        J=ITMP
        ILOAD=MIN(I,J,K,L)
        IF(ILOAD.GT.0)THEN
         ICOUNT =ICOUNT+1
C
C TERM 1 AND 2
C
         I1=INDX(I,J,NORBA)
         I2=INDX(K,L,NORBA)
         IRREPIJ=DIRPRD(IRREPA(I+NOA),IRREPB(J+NOB))
         IOFF=IPW(IRREPIJ)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIJ)
          IADR1=IOFF+ISYM(I1)-IPDSZ(IRREPIJ)
     &            +NN*(ISYM(I2)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR1.LE.ITOP.AND.IADR1.GT.0)W(IADR1)=BUF(IK)
          IADR2=IOFF+ISYM(I2)-IPDSZ(IRREPIJ)
     &            +NN*(ISYM(I1)-1-IPDIS(IRREPIJ))-IOFFSET
          IF(IADR2.LE.ITOP.AND.IADR2.GT.0)W(IADR2)=BUF(IK)
         ENDIF
C
C TERM 3 AND 4   
C
         I3=INDX(I,L,NORBA)
         I4=INDX(K,J,NORBA)
         IRREPIL=DIRPRD(IRREPA(I+NOA),IRREPB(L+NOB))
         IOFF=IPW(IRREPIL)
         IF(IOFF.LE.ITOPADR)THEN
          NN=NUMIRW(IRREPIL)
          IADR3=IOFF+ISYM(I3)-IPDSZ(IRREPIL)
     &            +NN*(ISYM(I4)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR3.LE.ITOP.AND.IADR3.GT.0)W(IADR3)=BUF(IK)
          IADR4=IOFF+ISYM(I4)-IPDSZ(IRREPIL)
     &            +NN*(ISYM(I3)-1-IPDIS(IRREPIL))-IOFFSET
          IF(IADR4.LE.ITOP.AND.IADR4.GT.0)W(IADR4)=BUF(IK)
         ENDIF
        ENDIF
300    CONTINUE
       IF(NUT.NE.-1)GOTO 3
303    CONTINUE
C
C
       WRITE(6,1000)ICOUNT
C
1000   FORMAT(T3,'@RDABCDAB-I, Processed ',I12,' ABCD integrals.')
      ENDIF
C
      RETURN
      END
