      SUBROUTINE SETHF2(ISPIN,BUF,IBUF,IBFSIZ,IUHF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*80 FNAME
      CHARACTER*10 STRING
      DIMENSION BUF(IBFSIZ),IBUF(IBFSIZ) 
      LOGICAL YESNO,DOALL,ABIJ,NOABCD
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /DOINTS/ DOALL,ABIJ,NOABCD
C
C LOCATE FIRST INTEGRAL RECORD FOR GIVEN SPIN CASE.
C
      IF(IUHF.EQ.0) THEN
       CALL GFNAME('HF2     ',FNAME,ILENGTH)
      ELSE
       IF(ISPIN.EQ.1) THEN
        CALL GFNAME('HF2AA   ',FNAME,ILENGTH)
       ELSE IF(ISPIN.EQ.2) THEN
        CALL GFNAME('HF2BB   ',FNAME,ILENGTH)
       ELSE IF(ISPIN.EQ.3) THEN
        CALL GFNAME('HF2AB   ',FNAME,ILENGTH)
       ENDIF
      ENDIF
C
      INQUIRE(UNIT=25,OPENED=YESNO)
      IF(.NOT.YESNO)THEN
       OPEN(UNIT=25,FILE=FNAME(1:ILENGTH),FORM='UNFORMATTED',
     &  STATUS='OLD')
      ENDIF
      REWIND(25)
      IF(IUHF.EQ.0.OR.ISPIN.EQ.3) THEN
 1     READ(25)STRING
       IF(INDEX(STRING,'**').EQ.0)GOTO 1
      ENDIF
      RETURN
      END
