      SUBROUTINE SRTEVAL(NROOT,LENVEC,EVAL,EVEC,SCR,ISCR)
C
C ORDERS EIGENVALUES FROM SMALLEST TO LARGEST AND
C ALSO REORDERS THE VECTORS CORRESPONDINGLY.
C
C NROOT : NUMBER OF EIGENVALUES
C LENVEC: LENGTH OF EIGENVECTORS
C EVAL  : EIGENVALUES TO BE REORDERED [LENGTH : NROOT]
C EVEC  : CORRESPONDING EIGENVECTORS  [LENGTH : NROOT*LENVEC]
C SCR   : FLOATING POINT SCRATCH AREA [LENGTH : NROOT*LENVEC]
C ISCR  : INTEGER SCRATCH AREA        [LENGTH : NROOT]
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION EVAL(NROOT),EVEC(LENVEC,NROOT),
     &          SCR(LENVEC,NROOT),ISCR(NROOT)
C
      DO 10 I=1,NROOT
       ISCR(I)=I
10    CONTINUE
C
      CALL PIKSR2(NROOT,EVAL,ISCR)
C
      DO 20 I=1,NROOT
       J=ISCR(I)
       CALL SCOPY(LENVEC,EVEC(1,J),1,SCR(1,I),1)
20    CONTINUE
C
      CALL SCOPY(LENVEC*NROOT,SCR,1,EVEC,1)
C
      RETURN
      END
