      SUBROUTINE STT4AB(W,BUF,IBUF,ISYMVO,ISIZVO,
     &                  IOFFVO,IOFFW,ITMP1,ITMP2,
     &                  ITMP3,ITMP4,LENW,ICASE,IUHF,NMO,
     &                  IRREPS)
C
C THIS SUBROUTINE PROCESSES THE <Ai|Bj> AND <aI|bJ> INTEGRALS 
C  PUTS THEM INTO A SYMMETRY PACKED LIST AND WRITES THEM TO DISK AS
C  THE MATRIX W(Aj,Bi) OR W(aJ,bI).  ICASE=1 IS FOR <Ai|Bj>, ICASE=2
C  IS FOR <aI|bJ>.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER A,B,DIRPRD,POP,VRT,AND
      CHARACTER*8 INAME
      CHARACTER*80 FNAME
      DIMENSION BUF(ILNBUF),IBUF(ILNBUF),W(LENW)
      DIMENSION ISYMVO(1),IOFFW(NIRREP),IRREPS(NMO,2)
      DIMENSION ISIZVO(NIRREP),IOFFVO(NIRREP)
      DIMENSION ITMP1(ILNBUF),ITMP2(ILNBUF),ITMP3(ILNBUF),ITMP4(ILNBUF)
C
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /BUFLEN/ ILNBUF
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /SHIFT/ ISHIFT,NDRGEO
C
      IUPKI(INT)=AND(INT,IALONE)
      IUPKJ(INT)=AND(ISHFT(INT,-IBITWD),IALONE)
      IUPKK(INT)=AND(ISHFT(INT,-2*IBITWD),IALONE)
      IUPKL(INT)=AND(ISHFT(INT,-3*IBITWD),IALONE)
      INDXF(I,J,N)=I+(J-1)*N
C
      NOCA=NOCCO(1)
      NOCB=NOCCO(2)
      NVRTA=NVRTO(1)
      NVRTB=NVRTO(2)
C
      IF(IFLAGS(1).GE.1)WRITE(LUOUT,2000)
2000  FORMAT(T3,'@STT4AB-I, Processing integral type PHPH, ',
     &       'spin case ABAB.')
C
      IF(ICASE.EQ.1)THEN
       INAME='PHPH1P  '
       ISET=NOCA
       NUMVRT=NVRTA
       ISPINA=1
       ISPINJ=2
      ELSE
       INAME='PHPH2P  '
       ISET=NOCB
       NUMVRT=NVRTB
       ISPINA=2
       ISPINJ=1
      ENDIF
      CALL GFNAME(INAME,FNAME,ILENGTH)
      OPEN(UNIT=15,FILE=FNAME(1:ILENGTH),
     &FORM='UNFORMATTED',ACCESS='SEQUENTIAL',STATUS='OLD')
      CALL ZERO(W,LENW)
C
C PICK UP A BUFFER OF INTEGRALS
C
1     READ(15)BUF,IBUF,NUT
      IF(ICASE.EQ.2)THEN
       DO 10 INT=1,NUT
        ITMP1(INT)=IUPKI(IBUF(INT))
        ITMP2(INT)=IUPKJ(IBUF(INT))
        ITMP3(INT)=IUPKK(IBUF(INT))
        ITMP4(INT)=IUPKL(IBUF(INT))
        I=ITMP1(INT)
        A=ITMP2(INT)
        J=ITMP3(INT)
        B=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
C
C GET AJ AND BI ABSOLUTE OFFSETS
C
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
C
C NOW GET RELATIVE AJ SYMMETRY OFFSET WITHIN THE DPD BLOCK AND DO SAME
C  FOR BI
C
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
C
C NOW CALCULATE ABSOLUTE POSITION IN W VECTOR WHERE THIS ELEMENT
C  BELONGS
C
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
10     CONTINUE
C
C REVERSE SENSE OF A-B
C
       DO 20 INT=1,NUT
        I=ITMP1(INT)
        B=ITMP2(INT)
        J=ITMP3(INT)
        A=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
20     CONTINUE
C
C REVERSE SENSE OF I-J
C
       DO 30 INT=1,NUT
        J=ITMP1(INT)
        A=ITMP2(INT)
        I=ITMP3(INT)
        B=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
30     CONTINUE
C
C REVERSE SENSE OF A-B AND I-J
C
       DO 40 INT=1,NUT
        J=ITMP1(INT)
        B=ITMP2(INT)
        I=ITMP3(INT)
        A=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
40     CONTINUE
      ELSE
       DO 110 INT=1,NUT
        ITMP1(INT)=IUPKI(IBUF(INT))
        ITMP2(INT)=IUPKJ(IBUF(INT))
        ITMP3(INT)=IUPKK(IBUF(INT))
        ITMP4(INT)=IUPKL(IBUF(INT))
        A=ITMP1(INT)
        I=ITMP2(INT)
        B=ITMP3(INT)
        J=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
C
C GET AJ AND BI ABSOLUTE OFFSETS
C
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
C
C NOW GET RELATIVE AJ SYMMETRY OFFSET WITHIN THE DPD BLOCK AND DO SAME
C  FOR BI
C
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
C
C NOW CALCULATE ABSOLUTE POSITION IN W VECTOR WHERE THIS ELEMENT
C  BELONGS
C
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
110     CONTINUE
C
C REVERSE SENSE OF A-B
C
       DO 120 INT=1,NUT
        B=ITMP1(INT)
        I=ITMP2(INT)
        A=ITMP3(INT)
        J=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
120    CONTINUE
C
C REVERSE SENSE OF I-J
C
       DO 130 INT=1,NUT
        A=ITMP1(INT)
        J=ITMP2(INT)
        B=ITMP3(INT)
        I=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
130    CONTINUE
C
C REVERSE SENSE OF A-B AND I-J
C
       DO 140 INT=1,NUT
        B=ITMP1(INT)
        J=ITMP2(INT)
        A=ITMP3(INT)
        I=ITMP4(INT)
        IA=A+ISET
        X=BUF(INT)
        IRRA=IRREPS(IA,ISPINA)
        IRRJ=IRREPS(J,ISPINJ)
        IRDPD=DIRPRD(IRRA,IRRJ)
        IOFFAJ=INDXF(A,J,NUMVRT)
        IOFFBI=INDXF(B,I,NUMVRT)
        IOFAJS=ISYMVO(IOFFAJ)-IOFFVO(IRDPD)
        IOFBIS=ISYMVO(IOFFBI)-IOFFVO(IRDPD)
        IABSOF=IOFFW(IRDPD)
        IRELOF=INDXF(IOFAJS,IOFBIS,ISIZVO(IRDPD))
        IOFF=IRELOF+IABSOF
        W(IOFF)=X
140    CONTINUE
      ENDIF
      IF(NUT.EQ.ILNBUF)GOTO 1
C
C NOW DUMP THESE TO DISK
C
      CALL PUTALL(W,LENW,1,24+ICASE + ISHIFT) 
      CLOSE(UNIT=15,STATUS='DELETE')
      RETURN
      END
