      SUBROUTINE DIAGEA(EAMAT, NEA, ICORE, MAXCOR, EIGVEC)
C
C  THE COMPLETE EA MATRIX IS DIAGONALIZED AND THE EIGENVALUES
C  AND EIGENVECTORS ARE PRINTED (IF EIGVEC = NONZERO)      
C
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION EAMAT
C
      DIMENSION ICORE(MAXCOR), EAMAT(NEA, NEA)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      I000 = 1
      I010 = I000 + NEA * IINTFP
      I020 = I010 + NEA * IINTFP
      I030 = I020 + NEA * NEA * IINTFP
      I040 = I030 + NEA * IINTFP
      I050 = I040 + NEA * IINTFP
C     
      CALL MN_GEEV(NEA, NEA, EAMAT, ICORE(I000), ICORE(I010),
     &             EIGVEC,ICORE(I020), NEA*NEA, IERR)
      IF (IERR.NE.0) WRITE(*,*) '@DIAGEA: Something went wrong in GEEV.'
C
C  NOW ANALYSE WHAT TO PRINT
C
      WRITE(6,*) ' REAL PART OF EIGENVALUES '
      CALL OUTPUT(ICORE(I000), 1, NEA,1,1, NEA,1,1)
      WRITE(6,*) ' IMAGINARY PART OF EIGENVALUES '
      CALL OUTPUT(ICORE(I010), 1, NEA, 1, 1,NEA, 1,1)
      IF (EIGVEC.NE.0) THEN
         CALL NORMALIZ(ICORE(I020), NEA)
         WRITE(6,*) '  EIGENVECTORS'
         CALL OUTPUT(ICORE(I020),1, NEA, 1, NEA, NEA, NEA,1)
      ENDIF
C
      RETURN
      END
