      SUBROUTINE PRINTW(ICORE, MAXCOR, IUHF)
C
      IMPLICIT INTEGER(A-Z)
      DIMENSION ICORE(MAXCOR)
C
      DIMENSION LISTW0(2,2)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
C
C     233: W(AbCd), ordered according to Ab;Cd
C
      LISTW0(1,1) = 231
      LISTW0(1,2) = 233
      LISTW0(2,1) = 233
      LISTW0(2,2) = 232
C
      DO 25 ISPIN = 1, 1 + iuhf
      DO 50 IMIXSPIN = 1, 1+IUHF
         LISTW = LISTW0(ISPIN, IMIXSPIN + 1 - IUHF)
         MSPIN = IMIXSPIN
         WRITE(6,*) ' PPPP INTEGRALS LISTW = ', LISTW
       DO 100 XIRREP=1,NIRREP
        IRREPW=XIRREP
        DISSYW=IRPDPD(IRREPW,ISYTYP(1,LISTW)) 
        NUMDSW=IRPDPD(IRREPW,ISYTYP(2,LISTW)) 
        CALL GETLST(ICORE,1, NUMDSW, 1, XIRREP, LISTW)
        WRITE(6,*) ' IRREP ', XIRREP
        CALL OUTPUT(ICORE,1, DISSYW, 1, NUMDSW, DISSYW, NUMDSW)
 100  CONTINUE
 50   continue
 25    continue
C
      RETURN
      END
