      SUBROUTINE SETZERO(IUHF, ISPIN, ICORE, MAXCOR, LS1OUT,
     $   LS2OUT)
C
C THE LISTS LS1OUT AND LS2OUT ARE PUT TO ZERO
C
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR), LS2OUT(2,2)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SINFO/ NS(8), SIRREP
C
      IF ((IUHF .EQ. 0) .AND. (ISPIN .NE. 1)) THEN
         RETURN
      ENDIF
C
      NS1 = NS(SIRREP)
      CALL ZERO(ICORE(1), NS1 * VRT(SIRREP,ISPIN) )
      CALL PUTLST(ICORE,1,1,1,ISPIN,LS1OUT)
C
      DO 50 KSPIN = 1, 1+IUHF
      IF (IUHF. NE.0) THEN
         MSPIN = KSPIN
      ELSE
         MSPIN = 3-ISPIN
      ENDIF
         LISTS2EX = LS2OUT(ISPIN, MSPIN)
         DO 100 XIRREP = 1 , NIRREP
            DISSYS = IRPDPD(XIRREP, ISYTYP(1, LISTS2EX))
            MIRREP = DIRPRD(SIRREP, XIRREP)
            NUMDSS = POP(MIRREP, MSPIN) * NS1
            IF ((NUMDSS * DISSYS) .GT. 0) THEN
               CALL ZERO(ICORE, DISSYS*NUMDSS)
               CALL PUTLST(ICORE, 1, NUMDSS, 1, XIRREP, LISTS2EX)
            ENDIF
 100     CONTINUE
 50   CONTINUE
C
      RETURN
      END
