      SUBROUTINE BDHBARIP(EIP,WBAR,FIJ,FIA,FAB,T2,F,NOCC,NVIR,NIP,NAO)
C
      IMPLICIT DOUBLE PRECISION (A-H, O-Z) 
C
      DIMENSION EIP(NIP,NIP)
      DIMENSION WBAR(NAO,NAO,NAO,NAO)
      DIMENSION FIJ(NOCC,NOCC)
      DIMENSION FIA(NOCC,NVIR)
      DIMENSION FAB(NVIR,NVIR)
      DIMENSION T2(NOCC,NOCC,NVIR,NVIR)
      DIMENSION F(NAO)
C
      DZERO = 0.D+0
C
      DO 5 I1=1, NAO
         DO 6 I2=1, NAO
            EIP(I1,I2)=DZERO
 6       CONTINUE
 5    CONTINUE
C
C HPP
      CALL DIAG1I(EIP,FIJ,F,NOCC,NIP,NAO)
C
C HQP
      CALL DIAG2I(EIP,WBAR,NVIR,NIP,NOCC,NAO)
C
C HPQ
      CALL DIAG3I(EIP,WBAR,NVIR,NIP,NOCC,NAO)
      CALL DIAG4I(EIP,FIA,NVIR,NIP,NOCC,NAO)
C
C HQQ
      CALL DIAG5I(EIP,WBAR,NVIR,NIP,NOCC,NAO)
      CALL DIAG6I(EIP,WBAR,NVIR,NIP,NOCC,NAO)
      CALL DIAG7I(EIP,WBAR,T2,NVIR,NIP,NOCC,NAO)
      CALL DIAG8I(EIP,FIJ,FAB,F,NVIR,NIP,NOCC,NAO)
C
      RETURN
      END
