      
     

      SUBROUTINE SYMETB(Z,N)
C
C THIS ROUTINE "SYMMETRIZES" A MATRIX Z IN THE SENSE THAT IT
C  PLACES THE VALUES OF Z(I,J; I<J) INTO Z(J,I).
C
CEND
      DOUBLE PRECISION Z(N,N)
      DO 10 I=2,N
*VOCL LOOP,NOVREC
CDIR$ IVDEP
       DO 20 J=1,I-1 
        Z(J,I)=Z(I,J)
20     CONTINUE
10    CONTINUE
      RETURN
      END
