      SUBROUTINE MO2OAO(ZMO,ZAO,EVEC,SCR,NBAS,ISPIN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*8 LABEL
      DIMENSION EVEC(NBAS,NBAS),ZMO(NBAS,NBAS),ZAO(NBAS,NBAS)
      DIMENSION SCR(NBAS,NBAS)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      IF(ISPIN.EQ.1)LABEL='EVCOAOXA'
      IF(ISPIN.EQ.2)LABEL='EVCOAOXB'
      CALL GETREC(20,'JOBARC',LABEL,IINTFP*NBAS*NBAS,EVEC)
      CALL MTRAN2(EVEC,NBAS)
      CALL MXM(ZMO,NBAS,EVEC,NBAS,SCR,NBAS)
      CALL MTRAN2(EVEC,NBAS)
      CALL MXM(EVEC,NBAS,SCR,NBAS,ZAO,NBAS)
      RETURN
      END
