      SUBROUTINE SYMMETW2(A,NUM)
C
C   THIS ROUTINE SYMMETRIZES A GIVEN MATRIX A
C
C     A(PQ) = ( A(PQ)+A(QP))
C
C   WHERE A IS A SYMMETRY PACKED MATRIX AND
C   NUM THE CORRESPONDING POPULATION VECTOR
C
C   THE SYMMETRIZATION IS HERE COMPLETELY DONE IN PLACE
C
CEND
C
C CODED AUGUST/90 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DIMENSION A(NUM,NUM)
C
C SYMMETRIZE FISRT HALF OF A
C
       DO 100 I=2,NUM
*VOCL LOOP,NOVREC
CDIR$ IVDEP
       DO 100 J=1,I-1
        A(I,J)=(A(I,J)+A(J,I))
100    CONTINUE
C
C FILL SECOND HALF OF A
C
       DO 200 I=2,NUM
*VOCL LOOP,NOVREC
CDIR$ IVDEP
       DO 200 J=1,I-1
        A(J,I)=A(I,J)
200    CONTINUE
C
      RETURN
      END
