      SUBROUTINE REDUCE(A,N,I,M)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      DIMENSION A(1)
C
      ISTART1=I*N+1 
      ISTART2=(I-1)*N+1
      LENGTH=(M-I)*N
C
c YAU : old
c     CALL ICOPY(LENGTH*IINTFP,A(ISTART1),1,A(ISTART2),1)
c YAU : new
      CALL DCOPY(LENGTH,A(ISTART1),1,A(ISTART2),1)
c YAU : end
C
      RETURN
      END
