      SUBROUTINE DP0SUM(DIPMN,DIPME,DIP0)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION DIPMN(3),DIPME(3),DIP0(3)
C
      COMMON/PERT/NTPERT,NPERT(8),IPERT(8),IXYZ(3),
     &            ISCHROTT(7)
      DATA AZERO /0.D0/
C
      DO 100 I=1,3
      IF (IXYZ(I).EQ.1) THEN
       DIP0(I)=DIPMN(I)+DIPME(I)
      ELSE
       DIP0(I)=AZERO
      END IF
  100 CONTINUE  
C
      CALL HEADER('Total dipole moment',-1) 
      CALL DP0PRI(DIP0) 
C
      OPEN(UNIT=80,FILE='DIPOL',STATUS='UNKNOWN',FORM='FORMATTED')
      REWIND(80)
      WRITE(80,1000) DIP0
1000  FORMAT(3F20.10)
      CLOSE(UNIT=80,STATUS='KEEP')
      RETURN
      END
