      SUBROUTINE GAABB2(NIRREP,NTYPE,TYPE,NBAS,IOFFL,
     &           MULT,NRCSH,KHKTSH,INDGEN,ISTBSH,
     &           ISHLD,NNIJ,IJADD,
     &           NSTSH,NENDSH,
     &           BUF,BUF1,BUCK,IBUCK,NREC)
C
C  GAABB2 PERFORMS THE SORT OF THE GAMMA ELEMENTS OF SYMMETRY TYPE
C  AABB. THIS IS THE OUT OF CORE VERSION.
C 
CEND
C
C  CODED DEC/90/JG
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER AND,OR,XOR
      PARAMETER (IBIT08 = 255)
      PARAMETER (MXBTCH=1000)
C
      INTEGER P, Q, R, S, PQ, RS, PQRS, RSPQ
      INTEGER TYPE
C
      DIMENSION NBAS(8),IOFFL(8) 
      DIMENSION TYPE(4,42,4)
      DIMENSION MULT(0:7),NRCSH(1),KHKTSH(1),INDGEN(1),ISTBSH(1)
      DIMENSION ISHLD(1),NNIJ(1),IJADD(1),NSTSH(8,1),NENDSH(8,1)
      DIMENSION BUF(1),BUF1(1),BUCK(1),IBUCK(1)
C
C COMMON /BATCH/ CONTAINS THE SORT INFORMATION
C
      COMMON/BATCH/NBATCH,LBUC,LBUC2,LASTAD(MXBTCH),
     &             ICOUNT(MXBTCH),ISTART(MXBTCH),
     &             NAD(MXBTCH),NSTART(MXBTCH),NEND(MXBTCH)
C
      COMMON/PTRFIL/JOBIN,JOBOUT,LUMC,LUSCR,LUDA,LUPSO,LUPAO
C
C  COMMON /MACHSP/ CONTAINS MACHINE DEPENDENT STUFF
C
      COMMON /MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C STATEMENT FUNCTIONS FOR PACKING, UNPACKING AND ADDRESSING 
C
      IBTAND(I,J) = AND(I,J)
      IBTSHL(I,J) = ISHFT(I,J)
      IBTSHR(I,J) = ISHFT(I,-J)
      IPART(I,J) = IBTAND(IBTSHR(I,8*(J-1)),IBIT08)
      ISHLL(I)   = IBTAND(I,IBIT08)
      ICONTR(I)  = IBTAND(IBTSHR(I,8),IBIT08)
      IANG(I)    = IBTAND(IBTSHR(I,16),IBIT08)
      JRREP(I)   = IBTAND(IBTSHR(I,24),IBIT08)
      ICR1(I,J,K,L) = NRCP*(NRCQ*(NRCR*(L-1)+K-1)+J-1)+I
      IAR1(I,J,K,L) = KHKTP*(KHKTQ*(KHKTR*(L-1)+K-1)+J-1)+I
      IRR1(I,J,K,L) = MULP*(MULQ*(MULR*(L)+K)+J)+I+1
      ICR2(I,J,K,L) = NRCR*(NRCS*(NRCP*(L-1)+K-1)+J-1)+I
      IAR2(I,J,K,L) = KHKTR*(KHKTS*(KHKTP*(L-1)+K-1)+J-1)+I
      IRR2(I,J,K,L) = MULR*(MULS*(MULP*(L)+K)+J)+I+1
      IADDRS(I,J,K) = NRCTOT*(MULTOT*(K-1)+J-1)+I
C
C  LOOP OVER ALL AABB SYMMETRY TYPES
C
        DO 100 IND=1,NTYPE
C
C  RESET THE COUNTER TO ZERO
C
         KCOUNT=0
C
C  DETERMINE THE IRREPS FOR THE CURRENT LOOP
C
         IRREP1=TYPE(2,IND,1)
         IRREP2=TYPE(2,IND,3)
C
C  DETERMINE THE NUMBER OF BASIS FUNCTIONS FOR THIS LOOP
C
         NBAS1=NBAS(IRREP1)
         NBAS2=NBAS(IRREP2)
C
C  DETERMINE OFFSETS FOR THE BASIS FUNCTIONS FOR THIS LOOP
C
         IOFFL1=IOFFL(IRREP1)
         IOFFL2=IOFFL(IRREP2)
C
C  LOOP OVER FIRST INDEX (P)
C
         DO 100 L1=IOFFL1+1,IOFFL1+NBAS1
C
C  GET PARAMETERS FOR THIS ORBITAL
C
          LAB1=INDGEN(L1)
          P=ISHLL(LAB1)
          MULP=MULT(ISTBSH(P))
          NRCP=NRCSH(P)
          KHKTP=KHKTSH(P)
          IP=ICONTR(LAB1)
          KP=IANG(LAB1)
          NP=JRREP(LAB1)
C
C  LOOP OVER SECOND INDEX (Q)
C
          DO 100 L2=IOFFL1+1,L1
C
C  GET PARAMETERS FOR THIS ORBITAL
C
           LAB2=INDGEN(L2)
           Q=ISHLL(LAB2)
           MULQ=MULT(ISTBSH(Q))
           NRCQ=NRCSH(Q)
           KHKTQ=KHKTSH(Q)
           IQ=ICONTR(LAB2)
           KQ=IANG(LAB2)
           NQ=JRREP(LAB2)
C
C  GET ADRESS OF SHELL COMBINATIONS P,Q
C
           PQ=(P*(P-1))/2+Q  
C
C  P IS ALWAYS GE Q
C
C
C GET ADRESS WHICH CORRESPONDS TO THE SHELLS PQ ON THE LEFT SIDE
C
           ISHLADPQ=0
           IF(PQ.NE.1) THEN 
            MAXPQ=PQ-1
            DO 301 M=1,MAXPQ
c             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M)
             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M+1)
301         CONTINUE
           ENDIF
c            ISHLADPQ=ISHLD(PQ)
C
C  PICK UP A LIST FROM THE AOGAM VERSION OF MOINTS
C  INCREMENT FIRST KCOUNT
C
           KCOUNT=KCOUNT+1
C
           CALL GETLST(BUF,KCOUNT,1,1,2,IND)
C
C EXPAND TRIANGULAR MATRIX R>S FOR FIXED P,Q TO FULL SQUARE
C
           CALL EXPND(BUF,BUF1,NBAS2)
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 200 L3=IOFFL2+1,IOFFL2+NBAS2
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP2,R) 
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
            IF(R.LE.P) THEN
C
             IF(R.EQ.P) NMAX4=NENDSH(IRREP2,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 300 L4=IOFFL2+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL2-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C GET BIN AND LOCATION INN CHAINING AREA FOR THIS SHELL
C
              DO 9001 IBATCH=1,NBATCH
               IF((PQRS.GE.NSTART(IBATCH)).AND.(PQRS.LE.NEND(IBATCH)))
     &            GO TO 9002 
9001          CONTINUE
               CALL ERREX
9002          CONTINUE
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR1(NRCP,NRCQ,NRCR,NRCS)
c              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,MULS-1)
              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR1(IP,IQ,IR,IS),
c     &             IRR1(NP,NQ,NR,NS),
     &             IRR1(NP,NQ,NR,0),
     &             IAR1(KP,KQ,KR,KS))
     &             -NAD(IBATCH)
C
              JCOUNT=ICOUNT(IBATCH)+1
              BUCK(ISTART(IBATCH)+JCOUNT)=BUF1(INDEX)
              IBUCK(ISTART(IBATCH)+JCOUNT)=ILOC
              ICOUNT(IBATCH)=JCOUNT
              IF(JCOUNT.EQ.LBUC2) THEN
               CALL WRTSRT(LUDA,BUCK(ISTART(IBATCH)+1),
     &                     IBUCK(ISTART(IBATCH)+1),
     &                     LASTAD(IBATCH),ICOUNT(IBATCH),
     &                     LBUC2,NREC)
              ENDIF
C

C  END OF S LOOP FOR P GT R CASE
C
300          CONTINUE
C
            ENDIF
            IF(R.GE.P) THEN
C
            NMAX4=NENDSH(IRREP2,R)
            NSTART4=IOFFL2+1
            IF(R.EQ.P) NSTART4=NSTSH(IRREP2,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 400 L4=NSTART4,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL2-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS R,S,P,Q
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C GET BIN AND LOCATION INN CHAINING AREA FOR THIS SHELL
C
              DO 9003 IBATCH=1,NBATCH
               IF((RSPQ.GE.NSTART(IBATCH)).AND.(RSPQ.LE.NEND(IBATCH)))
     &            GO TO 9004
9003          CONTINUE
               STOP 'GAABB 2'
9004          CONTINUE
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO 302 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
302           CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR2(NRCR,NRCS,NRCP,NRCQ)
c              MULTOT=IRR2(MULR-1,MULS-1,MULP-1,MULQ-1)
              MULTOT=IRR2(MULR-1,MULS-1,MULP-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR2(IR,IS,IP,IQ),
c     &             IRR2(NR,NS,NP,NQ),
     &             IRR2(NR,NS,NP,0),
     &             IAR2(KR,KS,KP,KQ))
     &             -NAD(IBATCH)
C
              JCOUNT=ICOUNT(IBATCH)+1
              BUCK(ISTART(IBATCH)+JCOUNT)=BUF1(INDEX)
              IBUCK(ISTART(IBATCH)+JCOUNT)=ILOC
              ICOUNT(IBATCH)=JCOUNT
              IF(JCOUNT.EQ.LBUC2) THEN
               CALL WRTSRT(LUDA,BUCK(ISTART(IBATCH)+1),
     &                     IBUCK(ISTART(IBATCH)+1),
     &                     LASTAD(IBATCH),ICOUNT(IBATCH),
     &                     LBUC2,NREC)
              ENDIF
C
C  END OF S LOOP FOR RS,PQ CASE
C
400         CONTINUE
C
            ENDIF
C
200        CONTINUE
C
C NOW TREAT AS WELL THE CASE P EQ Q AND L1 NE L2
C
            IF(P.EQ.Q.AND.L1.NE.L2) THEN
C
C REPEAT THE WHOLE PROCEDURE WITH L1 AND L2 INTERCHANGED
C
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 500 L3=IOFFL2+1,IOFFL2+NBAS2
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP2,R)
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
            IF(R.LE.P) THEN
C
             IF(R.EQ.P) NMAX4=NENDSH(IRREP2,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 600 L4=IOFFL2+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL2-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C GET BIN AND LOCATION INN CHAINING AREA FOR THIS SHELL
C
              DO 9005 IBATCH=1,NBATCH
               IF((PQRS.GE.NSTART(IBATCH)).AND.(PQRS.LE.NEND(IBATCH)))
     &            GO TO 9006
9005          CONTINUE
               CALL ERREX
9006          CONTINUE
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR1(NRCQ,NRCP,NRCR,NRCS)
c              MULTOT=IRR1(MULQ-1,MULP-1,MULR-1,MULS-1)
              MULTOT=IRR1(MULQ-1,MULP-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR1(IQ,IP,IR,IS),
c     &             IRR1(NQ,NP,NR,NS),
     &             IRR1(NQ,NP,NR,0),
     &             IAR1(KQ,KP,KR,KS))
     &             -NAD(IBATCH)
C
              JCOUNT=ICOUNT(IBATCH)+1
              BUCK(ISTART(IBATCH)+JCOUNT)=BUF1(INDEX)
              IBUCK(ISTART(IBATCH)+JCOUNT)=ILOC
              ICOUNT(IBATCH)=JCOUNT
              IF(JCOUNT.EQ.LBUC2) THEN
               CALL WRTSRT(LUDA,BUCK(ISTART(IBATCH)+1),
     &                     IBUCK(ISTART(IBATCH)+1),
     &                     LASTAD(IBATCH),ICOUNT(IBATCH),
     &                     LBUC2,NREC)
              ENDIF
C
600           CONTINUE
C
C  END OF S LOOP FOR RS,PQ CASE
C
700          CONTINUE
C
            ENDIF
            IF(R.GE.P) THEN
C
            NMAX4=NENDSH(IRREP2,R)
            NSTART4=IOFFL2+1
            IF(R.EQ.P) NSTART4=NSTSH(IRREP2,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 800 L4=NSTART4,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL2-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS R,S,P,Q
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C GET BIN AND LOCATION INN CHAINING AREA FOR THIS SHELL
C
              DO 9007 IBATCH=1,NBATCH
               IF((RSPQ.GE.NSTART(IBATCH)).AND.(RSPQ.LE.NEND(IBATCH)))
     &            GO TO 9008
9007          CONTINUE
               STOP 'GAABB 4'
9008          CONTINUE
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO 802 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
802           CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR2(NRCR,NRCS,NRCQ,NRCP)
c              MULTOT=IRR2(MULR-1,MULS-1,MULQ-1,MULP-1)
              MULTOT=IRR2(MULR-1,MULS-1,MULQ-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR2(IR,IS,IQ,IP),
c     &             IRR2(NR,NS,NQ,NP),
     &             IRR2(NR,NS,NQ,0),
     &             IAR2(KR,KS,KQ,KP))
     &             -NAD(IBATCH)
C
              JCOUNT=ICOUNT(IBATCH)+1
              BUCK(ISTART(IBATCH)+JCOUNT)=BUF1(INDEX)
              IBUCK(ISTART(IBATCH)+JCOUNT)=ILOC
              ICOUNT(IBATCH)=JCOUNT
              IF(JCOUNT.EQ.LBUC2) THEN
               CALL WRTSRT(LUDA,BUCK(ISTART(IBATCH)+1),
     &                     IBUCK(ISTART(IBATCH)+1),
     &                     LASTAD(IBATCH),ICOUNT(IBATCH),
     &                     LBUC2,NREC)
              ENDIF
C
C  END OF S LOOP FOR RS,PQ CASE
C
800         CONTINUE
C
            ENDIF
C
C  END R LOOP FOR P EQ Q AND L1 NE L2 CASE
C
500        CONTINUE
C
         ENDIF
C
100     CONTINUE
C
       RETURN
       END
