      SUBROUTINE GABCD1(NIRREP,NTYPE,TYPE,NBAS,IOFFL,
     &                  MULT,NRCSH,KHKTSH,INDGEN,ISTBSH,
     &                 ISHLD,NNIJ,IJADD,
     &                 NSTSH,NENDSH,
     &                 BUF,SORT)
C
C  GABCD1 PERFORMS THE SORT OF THE GAMMA ELEMENTS OF SYMMETRY TYPE
C  ABCD. THIS IS THE INCORE VERSION
C 
CEND
C
C  CODED DEC/90/JG
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER AND,OR,XOR
      PARAMETER (IBIT08 = 255)
      INTEGER P, Q, R, S, PQ, RS, PQRS
      INTEGER TYPE
C
      DIMENSION NBAS(8),IOFFL(8) 
      DIMENSION TYPE(4,42,4)
      DIMENSION MULT(0:7),NRCSH(1),KHKTSH(1),INDGEN(1),ISTBSH(1)
      DIMENSION ISHLD(1),NNIJ(1),IJADD(1),NSTSH(8,1),NENDSH(8,1)
      DIMENSION BUF(1),SORT(1)
C
C  COMMON /MACHSP/ CONTAINS MACHINE DEPENDENT STUFF
C
      COMMON /MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C STATEMENT FUNCTIONS FOR PACKING, UNPACKING AND ADDRESSING 
C
      IBTAND(I,J) = AND(I,J)
      IBTSHL(I,J) = ISHFT(I,J)
      IBTSHR(I,J) = ISHFT(I,-J)
      IPART(I,J) = IBTAND(IBTSHR(I,8*(J-1)),IBIT08)
      ISHLL(I)   = IBTAND(I,IBIT08)
      ICONTR(I)  = IBTAND(IBTSHR(I,8),IBIT08)
      IANG(I)    = IBTAND(IBTSHR(I,16),IBIT08)
      JRREP(I)   = IBTAND(IBTSHR(I,24),IBIT08)
      ICR1(I,J,K,L) = NRCP*(NRCQ*(NRCR*(L-1)+K-1)+J-1)+I
      IAR1(I,J,K,L) = KHKTP*(KHKTQ*(KHKTR*(L-1)+K-1)+J-1)+I
      IRR1(I,J,K,L) = MULP*(MULQ*(MULR*(L)+K)+J)+I+1
      ICR2(I,J,K,L) = NRCQ*(NRCP*(NRCS*(L-1)+K-1)+J-1)+I
      IAR2(I,J,K,L) = KHKTQ*(KHKTP*(KHKTS*(L-1)+K-1)+J-1)+I
      IRR2(I,J,K,L) = MULQ*(MULP*(MULS*(L)+K)+J)+I+1
      ICR3(I,J,K,L) = NRCP*(NRCQ*(NRCS*(L-1)+K-1)+J-1)+I
      IAR3(I,J,K,L) = KHKTP*(KHKTQ*(KHKTS*(L-1)+K-1)+J-1)+I
      IRR3(I,J,K,L) = MULP*(MULQ*(MULS*(L)+K)+J)+I+1
      ICR4(I,J,K,L) = NRCQ*(NRCP*(NRCR*(L-1)+K-1)+J-1)+I
      IAR4(I,J,K,L) = KHKTQ*(KHKTP*(KHKTR*(L-1)+K-1)+J-1)+I
      IRR4(I,J,K,L) = MULQ*(MULP*(MULR*(L)+K)+J)+I+1
      ICR5(I,J,K,L) = NRCR*(NRCS*(NRCP*(L-1)+K-1)+J-1)+I
      IAR5(I,J,K,L) = KHKTR*(KHKTS*(KHKTP*(L-1)+K-1)+J-1)+I
      IRR5(I,J,K,L) = MULR*(MULS*(MULP*(L)+K)+J)+I+1
      ICR6(I,J,K,L) = NRCS*(NRCR*(NRCQ*(L-1)+K-1)+J-1)+I
      IAR6(I,J,K,L) = KHKTS*(KHKTR*(KHKTQ*(L-1)+K-1)+J-1)+I
      IRR6(I,J,K,L) = MULS*(MULR*(MULQ*(L)+K)+J)+I+1
      ICR7(I,J,K,L) = NRCR*(NRCS*(NRCQ*(L-1)+K-1)+J-1)+I
      IAR7(I,J,K,L) = KHKTR*(KHKTS*(KHKTQ*(L-1)+K-1)+J-1)+I
      IRR7(I,J,K,L) = MULR*(MULS*(MULQ*(L)+K)+J)+I+1
      ICR8(I,J,K,L) = NRCS*(NRCR*(NRCP*(L-1)+K-1)+J-1)+I
      IAR8(I,J,K,L) = KHKTS*(KHKTR*(KHKTP*(L-1)+K-1)+J-1)+I
      IRR8(I,J,K,L) = MULS*(MULR*(MULP*(L)+K)+J)+I+1
      IADDRS(I,J,K) = NRCTOT*(MULTOT*(K-1)+J-1)+I
C
C  LOOP OVER ALL AABB SYMMETRY TYPES
C
        DO 100 IND=1,NTYPE
C
C  RESET THE COUNTER TO ZERO
C
         KCOUNT=0
C
C  DETERMINE THE IRREPS FOR THE CURRENT LOOP
C
         IRREP1=TYPE(4,IND,1)
         IRREP2=TYPE(4,IND,2)
         IRREP3=TYPE(4,IND,3)
         IRREP4=TYPE(4,IND,4)
C
C  DETERMINE THE NUMBER OF BASIS FUNCTIONS FOR THIS LOOP
C
         NBAS1=NBAS(IRREP1)
         NBAS2=NBAS(IRREP2)
         NBAS3=NBAS(IRREP3)
         NBAS4=NBAS(IRREP4)
C
C  DETERMINE OFFSETS FOR THE BASIS FUNCTIONS FOR THIS LOOP
C
         IOFFL1=IOFFL(IRREP1)
         IOFFL2=IOFFL(IRREP2)
         IOFFL3=IOFFL(IRREP3)
         IOFFL4=IOFFL(IRREP4)
C
C  LOOP OVER FIRST INDEX (P)
C
         DO 100 L1=IOFFL1+1,IOFFL1+NBAS1
C
C  GET PARAMETERS FOR THIS ORBITAL
C
          LAB1=INDGEN(L1)
          P=ISHLL(LAB1)
          MULP=MULT(ISTBSH(P))
          NRCP=NRCSH(P)
          KHKTP=KHKTSH(P)
          IP=ICONTR(LAB1)
          KP=IANG(LAB1)
          NP=JRREP(LAB1)
C
C  LOOP OVER SECOND INDEX (Q)
C
          DO 100 L2=IOFFL2+1,IOFFL2+NBAS2
C
C  GET PARAMETERS FOR THIS ORBITAL
C
           LAB2=INDGEN(L2)
           Q=ISHLL(LAB2)
           MULQ=MULT(ISTBSH(Q))
           NRCQ=NRCSH(Q)
           KHKTQ=KHKTSH(Q)
           IQ=ICONTR(LAB2)
           KQ=IANG(LAB2)
           NQ=JRREP(LAB2)
C
C  GET ADRESS OF SHELL COMBINATIONS P,Q
C
           IF(P.GE.Q) THEN
            PQ=(P*(P-1))/2+Q  
           ELSE
            PQ=(Q*(Q-1))/2+P
           ENDIF
C
C GET ADRESS WQHICH CORRESPONDS TO THE SHELLS PQ ON THE LEFT SIDE
C
           ISHLADPQ=0
           IF(PQ.NE.1) THEN 
            MAXPQ=PQ-1
            DO 301 M=1,MAXPQ
c             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M)
             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M+1)
301         CONTINUE
           ENDIF
c            ISHLADPQ=ISHLD(PQ)
C
C  PICK UP A LIST FROM THE AOGAM VERSION OF MOINTS
C  INCREMENT FIRST KCOUNT
C
           KCOUNT=KCOUNT+1
C
           CALL GETLST(BUF,KCOUNT,1,1,4,IND)
C
C  THE LOOP STRUCTURE IS SET UP AS FOLLOWS
C
C  1) P GE Q     P GE R 
C  2) P GE Q     R GE P
C  3) P GE Q     P GE S
C  4) P GE Q     S GE P
C  5) Q GE P     Q GE R
C  6) Q GE P     R GE Q
C  7) Q GE P     Q GE S 
C  8) Q GE P     S GE Q
C
           IF(P.GE.Q) THEN
C
C  LOOP 1) AND LOOP 2)
C
           DO 200 L3=IOFFL3+1,IOFFL3+NBAS3
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C  CASE 1) P GE Q, R GE S AND PQ GE RS
C
            IF(P.GE.R) THEN
C
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP4,R) 
            IF(R.EQ.P) NMAX4=NENDSH(IRREP4,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 300 L4=IOFFL4+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR1(NRCP,NRCQ,NRCR,NRCS)
c              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,MULS-1)
              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR1(IP,IQ,IR,IS),
c     &             IRR1(NP,NQ,NR,NS),
     &             IRR1(NP,NQ,NR,0),
     &             IAR1(KP,KQ,KR,KS))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
300          CONTINUE
C
             ENDIF
C
C  CASE 2)   P GE Q R GE S AND RS GE PQ
C
             IF(R.GE.P) THEN
C
             NMAX4=NENDSH(IRREP4,R)
             NMIN4=IOFFL4+1
C
             IF(P.EQ.R) NMIN4=NSTSH(IRREP4,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 350 L4=NMIN4,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO 352 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
352            CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR5(NRCR,NRCS,NRCP,NRCQ)
c              MULTOT=IRR5(MULR-1,MULS-1,MULP-1,MULQ-1)
              MULTOT=IRR5(MULR-1,MULS-1,MULP-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR5(IR,IS,IP,IQ),
c     &             IRR5(NR,NS,NP,NQ),
     &             IRR5(NR,NS,NP,0),
     &             IAR5(KR,KS,KP,KQ))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
350          CONTINUE
C
             ENDIF
C
200         CONTINUE
C
C  LOOP 3) AND LOOP 4)
C
           DO 1200 L4=IOFFL4+1,IOFFL4+NBAS4
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB4=INDGEN(L4)
            S=ISHLL(LAB4)
            MULS=MULT(ISTBSH(S))
            NRCS=NRCSH(S)
            KHKTS=KHKTSH(S)
            IS=ICONTR(LAB4)
            KS=IANG(LAB4)
            NS=JRREP(LAB4)
C
C LOOP 3) P GE Q S GE R AND PQ GE SR
C
            IF(P.GE.S) THEN
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX3=NENDSH(IRREP3,S)
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
             IF(P.EQ.S) NMAX3=NENDSH(IRREP3,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1300 L3=IOFFL3+1,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
              ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR3(NRCP,NRCQ,NRCS,NRCR)
c              MULTOT=IRR3(MULP-1,MULQ-1,MULS-1,MULR-1)
              MULTOT=IRR3(MULP-1,MULQ-1,MULS-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR3(IP,IQ,IS,IR),
c     &             IRR3(NP,NQ,NS,NR),
     &             IRR3(NP,NQ,NS,0),
     &             IAR3(KP,KQ,KS,KR))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1300         CONTINUE
C
             ENDIF
C
C  CASE 4)   P GE Q S GE R AND RS GE PQ
C
             IF(S.GE.P) THEN
C
             NMAX3=NENDSH(IRREP3,S)
             NMIN3=IOFFL3+1
C
             IF(P.EQ.S) NMIN3=NSTSH(IRREP3,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1350 L3=NMIN3,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO 1352 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
1352            CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR8(NRCS,NRCR,NRCP,NRCQ)
c              MULTOT=IRR8(MULS-1,MULR-1,MULP-1,MULQ-1)
              MULTOT=IRR8(MULS-1,MULR-1,MULP-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR8(IS,IR,IP,IQ),
c     &             IRR8(NS,NR,NP,NQ),
     &             IRR8(NS,NR,NP,0),
     &             IAR8(KS,KR,KP,KQ))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1350          CONTINUE
C
             ENDIF
C
1200        CONTINUE
            ENDIF
C
C NOW TREAT AS WELL THE CASE P LE Q 
C
            IF(P.LE.Q) THEN 
C
C  LOOP 5)  AND LOOP 6)
C
           DO 1500 L3=IOFFL3+1,IOFFL3+NBAS3
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C  CASE 5)  Q GE P R GE S AND QP GE RS
C
            IF(Q.GE.R) THEN
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP4,R) 
C
            IF(R.EQ.Q) NMAX4=NENDSH(IRREP4,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1600 L4=IOFFL4+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
              ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR4(NRCQ,NRCP,NRCR,NRCS)
c              MULTOT=IRR4(MULQ-1,MULP-1,MULR-1,MULS-1)
              MULTOT=IRR4(MULQ-1,MULP-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR4(IQ,IP,IR,IS),
c     &             IRR4(NQ,NP,NR,NS),
     &             IRR4(NQ,NP,NR,0),
     &             IAR4(KQ,KP,KR,KS))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1600          CONTINUE
C
              ENDIF
C
C  CASE 6)   Q GE P R GE S AND RS GE QP
C
             IF(Q.LE.R) THEN
C
             NMAX4=NENDSH(IRREP4,R)
             NMIN4=IOFFL4+1
C
             IF(Q.EQ.R) NMIN4=NSTSH(IRREP4,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1650 L4=NMIN4,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO 1652 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
1652            CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR7(NRCR,NRCS,NRCQ,NRCP)
c              MULTOT=IRR7(MULR-1,MULS-1,MULQ-1,MULP-1)
              MULTOT=IRR7(MULR-1,MULS-1,MULQ-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR7(IR,IS,IQ,IP),
c     &             IRR7(NR,NS,NQ,NP),
     &             IRR7(NR,NS,NQ,0),
     &             IAR7(KR,KS,KQ,KP))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1650          CONTINUE
              ENDIF
C
1500         CONTINUE
C
C LOOP 7) AND LOOP 8)
C
           DO 500 L4=IOFFL4+1,IOFFL4+NBAS4
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB4=INDGEN(L4)
            S=ISHLL(LAB4)
            MULS=MULT(ISTBSH(S))
            NRCS=NRCSH(S)
            KHKTS=KHKTSH(S)
            IS=ICONTR(LAB4)
            KS=IANG(LAB4)
            NS=JRREP(LAB4)
C
            IF(Q.GE.S) THEN
C
C CASE 7)  Q GE P S GE R AND QP GE SR
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX3=NENDSH(IRREP3,S)
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
             IF(Q.EQ.S) NMAX3=NENDSH(IRREP3,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 600 L3=IOFFL3+1,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR2(NRCQ,NRCP,NRCS,NRCR)
c              MULTOT=IRR2(MULQ-1,MULP-1,MULS-1,MULR-1)
              MULTOT=IRR2(MULQ-1,MULP-1,MULS-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR2(IQ,IP,IS,IR),
c     &             IRR2(NQ,NP,NS,NR),
     &             IRR2(NQ,NP,NS,0),
     &             IAR2(KQ,KP,KS,KR))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
600         CONTINUE
C
            ENDIF
C
C  CASE 8)  Q GE P S GE R AND SR GE PQ
C
             IF(S.GE.Q) THEN
C
             NMAX3=NENDSH(IRREP3,S)
             NMIN3=IOFFL3+1
C
             IF(Q.EQ.S) NMIN3=NSTSH(IRREP3,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 650 L3=NMIN3,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL4)+(L3-IOFFL3-1)*NBAS4
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              RSPQ=(RS*(RS-1))/2+PQ
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
              ISHLADRS=0
              IF(RS.NE.1) THEN
               MAXRS=RS-1
               DO6 52 M=1,MAXRS
c                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M)
                ISHLADRS=ISHLADRS+NNIJ(M)*IJADD(M+1)
652            CONTINUE
              ENDIF
c              ISHLAD=ISHLADRS
c              IF(PQ.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(RS)*IJADD(PQ-1)
c              ENDIF
               ISHLAD=ISHLADRS+NNIJ(RS)*IJADD(PQ)
c               ISHLAD=ISHLD(RS)+NNIJ(RS)*IJADD(PQ)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR6(NRCS,NRCR,NRCQ,NRCP)
c              MULTOT=IRR6(MULS-1,MULR-1,MULQ-1,MULP-1)
              MULTOT=IRR6(MULS-1,MULR-1,MULQ-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR6(IS,IR,IQ,IP),
c     &             IRR6(NS,NR,NQ,NP),
     &             IRR6(NS,NR,NQ,0),
     &             IAR6(KS,KR,KQ,KP))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
650          CONTINUE
C
             ENDIF
C
500        CONTINUE
C
         ENDIF
C
100     CONTINUE
C
       RETURN
       END
