      SUBROUTINE SYTRAA(GAMMA,CV,CO,NAO,NV,NO,BUF,RESULT,IACC)
C
C THIS ROUTINE PERFORMS THE TRANSFORMATION
C
C                                       + 
C                Q(XX) = C(X,A) Z(A,I) C (X,I) 
C
C
C USED IN TRANSFORMING THE T2 VECTOR TO THE ATOMIC ORBITAL BASIS
C
C THE RESULT IS RETURNED IN VECTOR RESULT, AND BUF IS A SCRATCH
C  VECTOR OF LENGTH NAOA*NAOB.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION CV(NAO*NV),CO(NO*NAO),GAMMA(NV*NO),BUF(1)
      DIMENSION RESULT(NAO*NAO)
C
      DATA ZILCH /0.0/
      DATA ONE   /1.0/
C
      IF(IACC.EQ.0)CALL ZERO(RESULT,NAO*NAO)
C
      IF(MIN(NV,NO).NE.0)THEN
       CALL XGEMM('N','N',NAO,NO,NV,ONE,CV,NAO,GAMMA,NV,
     &            ZILCH,BUF,NAO)
       CALL XGEMM('N','T',NAO,NAO,NO,ONE,BUF,NAO,CO,NAO,
     &            ONE,RESULT,NAO)
      ENDIF
C
      RETURN
      END
