
      SUBROUTINE PCCD_FMECONT(ICORE,MAXCOR,IUHF,ISPIN)
C
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,ONEM,ZILCH
      DIMENSION ICORE(MAXCOR)
      COMMON /INFO/ NOCA,NOCB,NVRTA,NVRTB
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      DATA ONE /1.0D0/ 
      DATA ONEM /-1.0D0/
      DATA ZILCH /0.0D0/

      LISTTB=35+ISPIN
      IF(IUHF.EQ.0)LISTTB=37
      LISTF =93

      NLENT1=IRPDPD(1,8+ISPIN)
      NLENFA=IRPDPD(1,8+ISPIN)
      NLENFB=IRPDPD(1,11-ISPIN)
C
      I000=1
      I010=I000+NLENT1*IINTFP
      IF(IUHF.EQ.0)THEN
       I020=I010
      ELSE
       I020=I010+NLENFA*IINTFP
      ENDIF
      I030=I020+NLENFB*IINTFP
      CALL GETLST(ICORE(I010),1,1,1,ISPIN,LISTF)

      IF(IUHF.NE.0)CALL GETLST(ICORE(I020),1,1,1,3-ISPIN,LISTF)
      NTDSZB=IRPDPD(1,ISYTYP(1,LISTTB))
      NTDISB=IRPDPD(1,ISYTYP(2,LISTTB))

      I040=I030+NTDSZB*NTDISB*IINTFP
      IF(I040.GT.MAXCOR)CALL INSMEM('MAKFME',I040,MAXCOR)
      CALL ZERO(ICORE(I000),NLENT1)
      I040=I030+NTDSZB*NTDISB*IINTFP
      IF(I040.GT.MAXCOR)CALL INSMEM('MAKFME',I040,MAXCOR)
        CALL GETLST(ICORE(I030),1,NTDISB,1,1,LISTTB)
        CALL XGEMM('N','N',1,NLENT1,NLENFB,ONE,ICORE(I020),
     &            1,ICORE(I030),NTDSZB,ONE,ICORE(I000),
     &            1)
20    CONTINUE
      CALL UPDAT1(ICORE(I000),ICORE(I010),NLENT1,2+ISPIN,90)
      RETURN
      END
