      SUBROUTINE PCCD_FEACONT(ICORE,MAXCOR,IUHF)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,DISSYT,DISSYZ,POP,VRT
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWO
      COMMON /SYM/ POP(8,2),VRT(8,2),NTAA,NTBB,
     &             NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON /FLAGS/ IFLAGS(100)

      DATA ONE,ONEM,HALFM /1.0D0,-1.0D0,-0.5D0/
C
      NFAA=NF2AA
      NFBB=NF2BB
      I0AA=MAXCOR+1-NFAA*IINTFP
      MXCOR=MAXCOR-NFAA*IINTFP

      IF(IUHF.EQ.0) THEN
       I0BB=I0AA
      ELSE
       I0BB=I0AA-NFBB*IINTFP
       MXCOR=MXCOR-NFBB*IINTFP
      ENDIF

      CALL GETLST(ICORE(I0AA),1,1,1,1,92)
      IF(IUHF.EQ.1) THEN
        CALL GETLST(ICORE(I0BB),1,1,1,2,92)
      ENDIF

      LISTT=46
      LISTZ=63
      DO 200 IRREP=1,NIRREP

        DISSYZ=IRPDPD(IRREP,ISYTYP(1,LISTZ))
        NUMSYZ=IRPDPD(IRREP,ISYTYP(2,LISTZ))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        I001=1
        I002=I001+IINTFP*NUMSYT*DISSYT
        I003=I002+IINTFP*NUMSYZ*DISSYZ
        IF(MIN(NUMSYT,NUMSYZ,DISSYT,DISSYZ).NE.0) THEN
         I004=I003+IINTFP*MAX(NUMSYT,NUMSYZ,DISSYZ,DISSYT)*3
         IF(I004.LT.MXCOR) THEN
         CALL PCCD_FEAAB1(ICORE(I001),ICORE(I002),ICORE(I002),
     &                    ICORE(I001),ICORE(I0AA),ICORE(I0BB),
     &                    POP(1,1),POP(1,2),VRT(1,1),VRT(1,2),DISSYT,
     &                    DISSYZ,NUMSYT,NUMSYZ,NFAA,NFBB,
     &                    LISTT,LISTZ,IRREP,IUHF,ICORE(I003))
        ELSE
        CALL INSMEM("PDCC_FEACONT",I004,MAXCOR)
        ENDIF
       ENDIF
200   CONTINUE
      RETURN
      END
