










      SUBROUTINE PCCD_TENER(IRREP,NLIST,EAB,NUMSYT,DISSYT,T2,
     +                      W,W1,POP,NIRREP)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DISSYT,POP
      DIMENSION T2(DISSYT,NUMSYT),W(DISSYT,NUMSYT)
      DIMENSION W1(DISSYT*NUMSYT)
      DIMENSION POP(8)

      DATA QUART,HALF,ONE,TWO /0.25D0,0.50D0,1.0D0,2.0D0/

      CALL GETLST(W,1,NUMSYT,2,IRREP,16)
      CALL SPINAD1(IRREP,POP,DISSYT,W,W1,W1(1+DISSYT))
      CALL GETLST(T2,1,NUMSYT,1,IRREP,NLIST)

      EAB=DDOT(NUMSYT*DISSYT,T2,1,W,1)
      EAB=HALF*EAB

      RETURN
      END
