
      SUBROUTINE PCCD_NEWT2(ICORE,MAXCOR,IUHF)

      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ELAST,FACT
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/ POP1(8),POP2(8),VRT1(8),VRT2(8),NTAA,NTBB,NF1AA,
     &             NF1BB,NF2AA,NF2BB

      I000=1
      LSTDEN=50
      LSTINC=63
      DO IRREP=1,NIRREP
         NDSSYM_T2=IRPDPD(IRREP,ISYTYP(2,LSTINC))
         DISSYM_T2=IRPDPD(IRREP,ISYTYP(1,LSTINC))
         NDSSYM_D2=IRPDPD(IRREP,ISYTYP(2,LSTDEN))
         DISSYM_D2=IRPDPD(IRREP,ISYTYP(1,LSTDEN))
  
         NSIZE_T2=NDSSYM_T2*DISSYM_T2
         NSIZE_D2=NDSSYM_D2*DISSYM_D2

         I010=I000+NSIZE_T2*IINTFP
         I020=I010+NSIZE_D2*IINTFP
         I030=I020+NSIZE_T2*IINTFP
         IEND=I030
         IF(IEND.GT.MAXCOR)CALL INSMEM('PCCD_NEWT2',IEND,MAXCOR)
         LEFT=MAXCOR - IEND 

         CALL GETLST(ICORE,1,NDSSYM_T2,1,IRREP,LSTINC)
         CALL GETLST(ICORE(I010),1,NDSSYM_D2,1,IRREP,LSTDEN)
         CALL VECPRD(ICORE(I000),ICORE(I010),ICORE(I000),NSIZE_T2)

         CALL PUTLST(ICORE(I000),1,NDSSYM_T2,1,IRREP,LSTINC)
      ENDDO

      RETURN
      END
