
      SUBROUTINE PCCD_AOLADLST(IUHF,LISTFLAG,IRREPX)
      IMPLICIT INTEGER (A-Z)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/AOSYM/IAOPOP(8),IOFFAO(8),IOFFV(8,2),IOFFO(8,2),
     &             IRPDPDAO(8),IRPDPDAOS(8),ISTART(8,8),ISTARTMO(8,3)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
C
      IF(LISTFLAG.EQ.0)RETURN
C
      CALL GETAOINF(IUHF,IRREPX)
      call aces_io_remove(52,'MOABCD')

      IMOD=0
      ISPIN=3
      
       CALL INIPCK4(1,IRPDPDAO,IRPDPD(1,ISYTYP(2,43+ISPIN)),
     &              243+ISPIN,IMOD,0,0)
       CALL INIPCK4(1,IRPDPDAO,IRPDPD(1,ISYTYP(2,43+ISPIN)),
     &              260+ISPIN,IMOD,0,0)
       IF(LISTFLAG.EQ.2) THEN
        CALL INIPCK4(1,IRPDPDAO,IRPDPD(1,ISYTYP(2,43+ISPIN)),
     &               60+ISPIN,IMOD,0,0)
       ENDIF  
C
      RETURN
      END
