      SUBROUTINE RMD314(T3,D3,LEN,DIJK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER ABC
      DIMENSION T3(LEN),D3(LEN)
C
C     THIS ROUTINE REMOVES THE DENOMINATOR FROM D3T3 TO GET PURE
C     T3 AMPLITUDES.
C
      DO   10 ABC=1,LEN
      T3(ABC) = T3(ABC) / (DIJK - D3(ABC))
   10 CONTINUE
      RETURN
      END
