      SUBROUTINE PCCD_DIISLST(IRREPX,IUHF,SINGLE,SIDE)

      IMPLICIT INTEGER (A-Z)
      LOGICAL SINGLE
      CHARACTER*1 SIDE
      COMMON/FLAGS/IFLAGS(100)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
      COMMON/DIISDAT1/SIZE,NDIMR,IDIMR
C
      NDIMR = 1
      IDIMR = 1
      IF (SIDE .EQ. "L") RETURN
      MAXDIM=IFLAGS(12)
      IF(SINGLE)THEN
        SIZE=IRPDPD(IRREPX,9)+IUHF*IRPDPD(IRREPX,10)
      ELSE
        SIZE=0
      ENDIF
      ISPIN=3 
      SIZE=SIZE+IDSYMSZ(IRREPX,ISYTYP(1,60+ISPIN),ISYTYP(2,60+ISPIN))
      CALL UPDMOI(MAXDIM,SIZE,1,70,0,0)
      CALL UPDMOI(MAXDIM,SIZE,2,70,0,0)

      RETURN
      END
