      SUBROUTINE  PCCD_FORMV1(ICORE,MAXCOR,IUHF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,DISSYL,DISSYT,POP1,POP2,VRT1,VRT2
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYM/ POP1(8),POP2(8),VRT1(8),VRT2(8),NTAA,NTBB,
     &             NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
      MXCOR=MAXCOR
      LISTT=46
      LISTL=146

      DO 110 IRREP=1,NIRREP
C
        DISSYL=IRPDPD(IRREP,ISYTYP(1,LISTL))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYL=IRPDPD(IRREP,ISYTYP(2,LISTL))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        I001=1
        I002=I001+IINTFP*NUMSYL*DISSYL
        I003=I002+IINTFP*NUMSYT*DISSYT
        IF(MIN(NUMSYT,NUMSYL,DISSYT,DISSYL).NE.0)THEN
         I004=I003+IINTFP*NUMSYT*NUMSYL
         I005=I004+IINTFP*MAX(DISSYT,DISSYL)
         IF(I005.LT.MXCOR) THEN

          CALL PCCD_V1ALL(ICORE(I001),ICORE(I002),ICORE(I003),
     &                    3,.FALSE.,.FALSE.,DISSYL,DISSYT,NUMSYL,
     &                    NUMSYT,LISTL,LISTT,IRREP,ICORE(I005))
         ELSE
          CALL INSMEM('V1ALL ',I005,MXCOR)
         ENDIF
        ELSE
        ENDIF
110    CONTINUE
C
      RETURN
      END
