      SUBROUTINE PCCD_G1X2AB(T2,Z2,T,Z,FEAAA,FEABB,POP1,POP2,VRT1,
     &                        VRT2,DISSYT,DISSYZ,NUMSYT,NUMSYZ,
     &                        NFSIZA,NFSIZB,LISTT,LISTZ,IRREP,
     &                        IUHF,TMP)
       IMPLICIT DOUBLE PRECISION(A-H,O-Z)

       INTEGER DISSYT,DISSYZ,DIRPRD,POP1,VRT1,POP2,VRT2
       DIMENSION T2(DISSYT,NUMSYT),Z2(DISSYZ,NUMSYZ),FEAAA(NFSIZA),
     &           FEABB(NFSIZB),T(NUMSYT,DISSYT),Z(NUMSYZ,DISSYZ)
       DIMENSION TMP(1),POP1(8),POP2(8),VRT1(8),VRT2(8)
       COMMON/SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
C
       DATA AZERO,ONE,ONEM /0.0D0,1.0D0,-1.0D0/

       CALL GETLST(T2,1,NUMSYT,2,IRREP,LISTT)
       CALL TRANSP(T2,T,NUMSYT,DISSYT)
       CALL ZERO(Z,NUMSYZ*DISSYZ)

       JOFF=1
       IOFF=1

       DO 90 IRREPJ=1,NIRREP
        NVRTJ=VRT2(IRREPJ)
        IRREPI=DIRPRD(IRREPJ,IRREP)
        NVRTI=VRT1(IRREPI)
        IF(MIN(NVRTJ,NVRTI).NE.0) THEN
        CALL XGEMM('N','T',NUMSYT*NVRTI,NVRTJ,NVRTJ,ONE,T(1,JOFF),
     &             NVRTI*NUMSYT,FEABB(IOFF),NVRTJ,
     &             AZERO,Z(1,JOFF),NVRTI*NUMSYZ)
        ENDIF
        JOFF=JOFF+NVRTJ*NVRTI
        IOFF=IOFF+NVRTJ*NVRTJ
90      CONTINUE
    
       CALL TRANSP(Z,Z2,DISSYZ,NUMSYZ)
       CALL GETLST(T2,1,NUMSYZ,1,IRREP,LISTZ)
       CALL VADD(T2,T2,Z2,NUMSYZ*DISSYZ,ONE)
       CALL SYMTR1(IRREP,POP1,POP2,DISSYZ,Z2,TMP,TMP(1+DISSYZ),
     &             TMP(1+2*DISSYZ))
       CALL SYMTR3(IRREP,VRT1,VRT2,DISSYZ,NUMSYZ,Z2,TMP,
     &             TMP(1+NUMSYZ),TMP(1+2*NUMSYZ))
       CALL VADD(Z2,Z2,T2,NUMSYZ*DISSYZ,ONE)
       CALL PUTLST(Z2,1,NUMSYZ,1,IRREP,LISTZ)

      RETURN
      END
