      SUBROUTINE PCCD_V1INX2(ICORE,MAXCOR,IUHF)

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,DISSYW,DISSYT
      INTEGER POP,VRT
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYM/POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NJUNK(18)
C
      LISTT=46
      LISTW=153
      DO 110 IRREP=1,NIRREP

        DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        I000=1
        I010=I000+NUMSYW*DISSYW*IINTFP
        I020=I010+NUMSYT*DISSYT*IINTFP
        I030=I020+NUMSYT*DISSYT*IINTFP
        IF(MIN(NUMSYT,NUMSYW,DISSYT,DISSYW).NE.0)THEN
         IF(I030.LT.MAXCOR)THEN
          CALL PCCD_V1X2AB(ICORE(I000),ICORE(I010),ICORE(I020),DISSYW,
     &                     NUMSYW,DISSYT,NUMSYT,LISTW,LISTT,IRREP,
     &                     IUHF)
C
         ELSE
          CALL INSMEM('PCCD_V1X2AB',I030,MXCOR)
         ENDIF
        ENDIF

110   CONTINUE

      RETURN
      END
