      SUBROUTINE PCCD_Q2AB(W,T,Z,POP1,POP2,VRT1,VRT2,NOCCSQ,DISSYW,
     &                     DISSYT,NUMSYW,NUMSYT,IRREP,TMP,FACT,IUHF)

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DISSYT, DISSYW, DIRPRD,POP1,POP2,VRT1,VRT2
      DIMENSION W(DISSYW,NUMSYW),T(DISSYT,NUMSYT),Z(NOCCSQ)
      DIMENSION TMP(1)
      DIMENSION POP1(8),POP2(8),T1A(1),T1B(1),VRT1(8),VRT2(8) 
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),DIRPRD(8,8)

      DATA ONE,ONEM,TWO /1.0D0,-1.D0,2.D0/,HALF /0.5D0/

      CALL GETLST(W,1,NUMSYW,2,IRREP,16)

      IF(IUHF.EQ.0) THEN
       CALL SPINAD1(IRREP,POP1,DISSYW,W,TMP,TMP(1+DISSYW))
      ENDIF
C
      CALL GETLST(T,1,NUMSYT,1,IRREP,46)

      JOFF=1
      IOFF=1
      DO 90 IRREPI=1,NIRREP
         NOCCI=POP1(IRREPI)
         IF(NOCCI.EQ.0) GO TO 90

         IRREPJ=DIRPRD(IRREP,IRREPI)
         NOCCJ=POP2(IRREPJ)

         IF(NOCCJ.EQ.0) GO TO 80
            CALL XGEMM('T','N',NOCCI,NOCCI,DISSYW*NOCCJ,FACT,
     &                 W(1,JOFF),NOCCJ*DISSYW,T(1,JOFF),      
     &                 NOCCJ*DISSYW,ONE,Z(IOFF),NOCCI)
            JOFF=JOFF+NOCCJ*NOCCI
80       CONTINUE
         IOFF=IOFF+POP1(IRREPI)**2
90    CONTINUE

      RETURN
      END
