      SUBROUTINE PCCD_RESET_RNG(ICORE,MAXCOR,IUHF)
C
C THIS ROUTINE RESETS THE SPIN-ADAPTED RING LISTS.  ON ENTRY, THE FOLLOWING
C  LISTS ARE STORED:
C  
C        2  * ABAB - ABBA   ON  LIST 56
C              ABBA         ON  LIST 58
C
C THE PURPOSE OF THIS ROUTINE IS TO WRITE THE FOLLOWING LISTS
C
C              ABAB         ON  LIST 56
C              ABBA         ON  LIST 58
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION ONE,HALF,ONEM
C
      DIMENSION ICORE(MAXCOR)
C
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      DATA HALF /0.5D0/
      DATA ONEM /-1.0D0/
      DATA ONE /1.0D0/
C
      ISIZE=ISYMSZ(ISYTYP(1,56),ISYTYP(2,56))
      I000=1
      I010=I000+IINTFP*ISIZE
      I020=I010+IINTFP*ISIZE
      CALL GETALL(ICORE(I000),ISIZE,1,56)
      CALL GETALL(ICORE(I010),ISIZE,1,58)
      CALL SAXPY (ISIZE,ONE,ICORE(I010),1,ICORE(I000),1)
      CALL SSCAL (ISIZE,HALF,ICORE(I000),1)
      CALL PUTALL(ICORE(I000),ISIZE,1,56)
      CALL SAXPY (ISIZE,ONEM,ICORE(I000),1,ICORE(I010),1)
      CALL PUTALL(ICORE(I010),ISIZE,1,54)
C
      RETURN
      END
