      SUBROUTINE OSL2(ICORE,MAXCOR,IUHF)
C
C     THIS ROUTINE DRIVES THE CALCULATION OF THE CONTRIBUTIONS TYPE3
C     (I.E. DERIVATIVE OF THE RENORMALIZATION TERM WITH UNMODIFIED H(EFF).)
C
CEND
C
CPROGRAMED PS AUG 93
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,DISSYT
C
      DIMENSION ICORE(MAXCOR)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
      INTEGER FSDPDAN,FSDPDNA,FSDPDAA,FSDPDIN,FSDPDNI,FSDPDII,FSDPDAI,
     $   FSDPDIA
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
C
      COMMON /ACTIRR/ IRREPOA,IRREPOB,IRREPVA,IRREPVB
C
      COMMON /FLAGS/ IFLAGS(100)
      integer pop1,pop2,vrt1,vrt2
      common /sym/ pop1(8),pop2(8),vrt1(8),vrt2(8),nt(2),
     &             nf1aa,nf1bb,nf2aa,nf2bb
      DATA ONE,ONEM,ZILCH/1.D0,-1.D0,0.D0/
C
C
C     FIRST GET THE 'EFFECTIVE HAMILTONIAN ELEMENT'
C
      CALL GETREC(20,'JOBARC','OSHEFFOF',IINTFP,W)
C     
C     CONTRIBUTIONS TO L1
C
      CALL OSL1AI(ICORE,MAXCOR,IUHF,W)
      CALL OSL1IA(ICORE,MAXCOR,IUHF,W)
      CALL OSL1II1(ICORE,MAXCOR,IUHF,W)
      CALL OSL1II2(ICORE,MAXCOR,IUHF,W)
C
C     CONTRIBUTIONS TO L2
C
      CALL OSL2AAIA(ICORE,MAXCOR,IUHF,W)
      CALL OSL2IAAA(ICORE,MAXCOR,IUHF,W)
      CALL OSL2AAII(ICORE,MAXCOR,IUHF,W)
      CALL OSL2IIAA(ICORE,MAXCOR,IUHF,W)
      CALL OSL2AIAI1(ICORE,MAXCOR,IUHF,W)
      CALL OSL2AIAI2(ICORE,MAXCOR,IUHF,W)
      CALL OSL2AIAI3(ICORE,MAXCOR,IUHF,W)
      CALL OSL2IIAI(ICORE,MAXCOR,IUHF,W)
      CALL OSL2AIII(ICORE,MAXCOR,IUHF,W)
      RETURN
      END
