      SUBROUTINE MATMULt(A,B,C,NI,NJ,NK,IACC,IFUN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(NI,NK),B(NK,NJ),C(NI,NJ)
      DATA ONE,ZERO,MONE/1.0D+0,0.0D+0,-1.0D+0/
C
C   CALL MAX BOARD MATRIX MULTIPLY SUBROUTINE.
C
C     THE ARGUMENT TOL IS NOT USED. IN THE VAX VERSION IT
C     IS A TOLERANCE FOR SAXPYS.
C
C     DEPENDING ON THE VALUES OF IACC AND IFUN, FOUR SORTS
C     OF MATRIX MULTIPLICATIONS MAY BE CARRIED OUT :
C
C     IACC=  0, IFUN= 0    C = C + A*B
C     IACC=  0, IFUN><0    C = C - A*B
C     IACC=><0, IFUN= 0    C =     A*B
C     IACC=><0, IFUN><0    C =   - A*B
C     
      call ienter(16)
      IF (IACC.EQ.0.AND.IFUN.EQ.0) THEN
      ALPHA=ONE
      BETA=ONE
      ELSE
      IF (IACC.EQ.0.AND.IFUN.NE.0) THEN
      ALPHA=MONE
      BETA=ONE
      ELSE
      IF (IACC.NE.0.AND.IFUN.EQ.0) THEN
      ALPHA=ONE
      BETA=ZERO
      ELSE
      ALPHA=MONE
      BETA=ZERO
      ENDIF
      ENDIF
      ENDIF
c      CALL SGEMM('N','N',NI,NJ,NK,ALPHA,A,NI,B,NK,BETA,C,NI)
      CALL XGEMM('N','T',NI,Nj,Nk,ALPHA,A,NI,B,Nj,BETA,C,NI)
C FPS 164
C      CALL PMMUL(A,B,C,NI,NK,NI,NI,NJ,NK,IACC,IFUN,8192,IERR)
      call iexit(16)
      RETURN
      END
      SUBROUTINE tMATMUL(A,B,C,NI,NJ,NK,IACC,IFUN)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION A(NI,NK),B(NK,NJ),C(NI,NJ)
      DATA ONE,ZERO,MONE/1.0D+0,0.0D+0,-1.0D+0/
C
C   CALL MAX BOARD MATRIX MULTIPLY SUBROUTINE.
C
C     THE ARGUMENT TOL IS NOT USED. IN THE VAX VERSION IT
C     IS A TOLERANCE FOR SAXPYS.
C
C     DEPENDING ON THE VALUES OF IACC AND IFUN, FOUR SORTS
C     OF MATRIX MULTIPLICATIONS MAY BE CARRIED OUT :
C
C     IACC=  0, IFUN= 0    C = C + A*B
C     IACC=  0, IFUN><0    C = C - A*B
C     IACC=><0, IFUN= 0    C =     A*B
C     IACC=><0, IFUN><0    C =   - A*B
C     
      call ienter(16)
      IF (IACC.EQ.0.AND.IFUN.EQ.0) THEN
      ALPHA=ONE
      BETA=ONE
      ELSE
      IF (IACC.EQ.0.AND.IFUN.NE.0) THEN
      ALPHA=MONE
      BETA=ONE
      ELSE
      IF (IACC.NE.0.AND.IFUN.EQ.0) THEN
      ALPHA=ONE
      BETA=ZERO
      ELSE
      ALPHA=MONE
      BETA=ZERO
      ENDIF
      ENDIF
      ENDIF
c      CALL SGEMM('N','N',NI,NJ,NK,ALPHA,A,NI,B,NK,BETA,C,NI)
      CALL XGEMM('T','N',NI,Nj,Nk,ALPHA,A,Nk,B,Nk,BETA,C,NI)
C FPS 164
C      CALL PMMUL(A,B,C,NI,NK,NI,NI,NJ,NK,IACC,IFUN,8192,IERR)
      call iexit(16)
      RETURN
      END
