
      SUBROUTINE AOSYMVC2(IAOMAP,IAOSYM,NAO)
C
C CALCULATE A "SYMMETRY VECTOR" FOR THE XX AO DISTRIBUTIONS.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION IAOMAP(NAO*NAO),IAOSYM(NAO)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON/AOSYM/IAOPOP(8),IOFFAO(8),IOFFV(8,2),IOFFO(8,2),
     &             IRPDPDAO(8),IRPDPDAOS(8),ISTART(8,8),ISTARTMO(8,3)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      INDX(I,J,N)=I+(J-1)*N
C
      IIN=0
      NTOT=0
c      NUMDIS=0
      DO 105 NIR=1,NIRREP
       NUMDIS=0
       DO 110 I=1,NAO
       DO 115 J=1,NAO
        NUMDIS=NUMDIS+1
        IRXXXI=IAOSYM(I)
        IRXXXJ=IAOSYM(J)
        IR=DIRPRD(IRXXXI,IRXXXJ)
        IF(IR.EQ.NIR)THEN
         IIN=IIN+1
         IAOMAP(IIN)=NUMDIS
        ENDIF
115     CONTINUE
110    CONTINUE
c       NUMIRR(NIR)=IIN-NTOT
       NTOT=IIN
105   CONTINUE
C
      RETURN
      END
