
      SUBROUTINE L1T1H4(H,DISSYH,NUMSYH,T1,FACT,ISPIN1,ISPIN2,
     &                  LIST1,LIST2)
C
C     THIS ROUTINE FORMS THE L1*T1 CONTRIBUTION TO H4(IA,JB)
C
C      H(NF,IA) =  T(I,A) L(N,F) 
C
C    STORAGE MODE OF H :   F,N ; A,I
C
C     THIS TERM IS REQUIRED ONLY FOR QCISD AND CCSD
C
C     THERE ARE ONLY TWO SPIN CASES TO CONSIDER
C
C       AAAA         AND         ABBA
C
C     NOTE ALSO THAT THIS TERM CONTRIBUTES ONLY TO IRREP ONE 
C
CEND
C
C   CODED AUGUST/90     JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DISSYH
      DIMENSION H(DISSYH,NUMSYH),T1(1)
C
C GET THE T1 AND L1 AMPLITUDES
C
       CALL GETLST(T1,1,1,1,ISPIN1,LIST1)
       CALL GETLST(T1(1+DISSYH),1,1,1,ISPIN2,LIST2)
C
C  CALCULATE THE CONTRIBUTION
C
       DO 100 IDIS=1,NUMSYH
       DO 100 IDSZ=1,DISSYH
       H(IDSZ,IDIS)=H(IDSZ,IDIS)+FACT*T1(IDSZ)*T1(IDIS+DISSYH)
100    CONTINUE
C 
       RETURN
       END
