
      SUBROUTINE AOSYMVEC(IAOMAP,IAOSYM,NAO)
C
C CALCULATE A "SYMMETRY VECTOR" FOR THE XX AO DISTRIBUTIONS.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION IAOMAP(NAO*NAO),IAOSYM(NAO)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON/AOSYM/IAOPOP(8),IOFFAO(8),IOFFV(8,2),IOFFO(8,2),
     &             IRPDPDAO(8),IRPDPDAOS(8),ISTART(8,8),ISTARTMO(8,3)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      INDX(I,J,N)=I+(J-1)*N
C
      DO 10 IRREP=1,NIRREP
       ITHRU=0
       DO 20 IRREPR=1,NIRREP
        IRREPL=DIRPRD(IRREPR,IRREP)
        LSTART=IOFFAO(IRREPL)
        RSTART=IOFFAO(IRREPR)
        NUML  =IAOPOP(IRREPL)
        NUMR  =IAOPOP(IRREPR)
        DO 21 INDR=RSTART,RSTART+NUMR-1
         DO 22 INDL=LSTART,LSTART+NUML-1
          INDEX=INDX(INDL,INDR,NAO)
          ITHRU=ITHRU+1
          IAOMAP(INDEX)=ITHRU
22       CONTINUE
21      CONTINUE
20     CONTINUE
10    CONTINUE
C
      RETURN
      END
