      SUBROUTINE E4TSC2(T3,EVAL,EVEAA,IADBLK,IADEVE,
     1                 NOCA,NOCB,NVRTA,NVRTB,I,J,K,IRPIJK,E4TBAA)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION T3(1)
      DOUBLE PRECISION EVAL(NOCA+NVRTA,2),E4TBAA,E4TIJK,
     1                 DIJK,EVEAA(1)
      DIMENSION IADEVE(8)
      DIMENSION IADBLK(8)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     1                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     1                NF1BB,NF2BB
      COMMON /INFO/   NOCCO(2),NVRTO(2)
C
      INDEX(I) = I*(I-1)/2
C
C     COMPUTE THE FOURTH-ORDER/T(CCSD) ENERGY
C
      E4TIJK = 0.0D+00
      DIJK = EVAL(I,1) + EVAL(J,1) + EVAL(K,2)
      CABS = 0
      DO 1200 IRPC=1,NIRREP
      IF(VRT(IRPC,2).EQ.0) GOTO 1200
      DO 1190    C=1,VRT(IRPC,2)
      CABS = CABS + 1
      IRPAB = DIRPRD(IRPC,IRPIJK)
      DO 1180 AB=1,IRPDPD(IRPAB,1)
      E4TIJK = E4TIJK + T3(IADBLK(IRPC) +
     1                    (C-1)*IRPDPD(IRPAB,1) + AB - 1) *
     1                  T3(IADBLK(IRPC) +
     1                    (C-1)*IRPDPD(IRPAB,1) + AB - 1) /
     1 (DIJK - EVAL(NOCB + CABS,2) - EVEAA(IADEVE(IRPAB) + AB -1))
 1180 CONTINUE
 1190 CONTINUE
 1200 CONTINUE
      E4TBAA = E4TBAA + E4TIJK
      WRITE(6,3000) E4TIJK,E4TBAA
 3000 FORMAT(' @D1T2-I, E4TIJK, E4TBAA ',2F20.12)
      RETURN
      END
