      SUBROUTINE GOT32(GOOOV,LNOOOV,OOOVAD,
     1                 T3,W,CORE,
     1                 IADT3,IADW,
     1                 IRPI,IRPJ,IRPK,IRPIJ,IRPIK,IRPJK,
     1                 I,J,K,IUHF,T2ABA,T2ABBJ,T2ABBI,T2AAAJ,T2AAAI,
     1                 IGPOS4)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION GOOOV(LNOOOV,*)
      DOUBLE PRECISION T3(1),W(1),CORE(1)
      DOUBLE PRECISION T2ABA(1),T2ABBJ(1),T2ABBI(1),
     1                          T2AAAJ(1),T2AAAI(1)
      DIMENSION IADT3(8),IADW(8)
      DIMENSION IADT2(8),LENT2(8),IADGI(8),LENGI(8)
      DIMENSION OOOVAD(8,4)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     1                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     1                NF1BB,NF2BB
      COMMON /INFO/   NOCCO(2),NVRTO(2)
      COMMON /FLAGS/  IFLAGS(100)
      EQUIVALENCE(ICLLVL,IFLAGS( 2))
      EQUIVALENCE(IDRLVL,IFLAGS( 3))
      EQUIVALENCE(IREFNC,IFLAGS(11))
C
      COMMON /T3OFF/  IOFFVV(8,8,10),IOFFOO(8,8,10),IOFFVO(8,8,4)
C
      INDEX(I) = I*(I-1)/2
C
      ISPIN1 = 1
      ISPIN2 = 2
C
      IF(IRPI.EQ.IRPJ)THEN
      IJ = IOFFOO(IRPJ,IRPIJ,ISPIN1) + INDEX(J-1) + I
      ELSE
      IJ = IOFFOO(IRPJ,IRPIJ,ISPIN1) + (J-1)*POP(IRPI,ISPIN1) + I
      ENDIF
      IK = IOFFOO(IRPK,IRPIK,5) + (K-1)*POP(IRPI,ISPIN1) + I
      JK = IOFFOO(IRPK,IRPJK,5) + (K-1)*POP(IRPJ,ISPIN1) + J
      IKRHF = IOFFOO(IRPI,IRPIK,6) + (I-1)*POP(IRPK,ISPIN2) + K
      JKRHF = IOFFOO(IRPJ,IRPJK,6) + (J-1)*POP(IRPK,ISPIN2) + K
C
      IF(IUHF.EQ.0) GOTO 500
C
C     ROUTINE TO COMPUTE CONTRIBUTION OF T3 AAB IN G(IJ,LA) AAAA.
C
C
C                        ABC  BC
C     G(IJ,LA) =   SUM  T    T
C                  B<C   IJK  LK
C                   K
C       AA AA            AAB  AB
C
C     W IS (B,C,A) REPRESENTATION OF T3 (A<B,C).
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,A), LABELLED BY IRPA.
C
      DO   20 IRPA=1,NIRREP
      IRPL = DIRPRD(IRPA,IRPIJ)
      LENGI(IRPA) = POP(IRPL,ISPIN1) * VRT(IRPA,ISPIN1)
      IF(IRPA.EQ.1)THEN
      IADGI(IRPA) = 1
      ELSE
      IADGI(IRPA) = IADGI(IRPA-1) + LENGI(IRPA-1)
      ENDIF
   20 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO   30 IRPL=1,NIRREP
      IRPKL = DIRPRD(IRPL,IRPK)
      IRPBC = IRPKL
      LENT2(IRPL) = IRPDPD(IRPBC,13) * POP(IRPL,ISPIN1)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
   30 CONTINUE
C
C     READ T2(BC,L).
C
      DO   70 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN1).EQ.0) GOTO 70
      IRPKL = DIRPRD(IRPK,IRPL)
C
C     KL = IOFFOO(IRPK,IRPKL,5) + (K-1)*POP(IRPL,ISPIN1) + 1
C     CALL GETLST(CORE(IADT2(IRPL)),
C    1            KL,POP(IRPL,ISPIN1),1,IRPKL,46)
C
C     WE NOW HAVE T2 IN THE FORM T2(BC,L) AND T3 IN THE FORM
C     T3(BC,A). CONTRACT TOGETHER TO FORM G(L,A), WHICH CAN
C     BE SUMMED INTO GAMMA(LA | IJ).
C
      IRPA = DIRPRD(IRPIJ,IRPL)
      CALL XGEMM('T','N',
     1           POP(IRPL,ISPIN1),VRT(IRPA,ISPIN1),IRPDPD(IRPKL,13),
     1            1.0D+00,
C    1           CORE(IADT2(IRPL)),IRPDPD(IRPKL,13),
     1           T2ABA(IADT2(IRPL)),IRPDPD(IRPKL,13),
     1           W(IADW(IRPA)),IRPDPD(IRPKL,13),
     1            1.0D+00,
     1 GOOOV(OOOVAD(IRPIJ,1)+(IJ-1)*IRPDPD(IRPIJ,15+ISPIN1) +
     1       IADGI(IRPA) - 1,1),
     1           POP(IRPL,ISPIN1))
   70 CONTINUE
C
  500 CONTINUE
C
C                        ABC  AB
C     G(IK,LC) =   SUM  T    T
C                  A<B   IJK  JL
C                   J
C       AB AB            AAB  AA
C
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,C), LABELLED BY IRPC.
C
      DO  120 IRPC=1,NIRREP
      IRPL = DIRPRD(IRPC,IRPIK)
      LENGI(IRPC) = POP(IRPL,ISPIN1) * VRT(IRPC,ISPIN2)
      IF(IRPC.EQ.1)THEN
      IADGI(IRPC) = 1
      ELSE
      IADGI(IRPC) = IADGI(IRPC-1) + LENGI(IRPC-1)
      ENDIF
  120 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  130 IRPL=1,NIRREP
      IRPJL = DIRPRD(IRPL,IRPJ)
      IRPAB = IRPJL
      LENT2(IRPL) = IRPDPD(IRPAB,ISPIN1) * POP(IRPL,ISPIN1)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
  130 CONTINUE
C
C     READ T2(A<B,L).
C
      DO  170 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN1).EQ.0) GOTO 170
      IRPJL = DIRPRD(IRPJ,IRPL)
C
C      IF(IRPJ.LT.IRPL)THEN
C      DO  140    L=1,POP(IRPL,ISPIN1)
C      JL = IOFFOO(IRPL,IRPJL,ISPIN1) + (L-1)*POP(IRPJ,ISPIN1) + J
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,ISPIN1)),
C     1            JL,1,1,IRPJL,43+ISPIN1)
C  140 CONTINUE
C      ENDIF
CC
C      IF(IRPJ.GT.IRPL)THEN
C      JL = IOFFOO(IRPJ,IRPJL,ISPIN1) + (J-1)*POP(IRPL,ISPIN1) + 1
C      CALL GETLST(CORE(IADT2(IRPL)),
C     1            JL,POP(IRPL,ISPIN1),1,IRPJL,43+ISPIN1)
C      CALL VMINUS(CORE(IADT2(IRPL)),LENT2(IRPL))
C      ENDIF
CC
C      IF(IRPJ.EQ.IRPL)THEN
C      DO  160    L=1,POP(IRPL,ISPIN1)
CC
C      IF(J.LT.L)THEN
C      JL = IOFFOO(IRPL,IRPJL,ISPIN1) + INDEX(L-1) + J
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,ISPIN1)),
C     1            JL,1,1,IRPJL,43+ISPIN1)
C      ENDIF
CC
C      IF(J.GT.L)THEN
C      JL = IOFFOO(IRPJ,IRPJL,ISPIN1) + INDEX(J-1) + L
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,ISPIN1)),
C     1            JL,1,1,IRPJL,43+ISPIN1)
C      CALL VMINUS(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,ISPIN1)),
C     1            IRPDPD(IRPJL,ISPIN1))
C      ENDIF
CC
C      IF(J.EQ.L)THEN
C      CALL ZERO(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,ISPIN1)),
C     1          IRPDPD(IRPJL,ISPIN1))
C      ENDIF
C  160 CONTINUE
C
C      ENDIF
C
C     WE NOW HAVE T2 IN THE FORM T2(A<B,L) AND T3 IN THE FORM
C     T3(A<B,C). CONTRACT TOGETHER TO FORM G(L,C), WHICH CAN
C     BE SUMMED INTO GAMMA(LC | IK).
C
      IRPC = DIRPRD(IRPIK,IRPL)
      CALL XGEMM('T','N',
     1  POP(IRPL,ISPIN1),VRT(IRPC,ISPIN2),IRPDPD(IRPJL,ISPIN1),
     1            1.0D+00,
C    1           CORE(IADT2(IRPL)),IRPDPD(IRPJL,ISPIN1),
     1           T2AAAJ(IADT2(IRPL)),IRPDPD(IRPJL,ISPIN1),
     1           T3(IADT3(IRPC)),IRPDPD(IRPJL,ISPIN1),
     1            1.0D+00,
     1 GOOOV(OOOVAD(IRPIK,4)+(IK-1)*IRPDPD(IRPIK,18) +
     1         IADGI(IRPC) - 1,IGPOS4),
     1           POP(IRPL,ISPIN1))
  170 CONTINUE
C
C                        ABC  AB
C     G(JK,LC) = - SUM  T    T
C                  A<B   IJK  IL
C                   I
C       AB AB            AAB  AA
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,C), LABELLED BY IRPC.
C
      DO  220 IRPC=1,NIRREP
      IRPL = DIRPRD(IRPC,IRPJK)
      LENGI(IRPC) = POP(IRPL,ISPIN1) * VRT(IRPC,ISPIN2)
      IF(IRPC.EQ.1)THEN
      IADGI(IRPC) = 1
      ELSE
      IADGI(IRPC) = IADGI(IRPC-1) + LENGI(IRPC-1)
      ENDIF
  220 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  230 IRPL=1,NIRREP
      IRPIL = DIRPRD(IRPL,IRPI)
      IRPAB = IRPIL
      LENT2(IRPL) = IRPDPD(IRPAB,ISPIN1) * POP(IRPL,ISPIN1)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
  230 CONTINUE
C
C     READ T2(A<B,L).
C
      DO  270 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN1).EQ.0) GOTO 270
      IRPIL = DIRPRD(IRPI,IRPL)
C
C      IF(IRPI.LT.IRPL)THEN
C      DO  240    L=1,POP(IRPL,ISPIN1)
C      IL = IOFFOO(IRPL,IRPIL,ISPIN1) + (L-1)*POP(IRPI,ISPIN1) + I
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,ISPIN1)),
C     1            IL,1,1,IRPIL,43+ISPIN1)
C  240 CONTINUE
C      ENDIF
CC
C      IF(IRPI.GT.IRPL)THEN
C      IL = IOFFOO(IRPI,IRPIL,ISPIN1) + (I-1)*POP(IRPL,ISPIN1) + 1
C      CALL GETLST(CORE(IADT2(IRPL)),
C     1            IL,POP(IRPL,ISPIN1),1,IRPIL,43+ISPIN1)
C      CALL VMINUS(CORE(IADT2(IRPL)),LENT2(IRPL))
C      ENDIF
CC
C      IF(IRPI.EQ.IRPL)THEN
C      DO  260    L=1,POP(IRPL,ISPIN1)
CC
C      IF(I.LT.L)THEN
C      IL = IOFFOO(IRPL,IRPIL,ISPIN1) + INDEX(L-1) + I
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,ISPIN1)),
C     1            IL,1,1,IRPIL,43+ISPIN1)
C      ENDIF
CC
C      IF(I.GT.L)THEN
C      IL = IOFFOO(IRPI,IRPIL,ISPIN1) + INDEX(I-1) + L
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,ISPIN1)),
C     1            IL,1,1,IRPIL,43+ISPIN1)
C      CALL VMINUS(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,ISPIN1)),
C     1            IRPDPD(IRPIL,ISPIN1))
C      ENDIF
CC
C      IF(I.EQ.L)THEN
C      CALL ZERO(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,ISPIN1)),
C     1          IRPDPD(IRPIL,ISPIN1))
C      ENDIF
C  260 CONTINUE
CC
C      ENDIF
C
C     WE NOW HAVE T2 IN THE FORM T2(A<B,L) AND T3 IN THE FORM
C     T3(A<B,C). CONTRACT TOGETHER TO FORM G(L,C), WHICH CAN
C     BE SUMMED INTO GAMMA(LC | JK).
C
      IRPC = DIRPRD(IRPJK,IRPL)
      CALL XGEMM('T','N',
     1  POP(IRPL,ISPIN1),VRT(IRPC,ISPIN2),IRPDPD(IRPIL,ISPIN1),
     1           -1.0D+00,
C    1           CORE(IADT2(IRPL)),IRPDPD(IRPIL,ISPIN1),
     1           T2AAAI(IADT2(IRPL)),IRPDPD(IRPIL,ISPIN1),
     1           T3(IADT3(IRPC)),IRPDPD(IRPIL,ISPIN1),
     1            1.0D+00,
     1 GOOOV(OOOVAD(IRPJK,4)+(JK-1)*IRPDPD(IRPJK,18) +
     1         IADGI(IRPC) - 1,IGPOS4),
     1           POP(IRPL,ISPIN1))
  270 CONTINUE
C
      IF(IUHF.GT.0) GOTO 1000
C
C
C                        ABC  BC
C     G(IK,LA) =   SUM  T    T
C                  B,C   IJK  JL
C                   J
C       AB BA            AAB  AB
C
C
C
C     NOTE : THERE IS A PHASE DILEMMA HERE. THUS, WHILE
C
C                     <IJ//KA>  = - <IJ/AK>
C                      AB  BA        AB AB
C
C            IT IS <IJ/AK> WHICH IS STORED. HENCE, TO BE CONSISTENT,
C            WE INTRODUCE A MINUS SIGN WHICH DOES NOT APPEAR IN THE
C            GAMMA EQUATIONS.
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,A), LABELLED BY IRPA.
C
      DO  1320 IRPA=1,NIRREP
      IRPL = DIRPRD(IRPA,IRPIK)
      LENGI(IRPA) = POP(IRPL,ISPIN2) * VRT(IRPA,ISPIN1)
      IF(IRPA.EQ.1)THEN
      IADGI(IRPA) = 1
      ELSE
      IADGI(IRPA) = IADGI(IRPA-1) + LENGI(IRPA-1)
      ENDIF
 1320 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  1330 IRPL=1,NIRREP
      IRPJL = DIRPRD(IRPL,IRPJ)
      IRPBC = IRPJL
      LENT2(IRPL) = IRPDPD(IRPBC,13) * POP(IRPL,ISPIN2)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
 1330 CONTINUE
C
C     READ T2(BC,L).
C
      DO 1370 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN2).EQ.0) GOTO 1370
      IRPJL = DIRPRD(IRPJ,IRPL)
C
C      DO  1340    L=1,POP(IRPL,ISPIN2)
C      JL = IOFFOO(IRPL,IRPJL,5) + (L-1)*POP(IRPJ,ISPIN1) + J
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,13)),
C     1            JL,1,1,IRPJL,46)
C 1340 CONTINUE
C
      IRPA = DIRPRD(IRPIK,IRPL)
      CALL XGEMM('T','N',
     1           POP(IRPL,ISPIN2),VRT(IRPA,ISPIN1),IRPDPD(IRPJL,13),
C    1           -1.0D+00,CORE(IADT2(IRPL)),IRPDPD(IRPJL,13),
     1           -1.0D+00,T2ABBJ(IADT2(IRPL)),IRPDPD(IRPJL,13),
     1           W(IADW(IRPA)),IRPDPD(IRPJL,13),
     1            1.00D+00,
     1 GOOOV(OOOVAD(IRPIK,4)+(IKRHF-1)*IRPDPD(IRPIK,11) +
     1         IADGI(IRPA) - 1,IGPOS4),
     1           POP(IRPL,ISPIN2))
 1370 CONTINUE
C
C                        ABC  BC
C     G(JK,LA) =   SUM  T    T
C                  B,C   IJK  IL
C                   I
C       AB BA            AAB  AB
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,A), LABELLED BY IRPA.
C
      DO 1420 IRPA=1,NIRREP
      IRPL = DIRPRD(IRPA,IRPJK)
      LENGI(IRPA) = POP(IRPL,ISPIN2) * VRT(IRPA,ISPIN1)
      IF(IRPA.EQ.1)THEN
      IADGI(IRPA) = 1
      ELSE
      IADGI(IRPA) = IADGI(IRPA-1) + LENGI(IRPA-1)
      ENDIF
 1420 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  1430 IRPL=1,NIRREP
      IRPIL = DIRPRD(IRPL,IRPI)
      IRPBC = IRPIL
      LENT2(IRPL) = IRPDPD(IRPBC,13) * POP(IRPL,ISPIN2)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
 1430 CONTINUE
C
C     READ T2(BC,L).
C
      DO 1470 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN2).EQ.0) GOTO 1470
      IRPIL = DIRPRD(IRPI,IRPL)
C
C      DO  1440    L=1,POP(IRPL,ISPIN2)
C      IL = IOFFOO(IRPL,IRPIL,5) + (L-1)*POP(IRPI,ISPIN1) + I
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,13)),
C     1            IL,1,1,IRPIL,46)
C 1440 CONTINUE
CC
C     WE NOW HAVE T2 IN THE FORM T2(BC,L) AND T3 IN THE FORM
C     W(BC,A). CONTRACT TOGETHER TO FORM G(L,A), WHICH CAN
C     BE SUMMED INTO GAMMA(LA | JK).
C
      IRPA = DIRPRD(IRPJK,IRPL)
      CALL XGEMM('T','N',
     1           POP(IRPL,ISPIN2),VRT(IRPA,ISPIN1),IRPDPD(IRPIL,13),
C    1            1.0D+00,CORE(IADT2(IRPL)),IRPDPD(IRPIL,13),
     1            1.0D+00,T2ABBI(IADT2(IRPL)),IRPDPD(IRPIL,13),
     1           W(IADW(IRPA)),IRPDPD(IRPIL,13),
     1            1.00D+00,
     1 GOOOV(OOOVAD(IRPJK,4)+(JKRHF-1)*IRPDPD(IRPJK,11) +
     1         IADGI(IRPA) - 1,IGPOS4),
     1           POP(IRPL,ISPIN2))
 1470 CONTINUE
C
      IF(IUHF.EQ.0) RETURN
C
 1000 CONTINUE
C
C                        ABC  BC
C     G(IK,LA) =   SUM  T    T
C                  B,C   IJK  JL
C                   J
C       AB BA            AAB  AB
C
C
C
C     NOTE : THERE IS A PHASE DILEMMA HERE. THUS, WHILE
C
C                     <IJ//KA>  = - <IJ/AK>
C                      AB  BA        AB AB
C
C            IT IS <IJ/AK> WHICH IS STORED. HENCE, TO BE CONSISTENT,
C            WE INTRODUCE A MINUS SIGN WHICH DOES NOT APPEAR IN THE
C            GAMMA EQUATIONS.
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,A), LABELLED BY IRPA.
C
      DO  320 IRPA=1,NIRREP
      IRPL = DIRPRD(IRPA,IRPIK)
      LENGI(IRPA) = POP(IRPL,ISPIN2) * VRT(IRPA,ISPIN1)
      IF(IRPA.EQ.1)THEN
      IADGI(IRPA) = 1
      ELSE
      IADGI(IRPA) = IADGI(IRPA-1) + LENGI(IRPA-1)
      ENDIF
  320 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  330 IRPL=1,NIRREP
      IRPJL = DIRPRD(IRPL,IRPJ)
      IRPBC = IRPJL
      LENT2(IRPL) = IRPDPD(IRPBC,13) * POP(IRPL,ISPIN2)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
  330 CONTINUE
C
C     READ T2(BC,L).
C
      DO  370 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN2).EQ.0) GOTO 370
      IRPJL = DIRPRD(IRPJ,IRPL)
C
C      DO  340    L=1,POP(IRPL,ISPIN2)
C      JL = IOFFOO(IRPL,IRPJL,5) + (L-1)*POP(IRPJ,ISPIN1) + J
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPJL,13)),
C     1            JL,1,1,IRPJL,46)
C  340 CONTINUE
C
C     WE NOW HAVE T2 IN THE FORM T2(BC,L) AND T3 IN THE FORM
C     W(BC,A). CONTRACT TOGETHER TO FORM G(L,A), WHICH CAN
C     BE SUMMED INTO GAMMA(LA | IK).
C
      IRPA = DIRPRD(IRPIK,IRPL)
      CALL XGEMM('T','N',
     1           POP(IRPL,ISPIN2),VRT(IRPA,ISPIN1),IRPDPD(IRPJL,13),
     1           -1.0D+00,
C    1           CORE(IADT2(IRPL)),IRPDPD(IRPJL,13),
     1           T2ABBJ(IADT2(IRPL)),IRPDPD(IRPJL,13),
     1           W(IADW(IRPA)),IRPDPD(IRPJL,13),
     1            1.0D+00,
     1 GOOOV(OOOVAD(IRPIK,3)+(IK-1)*IRPDPD(IRPIK,11) +
     1       IADGI(IRPA) - 1,3),
     1           POP(IRPL,ISPIN2))
  370 CONTINUE
C
C                        ABC  BC
C     G(JK,LA) =   SUM  T    T
C                  B,C   IJK  IL
C                   I
C       AB BA            AAB  AB
C
C     SET ADDRESSES FOR GAMMA INCREMENTS (L,A), LABELLED BY IRPA.
C
      DO  420 IRPA=1,NIRREP
      IRPL = DIRPRD(IRPA,IRPJK)
      LENGI(IRPA) = POP(IRPL,ISPIN2) * VRT(IRPA,ISPIN1)
      IF(IRPA.EQ.1)THEN
      IADGI(IRPA) = 1
      ELSE
      IADGI(IRPA) = IADGI(IRPA-1) + LENGI(IRPA-1)
      ENDIF
  420 CONTINUE
C
C     SET ADDRESSES FOR T2.
C
      DO  430 IRPL=1,NIRREP
      IRPIL = DIRPRD(IRPL,IRPI)
      IRPBC = IRPIL
      LENT2(IRPL) = IRPDPD(IRPBC,13) * POP(IRPL,ISPIN2)
      IF(IRPL.EQ.1)THEN
      IADT2(IRPL) = 1
      ELSE
      IADT2(IRPL) = IADT2(IRPL-1) + LENT2(IRPL-1)
      ENDIF
  430 CONTINUE
C
C     READ T2(BC,L).
C
      DO  470 IRPL=1,NIRREP
      IF(POP(IRPL,ISPIN2).EQ.0) GOTO 470
      IRPIL = DIRPRD(IRPI,IRPL)
C
C      DO  440    L=1,POP(IRPL,ISPIN2)
C      IL = IOFFOO(IRPL,IRPIL,5) + (L-1)*POP(IRPI,ISPIN1) + I
C      CALL GETLST(CORE(IADT2(IRPL) + (L-1)*IRPDPD(IRPIL,13)),
C     1            IL,1,1,IRPIL,46)
C  440 CONTINUE
C
C     WE NOW HAVE T2 IN THE FORM T2(BC,L) AND T3 IN THE FORM
C     W(BC,A). CONTRACT TOGETHER TO FORM G(L,A), WHICH CAN
C     BE SUMMED INTO GAMMA(LA | JK).
C
      IRPA = DIRPRD(IRPJK,IRPL)
      CALL XGEMM('T','N',
     1           POP(IRPL,ISPIN2),VRT(IRPA,ISPIN1),IRPDPD(IRPIL,13),
     1            1.0D+00,
C    1           CORE(IADT2(IRPL)),IRPDPD(IRPIL,13),
     1           T2ABBI(IADT2(IRPL)),IRPDPD(IRPIL,13),
     1           W(IADW(IRPA)),IRPDPD(IRPIL,13),
     1            1.0D+00,
     1 GOOOV(OOOVAD(IRPJK,3)+(JK-1)*IRPDPD(IRPJK,11) +
     1       IADGI(IRPA) - 1,3),
     1           POP(IRPL,ISPIN2))
  470 CONTINUE
      RETURN
      END
