      SUBROUTINE NEWGES(SCR,MAXCOR,IUHF,IRREPX,ISIDE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      LOGICAL DOUBLE,NONSTD,NONSTD2
      DIMENSION SCR(MAXCOR),IJUNK(100)
      COMMON /CALCINFO/ NROOT(8)
      COMMON/EXTINF2/ROOT,OVRLAP,RESID
      COMMON/EXTINF3/IROOT,LROOT,ITROOT
      COMMON/GUESS/DOUBLE,NONSTD,NONSTD2
      COMMON/GUESS2/IMAP(100,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/EXTRAP/MAXEXP,NREDUCE,NTOL,NSIZEC
      DATA ONE,ZILCH,TWO /1.0D0,0.0D0,2.0D0/
C
c      IGET=IMAP(IROOT+1,IRREPX)
      IGET=IROOT+1
C
      IOFFC=1
C
      NROOT(IRREPX)=MIN(NROOT(IRREPX),NSIZEC)
C
      IF(.NOT.DOUBLE)THEN
       CALL GETLST(SCR,IGET,1,1,IRREPX,94)
       CALL GETLST(ROOT,IGET,1,1,IRREPX,95)
       WRITE(6,12)
12     FORMAT(T3,'@NEWGES-I, Using TDA initial guess.')
       IF(IUHF.EQ.0)THEN
        FACT=ONE/SQRT(TWO)
        CALL SSCAL(IRPDPD(IRREPX,9),FACT,SCR,1)
       ENDIF
       DO 10 ISPIN=1,1+IUHF
        CALL PUTLST(SCR(IOFFC),1,1,1,ISPIN,490)
        IOFFC=IOFFC+IRPDPD(IRREPX,8+ISPIN)
10     CONTINUE
       DO 11 ISPIN=3,3-2*IUHF,-1
        CALL ZEROLIST(SCR,MAXCOR,443+ISPIN)
11     CONTINUE
C
      ELSE
C
       I000=1
       I010=I000+NROOT(IRREPX)
       CALL DIAGGUES(IRREPX,SCR(I010),SCR,MAXCOR,IUHF,
     &               NROOT(IRREPX))
       WRITE(6,13)
13     FORMAT(T3,'@NEWGES-I, Using diagonal initial guess.')
       I010=I000+NSIZEC
       I020=I010+NSIZEC
       CALL GETREC(20,'JOBARC','STRTGUES',IGET,IJUNK)
       CALL ZERO(SCR,NSIZEC)
       SCR(IJUNK(IGET))=ONE
       CALL SYMT2AB(IRREPX,SCR,SCR(I010),MAXCOR-I010+1)
       CALL SCOPY(NSIZEC,SCR,1,SCR(I010),1)
       CALL SPNTSING(IRREPX,SCR,SCR(I020),MAXCOR-I020+1)
       X=ONE/SQRT(SDOT(NSIZEC,SCR,1,SCR(I010),1))
       CALL SSCAL(NSIZEC,X,SCR(I010),1) 
       CALL SCOPY(NSIZEC,SCR(I010),1,SCR,1)
       CALL PUTLST(SCR(IOFFC),1,1,1,1,490)
       IOFFC=1+IRPDPD(IRREPX,9)
       CALL PUTALL(SCR(IOFFC),1,IRREPX,446)
C
      ENDIF
C
      RETURN
      END
