C
      SUBROUTINE RNGCONTR(W, T, Q, DISSYG, NUMSYG, DISSYT, NUMSYT,
     &                    DISSYQ, NUMSYQ, LISTG, LISTT, IRREPGR,
     &                    IRREPTR, CALMOD, SPINAD)
C
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      INTEGER POP,VRT
      LOGICAL SPINAD
      CHARACTER*3 CALMOD
      INTEGER DISSYT,DISSYG,DISSYQ
      DIMENSION W(DISSYG,NUMSYG),T(DISSYT,NUMSYT),Q(DISSYQ,NUMSYQ)
C
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(6)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C Common blocks used in the quadratic term
C
      COMMON /QADINTI/ INTIMI, INTIAE, INTIME
      COMMON /QADINTG/ INGMNAA, INGMNBB, INGMNAB, INGABAA,
     &                 INGABBB, INGABAB, INGMCAA, INGMCBB,
     &                 INGMCABAB, INGMCBABA, INGMCBAAB,
     &                 INGMCABBA
      COMMON /APERTT1/ IAPRT1AA
      COMMON /BPERTT1/ IBPRT1AA
      COMMON /APERTT2/ IAPRT2AA1, IAPRT2BB1, IAPRT2AB1, IAPRT2AB2, 
     &                 IAPRT2AB3, IAPRT2AB4, IAPRT2AA2, IAPRT2BB2,
     &                 IAPRT2AB5 
C
      DATA ONE /1.0D+00/
      DATA TWO /2.0D+00/
      DATA ONEM /-1.0D+00/
      DATA HALFM /-0.5D+00/
      DATA ZILCH /0.0/
C
C Pick up relevent T2 and W pieces, and spin adapt if needed.
C
      CALL GETLST(T, 1, NUMSYT, 1, IRREPTR, LISTT)
C
      IF (SPINAD) THEN
         CALL GETLST(W, 1, NUMSYT, 1, IRREPTR, IAPRT2AA1)
         CALL SAXPY(NUMSYT*DISSYT, ONEM, W, 1, T, 1)
         LISTG = INGMCABAB
      ENDIF
C
      CALL GETLST(W, 1, NUMSYG, 2, IRREPGR, LISTG)
C     
      IF (MIN (DISSYT, NUMSYT, NUMSYG) .NE. 0) THEN
C
         CALL XGEMM('N', 'N', DISSYT, NUMSYG, NUMSYT, ONE, T, DISSYT,
     &               W, DISSYG, ZILCH, Q, DISSYT)
      ELSE
         CALL ZERO(Q, NUMSYQ*DISSYQ)
      ENDIF
C
      IF (SPINAD) CALL SSCAL(NUMSYQ*DISSYQ, HALFM, Q, 1)
C
      RETURN
      END
