
      SUBROUTINE SQROUT(ZOO,ZVO,ZOV,ZVV,NOCC,NVRT,BUF,IARG)
C
C THIS ROUTINE CONSTRUCTS THE SQUARED OUT MATRIX:
C
C                    ZOO      ZOV
C          BUF =  
C                    ZVO      ZVV
C
C WHERE ZOO, ZVO, ZOV AND ZVV ARE THE OCC-OCC, VRT-OCC, OCC-VRT
C       AND VRT-VRT SUBMATRICES.  THE NUMBER OF OCCUPIED AND
C       VIRTUAL ORBITALS IS GIVEN BY NOCC AND NVRT.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION ZOO(1),ZVO(1),ZOV(1),ZVV(1),BUF(1)
C
      NTOT=NOCC+NVRT
      IOFF=NOCC+1
C
C IF IARG IS NONNEGATIVE, EXPAND TO BUF
C
      IF(IARG.NE.0)THEN
       CALL BLKCPY(ZOO,NOCC,NOCC,BUF,NTOT,NTOT,1,1)
       CALL BLKCPY(ZVO,NVRT,NOCC,BUF,NTOT,NTOT,IOFF,1)
       CALL BLKCPY(ZOV,NOCC,NVRT,BUF,NTOT,NTOT,1,IOFF)
       CALL BLKCPY(ZVV,NVRT,NVRT,BUF,NTOT,NTOT,IOFF,IOFF)
C
C ELSE CONTRACT FROM BUF
C
      ELSE
       CALL BLKCPY2(BUF,NTOT,NBOT,ZOO,NOCC,NOCC,1,1)
       CALL BLKCPY2(BUF,NTOT,NTOT,ZVO,NVRT,NOCC,IOFF,1)
       CALL BLKCPY2(BUF,NTOT,NTOT,ZOV,NOCC,NVRT,1,IOFF)
       CALL BLKCPY2(BUF,NTOT,NTOT,ZVV,NVRT,NVRT,IOFF,IOFF)
      ENDIF
C
      RETURN
      END
