
      SUBROUTINE DZERSYM(IRREPX,Z,NLIST) 
C
C ZEROS LIST NLIST
C
CEND
      IMPLICIT INTEGER (A-Z)
C
      DOUBLE PRECISION Z(*)
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      DO 10 IRREPR=1,NIRREP
       IRREPL=DIRPRD(IRREPR,IRREPX)
       NSYDIS=IRPDPD(IRREPR,ISYTYP(2,NLIST))
       NSYDSZ=IRPDPD(IRREPL,ISYTYP(1,NLIST))
       CALL ZERO(Z,NSYDIS*NSYDSZ)
       CALL PUTLST(Z,1,NSYDIS,1,IRREPR,NLIST)
10    CONTINUE
      RETURN
      END
