      SUBROUTINE FORMW4(ICORE,MAXCOR,IUHF,TERM1,TERM2,TERM3,TERM4,
     &                  TERM5,TERM6,TAU,CCSD)
C
C THIS ROUTINE DRIVES THE FORMATION OF THE W(IAJK) HBAR ELEMENTS
C
C   NOTE: THIS ROUTINE IS NEEDED ONLY FOR CCSD-BASED METHODS SINCE
C          W(IAJK) = <IA||JK> FOR QCISD.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      LOGICAL TERM1,TERM2,TERM3,TERM4,TERM5,TERM6,TAU,CCSD,CC2
C
      COMMON/FLAGS/IFLAGS(100)
C
C FOR CCSD SECOND DERIVATIVE CALCULATIONS, STORE W(IFMN) ON LISTS 207 TO 210
C
      IOFFLIST=0
      IF(IFLAGS(3).EQ.2) IOFFLIST=100

      IF (IFLAGS(2) .EQ. 47) CC2 = .TRUE.
C
      IF (CC2) THEN

      CALL MKHIAJK(ICORE,MAXCOR,IUHF,106+IOFFLIST,43,37,39,
     &             90,90,23,24,18,17,25,26,6,50,93,26,
     &             1,1,.FALSE.,.FALSE.,.FALSE.,
     &             TERM1,TERM2,TERM3,TERM4,TERM5,TERM6,TAU,.TRUE.,
     &             CCSD)

      ELSE


      CALL MKHIAJK(ICORE,MAXCOR,IUHF,106+IOFFLIST,43,37,39,
     &             90,90,123,124,118,117,125,126,6,50,93,26,
     &             1,1,.FALSE.,.FALSE.,.FALSE.,
     &             TERM1,TERM2,TERM3,TERM4,TERM5,TERM6,TAU,.TRUE.,
     &             CCSD)
      ENDIF 
C
      RETURN
      END
