      
      SUBROUTINE FORMH4(ICORE,MAXCOR,IUHF)
C
C   THIS ROUTINE CALCULATES THE FOURTH INTERMEDIATE REQUIRED
C   FOR THE QUADRUPLE CONTRIBUTION X(IJ,AB)
C
C  MBPT(4)
C
C   H(ME,JB) = - SUM N,F  T1(MN,EF) T1(NJ,FB)
C
C  CCD
C   
C   H(ME,JB) = - SUM N,F  L(MN,EF) T(NJ,FB)
C
C  QCISD
C
C   H(ME,JB) = - SUM N,F L(MN,EF) T(NJ,FB)
C
C  CCSD
C
C   G(IA,JB) = - SUM N,F L(MN,EF) (T(NJ,FB) + ...)
C
C  THIS TERM IS VERY SIMILAR TO THE T1(IJ,AB) CONTRIBUTION TO
C  THE W-RING INTERMEDIATE
C
C  THE SPIN CASES ARE
C
C    AAAA : =  - SUM M,E T1(IM,BE) T1(MJ,EA) - SUM m,e T1(Im,Be) T1(Jm,Ae)
C
C    ABAB : =  - SUM m,E T1(Im,Eb) T1(Jm,Ea)
C
C    ABBA : =  - SUM M,E T1(IM,BE) T1(Mj,Ea) - SUM m,e T1(Im,Be) T1(mj,eb)
C
C FOR UHF IN ADDITION THE BBBB BABA AND BABA SPIN CASES HAS TO CALCULATES
C
C
C  AAAA : LIST 54  (CALCULATED FROM ABAB AND ABBA IN QUIKAA)
C  BBBB : LIST 55  (UHF ONLY)
C  ABBA : LIST 58
C  BAAB : LIST 59  (UHF ONLY)
C  ABAB : LIST 56
C  BABA : LIST 57  (UHF ONLY)
C
CEND
C 
C  CODED AUGUST/90  JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      DIMENSION ICORE(MAXCOR)
      COMMON/METH/MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
C
      CALL H4ALL(ICORE,MAXCOR,'ABBA',IUHF)
      CALL H4ALL(ICORE,MAXCOR,'ABAB',IUHF)
      IF(IUHF.EQ.1) THEN
       CALL H4ALL(ICORE,MAXCOR,'AAAA',IUHF)
      ELSE
       CALL QUIKAA2(ICORE,MAXCOR)
      ENDIF
      IF(IUHF.NE.0) THEN
       CALL H4ALL(ICORE,MAXCOR,'BBBB',IUHF)
       CALL H4ALL(ICORE,MAXCOR,'BABA',IUHF)
C
C   BAAB HAS BEEN CALCULATED ALREADY IN THE CALL WITH ABBA
C

      ENDIF
      RETURN
      END
