      SUBROUTINE W5SCRFIL
C
C LOGIC FOR CREATING SCRATCH FILE FOR RESORTED ABCI INTEGRALS
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL YESNO
      DIMENSION TYPEL(10),TYPER(10)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/SYMINF/NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
C
      DATA TYPEL/13,9,19,13,18,20,19,9,19,20/
      DATA TYPER/11,20,9,11,13,10,10,20,9,10/
C
      INQUIRE(FILE='DERGAM',EXIST=YESNO)
      IF(YESNO)RETURN
C
C FIND LARGEST SIZE
C
      SIZMAX=0
      DO 5 I=1,10
       SIZE=ISYMSZ(TYPEL(I),TYPER(I))
       IF(SIZE.GT.SIZMAX)THEN
        IDOL=TYPEL(I)
        IDOR=TYPER(I)
        SIZMAX=SIZE
       ENDIF
5     CONTINUE
C
CJDW 2/7/95. Complaint from Sun : IMODE stops complaint about trying to
C            change a constant.
C
c      IMODE = 1
      call aces_io_remove(54,'DERGAM')
      IMODE = 0
      CALL INIPCK(1,IDOL,IDOR,401,IMODE,-1,1)
C     CALL INIPCK(1,IDOL,IDOR,401,1,-1,1)
C
      RETURN
      END
