      SUBROUTINE GETDCIS(DOO,DVV,IUHF)
C
C THIS SUBROUTINE READS THE DENSITY MATRIX FROM THE GAMLAM FILE
C
C THE LISTS READ ARE:
C
C  DOOA    1,160
C  DOOB    2,160    UHF AND ROHF ONLY
C  DVVA    3,160
C  DVVB    4,160    UHF AND ROHF ONLY
C  DVOA    5,160  
C  DVOB    6,160    UHF AND ROHF ONLY
C
CEND
C
C CODED APRIL/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
      INTEGER POP,VRT
      DIMENSION DOO(*),DVV(*)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NF1(2),NF2(2)
      COMMON/METH/MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,UCC
C
      CALL GETLST(DOO,1,1,1,1,160)
      CALL GETLST(DVV,1,1,1,3,160)
C
      IF(IUHF.NE.0) THEN
C
       CALL GETLST(DOO(1+NF1(1)),1,1,1,2,160)
       CALL GETLST(DVV(1+NF2(1)),1,1,1,4,160)
C
      ENDIF
C
      RETURN
      END
