      SUBROUTINE ROHFZ(XIAA,XIAB,EVALA,EVALB,POPA,POPB,
     &                 VRTA,VRTB,NOCCA,NOCCB)
C
C  THIS ROUTINE FORMS THE ELEMENTS OF THE OCCUPIED-VIRTUAL BLOCK
C  OF THE DENSITY MATRIX
C 
CEND
C
C CODED JULY/90 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER POPA,POPB,VRTA,VRTB,DIRPRD
      DIMENSION XIAA(1),XIAB(1),EVALA(1),EVALB(1),POPA(8),
     &          POPB(8),VRTA(8),VRTB(8)
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
C
      INDA=0
      INDB=0
      IOFFPA=0
      IOFFPB=0
      IOFFVA=NOCCA
      IOFFVB=NOCCB
      DO 10 IRREP=1,NIRREP
       NOA=POPA(IRREP)
       NVA=VRTA(IRREP)
       NOB=POPB(IRREP)
       NVB=VRTB(IRREP)
       IF(NOA.EQ.NOB) THEN
       DO 5 I=1,NOA
        INDIA=I+IOFFPA
        INDIB=I+IOFFPB
        DO 5 IA=1,NVA
        INDAA=IA+IOFFVA
        INDAB=IA+IOFFVB
        INDA=INDA+1
        INDB=INDB+1
        XIA=(XIAA(INDA)+XIAB(INDB))/(EVALA(INDIA)+EVALB(INDIB)
     &                          -EVALA(INDAA)-EVALB(INDAB))
        XIAA(INDA)=XIA
        XIAB(INDB)=XIA
5      CONTINUE
       ELSE
       NOPEN=NOA-NOB
       DO 6 I=1,NOB
        INDIA=I+IOFFPA
        INDIB=I+IOFFPB
        DO 7 IOPEN=1,NOPEN
         INDAB=IOPEN+IOFFVB
         INDB=INDB+1
         XIAB(INDB)=XIAB(INDB)/(EVALB(INDIB)-EVALB(INDAB))
7       CONTINUE
        DO 8 IA=1,NVA
         INDAA=IA+IOFFVA
         INDAB=IA+NOPEN+IOFFVB
         INDA=INDA+1
         INDB=INDB+1
         XIA=(XIAA(INDA)+XIAB(INDB))/(EVALA(INDIA)+EVALB(INDIB)
     &                           -EVALA(INDAA)-EVALB(INDAB))
         XIAA(INDA)=XIA
         XIAB(INDB)=XIA
8       CONTINUE
6      CONTINUE
       DO 9 IOPEN=1,NOPEN 
        INDIA=IOPEN+NOB+IOFFPA
        DO 9 IA=1,NVA
         INDAA=IA+IOFFVA
         INDA=INDA+1
         XIAA(INDA)=XIAA(INDA)/(EVALA(INDIA)-EVALA(INDAA))
9      CONTINUE
       ENDIF
       IOFFPA=IOFFPA+NOA
       IOFFVA=IOFFVA+NVA
       IOFFPB=IOFFPB+NOB
       IOFFVB=IOFFVB+NVB
10    CONTINUE
      RETURN
      END
