      SUBROUTINE SYMDRV(IBUF,IBUFSZ,NORB,IUHF)
C
C ROUTINE TO DRIVE SYMMETRY VECTOR CREATION.
C
      IMPLICIT INTEGER (A-Z)
      CHARACTER*1 XX(2)
      DIMENSION IBUF(IBUFSZ)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      DATA XX /'A','B'/
      ITWO=2
      IR1=1
      IR2=IR1+2*NORB
      IR3=IR2+NIRREP
      IR4=IR3
      CALL GETREC(20,'JOBARC','IRREPALP',NORB,IBUF(IR1))
      CALL GETREC(20,'JOBARC','IRREPBET',NORB,IBUF(IR1+NORB))
      DO 10002 IMODE=0,1
       DO 10001 ISPIN=1,2
        ISIZE=(NVRTO(ISPIN)*(NVRTO(ISPIN)-1))/2
        IF(IMODE.EQ.1)ISIZE=ISIZE+NVRTO(ISPIN)
        IR5=IR4+2*ISIZE
C
C 03/12/97 AP, deleted the unnecessary ISIZE argument at the
C end of the SYMVEC call.
C
        CALL SYMVEC('VRT','VRT',ISPIN,ISPIN,IMODE,NOCCO,NVRTO,
     &             DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &             ISIZE,'SV'//XX(ISPIN)//'V'//XX(ISPIN))
10001  CONTINUE
       DO 20001 ISPIN=1,2
        ISIZE=(NOCCO(ISPIN)*(NOCCO(ISPIN)-1))/2
        IF(IMODE.EQ.1)ISIZE=ISIZE+NOCCO(ISPIN)
        IR5=IR4+2*ISIZE
        CALL SYMVEC('OCC','OCC',ISPIN,ISPIN,IMODE,NOCCO,NVRTO,
     &             DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &             ISIZE,'SO'//XX(ISPIN)//'O'//XX(ISPIN))
20001 CONTINUE
10002 CONTINUE
      IMODE=2
      DO 10003 ISPIN=1,2
       ISIZE=NOCCO(ISPIN)*NVRTO(ISPIN)
       IR5=IR4+2*ISIZE
       CALL SYMVEC('VRT','OCC',ISPIN,ISPIN,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SV'//XX(ISPIN)//'O'//XX(ISPIN))
10003 CONTINUE
      ISIZE=NOCCO(2)*NVRTO(1)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','OCC',1,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOBVA')
      ISIZE=NOCCO(1)*NVRTO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','OCC',2,1,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SVBOA')
      ISIZE=NVRTO(1)*NVRTO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','VRT',1,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SVAVB')
      ISIZE=NOCCO(1)*NOCCO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','OCC',1,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOAOB')
      ISIZE=NVRTO(1)*NVRTO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','VRT',1,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SVAVB')
      ISIZE=NVRTO(1)*NOCCO(1)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','VRT',1,1,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOAVA')
      ISIZE=NVRTO(2)*NOCCO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','VRT',2,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOBVB')
      ISIZE=NOCCO(1)*NVRTO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','VRT',1,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOAVB')
      ISIZE=NVRTO(1)*NVRTO(1)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','VRT',1,1,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SVAVA')
      ISIZE=NVRTO(2)*NVRTO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('VRT','VRT',2,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SVBVB')
      ISIZE=NOCCO(1)*NOCCO(1)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','OCC',1,1,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOAOA')
      ISIZE=NOCCO(2)*NOCCO(2)
      IR5=IR4+2*ISIZE
      CALL SYMVEC('OCC','OCC',2,2,IMODE,NOCCO,NVRTO,
     &            DIRPRD,IBUF(IR1),NIRREP,NORB,IBUF(IR2),IBUF(IR3),
     &            ISIZE,'SOBOB')
C
C NOW SET UP THE OCC AND VRT SYMMETRY VECTORS.
C
      I000=1
      I010=I000+NIRREP
      I020=I010+NORB
      CALL SYVEC2(IBUF(I000),IBUF(I010),NORB,NIRREP,NOCCO(1),
     &            NOCCO(2),IUHF)
C
C FIND FIRST RECORD HOLDING SYMMETRY VECTORS.
C
COBS      NSTART=IRECNU(20,'JOBARC','SVAVA0  ')
      RETURN
      END
