      SUBROUTINE GETEVAL(FA,FB,EVAL,CMO,SCR1,SCR2,NTOTAL,
     &                   NTOTAL2,NBAS)
CEND
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION CNORM,CTOL
      INTEGER DIRPRD
      DIMENSION FA(NTOTAL),FB(NTOTAL),EVAL(1),
     &          CMO(NTOTAL2),SCR1(1),SCR2(1),NBAS(8)
      COMMON/MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
C
      DATA AZERO,HALF,ONE,ONEM /0.0D0,0.5D0,1.D0,-1.D0/
      DATA CTOL /1.0D-06/
C
      INDX(I,J)=I*(I-1)/2+J
C
C TRANSFORM FA AND FB TO MO BASIS
C
C GET THE MO VECTORS
C
       NBAST=0
       DO 2 IRREP=1,NIRREP
        NBAST=NBAST+NBAS(IRREP)
2      CONTINUE
      CALL GETREC(20,'JOBARC','MOVECTOR',NTOTAL2*IINTFP,CMO)
C 
C TRANSFORM
C
      IOFF1=1
      IOFF2=1
      IOFFB=0
      DO 100 IRREP=1,NIRREP
       IF(NBAS(IRREP).EQ.0) GO TO 100
       CALL EXPND2(FA(IOFF2),SCR1,NBAS(IRREP))
       CALL XGEMM('N','N',NBAS(IRREP),NBAS(IRREP),NBAS(IRREP),ONE,
     &            SCR1,NBAS(IRREP),CMO(IOFF1),NBAS(IRREP),AZERO,
     &            SCR2,NBAS(IRREP))
       CALL XGEMM('T','N',NBAS(IRREP),NBAS(IRREP),NBAS(IRREP),ONE,
     &            CMO(IOFF1),NBAS(IRREP),SCR2,NBAS(IRREP),AZERO,
     &            SCR1,NBAS(IRREP))
       DO 80 I=1,NBAS(IRREP)
C
C Adjust eigenvalue if eigenvector is zero (ie removed because of a linear
C dependency.
C
        CNORM = 0.0D+00
        CNORM = SNRM2(NBAS(IRREP),CMO(IOFF1 + (I-1)*NBAS(IRREP)),1)
        IF(CNORM.GE.CTOL)THEN
          EVAL(I+IOFFB)=SCR1(I+(I-1)*NBAS(IRREP))
        ELSE
          EVAL(I+IOFFB)=1.0D+06
        ENDIF
80     CONTINUE
C
       CALL EXPND2(FB(IOFF2),SCR1,NBAS(IRREP))
       CALL XGEMM('N','N',NBAS(IRREP),NBAS(IRREP),NBAS(IRREP),ONE,
     &            SCR1,NBAS(IRREP),CMO(IOFF1),NBAS(IRREP),AZERO,
     &            SCR2,NBAS(IRREP))
       CALL XGEMM('T','N',NBAS(IRREP),NBAS(IRREP),NBAS(IRREP),ONE,
     &            CMO(IOFF1),NBAS(IRREP),SCR2,NBAS(IRREP),AZERO,
     &            SCR1,NBAS(IRREP))
       DO 90 I=1,NBAS(IRREP)
        CNORM = 0.0D+00
        CNORM = SNRM2(NBAS(IRREP),CMO(IOFF1 + (I-1)*NBAS(IRREP)),1)
        IF(CNORM.GE.CTOL)THEN
          EVAL(NBAST+I+IOFFB)=SCR1(I+(I-1)*NBAS(IRREP))
        ELSE
          EVAL(NBAST+I+IOFFB)=1.0D+06
        ENDIF
90     CONTINUE
       IOFFB=IOFFB+NBAS(IRREP)
       IOFF1=IOFF1+NBAS(IRREP)*NBAS(IRREP)
       IOFF2=IOFF2+NBAS(IRREP)*(NBAS(IRREP)+1)/2
100   CONTINUE
C
C ALL DONE
C
      RETURN
      END
