
      SUBROUTINE SETUPPRJ(NATOMS,NBASIS,IORDGRP,ICENTER,IANGMOM,
     &                    ILCATM,NBFATM,NUMANG,IPTR,SYOP,ORIENT,
     &                    ISCR)
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICENTER(NBASIS),IANGMOM(NBASIS)
      DIMENSION ILCATM(NATOMS),NBFATM(NATOMS),NUMANG(NATOMS,5)
      DIMENSION SYOP(9*IORDGRP),IPTR(NATOMS*IORDGRP),ORIENT(9)
      DIMENSION ISCR(1),IPOP(5)
C     
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DATA IPOP /1,3,6,10,15/
C
      CALL GETREC(20,'JOBARC','CNTERBF0',NBASIS,ICENTER)
      CALL GETREC(20,'JOBARC','ANMOMBF0',NBASIS,IANGMOM)
C
C DETERMINE NBF PER ATOM, NUMBER OF S, P , D ETC PER ATOM
C
      DO 10 I=1,NATOMS
       CALL WHENEQ(NBASIS,ICENTER,1,I,ISCR,NBFATM(I))
       ILCATM(I)=ISCR(1)
       DO 15 IANG=1,5
        CALL WHENEQ(NBFATM(I),IANGMOM(ILCATM(I)),1,IANG-1,
     &              ISCR,NUMANG(I,IANG))
        NUMANG(I,IANG)=NUMANG(I,IANG)/IPOP(IANG)
15     CONTINUE
10    CONTINUE 
C
      CALL GETREC(20,'JOBARC','FULLSYOP',IINTFP*9*IORDGRP,SYOP)
      CALL GETREC(20,'JOBARC','FULLPERM',IORDGRP*NATOMS,IPTR)
      CALL GETREC(20,'JOBARC','ORIENTMT',9*IINTFP,ORIENT)
      CALL TRNOPS(SYOP,ORIENT,IORDGRP)
C
      RETURN
      END
