      SUBROUTINE DINV12(VIA,DVV,ICORE,MAXCOR,IUHF)
C
C THIS SUBROUTINE CALCULATES THE L(AI) CONTRIBUTION
C DUE TO THE VIRTUAL-VIRTUAL BLOCK OF THE G INTERMEDIATE
C
C      V(AI) += SUM F,G <GA//FI> D(GF)
C
C WHICH IS NEEDED FOR CCSD GRADIENT CALCULATIONS
C
C THIS ROUTINE USES EXPLICITELY SYMMETRY
C
CEND
C
C CODED SEPTEMBER/90
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      DOUBLE PRECISION via
      INTEGER DIRPRD,DISSYW,POP,VRT
      DIMENSION via(1),dvv(1),ICORE(MAXCOR)
      common/info/nocco(2),nvrto(2)
      COMMON /SYM/ POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF1BB,NF2AA,NF2BB
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
      MXCOR=MAXCOR
C
C NEW CODE
C
       CALL DVVINVO(1,via,dvv,ICORE,MXCOR,IUHF,27)

      RETURN
      END
