      SUBROUTINE CONSOR(F,E,UP,UM,DENP,DENM,FP,FM,
     X UP2,UM2,F2,E2,EVAL,EVEC,EHF,MCOMP,HMO,XX,IX,NINTMX,IA,
     X IVRT,IOCC,NSIZ1,NSIZ3,NSIZO)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      COMMON/INFOA/NBASIS,NUMSCF,NX,NMO2,NOC,NVT,NVO
      COMMON/SWPPP/INP,IAMO,IFAMO,IINDO,IORTH
      COMMON/IPRNT/ IOPEV,IOPDA,IOPU,IOPFE,IOPPR,IWRPA
      DIMENSION UP(NSIZ1,NSIZO,3),UM(NSIZ1,NSIZO,3)
     X ,UP2(NSIZ1,NSIZO,MCOMP),UM2(NSIZ1,NSIZO,MCOMP)
      DIMENSION F(NSIZ1,NSIZ1,3),F2(NSIZ1,NSIZ1,MCOMP)
     X ,E2(NSIZO,NSIZO,MCOMP),E(NSIZO,NSIZO,3)
     X ,EVAL(1),EVEC(1),DENP(1),DENM(1),FP(1),FM(1)
      DIMENSION EHF(3,MCOMP),HMO(NSIZ3,3),IA(1),IVRT(1),IOCC(1)
      DIMENSION ICOMP(9),JCOMP(9)
      DIMENSION XX(NINTMX),IX(NINTMX)
C     DIMENSION DENPO(5050)
C .... This routine can handle D(+w,-w) up to MCOMP=9
      DATA ICOMP/ 1,2,3,1,2,3,2,3,1/, JCOMP/ 1,2,3,2,3,1,1,2,3/
      DATA ZERO/0.D00/,TWO/2.D0/,HALF/5.D-01/,FOUR/4.D0/
      DATA ONE/1.D00/,OCTH/1.D-8/,THREE/3.D0/
      WRITE(6,*) ' Now in CONSOR'
      SQRT2 = SQRT(TWO)
      DO 50 IRL=1,MCOMP
      IC = ICOMP(IRL)
      JC = JCOMP(IRL)
      WRITE(6,*) ' x,y,z ',IC,JC
      DO 10 I=1,NUMSCF
      DO 10 J=1,NOC
      IF(I.GT.NOC) THEN
      UP2(I,J,IRL)=ZERO
      UM2(I,J,IRL)=ZERO
      DO 11 K=1,NUMSCF
      UP2(I,J,IRL)=UP2(I,J,IRL)+F(I,K,IC)*UM(K,J,JC)
     X +F(K,I,JC)*UP(K,J,IC)
      UM2(I,J,IRL)=UM2(I,J,IRL)+F(K,I,IC)*UP(K,J,JC)
     X +F(I,K,JC)*UM(K,J,IC)
   11 CONTINUE
      DO 13 K=1,NOC
      UP2(I,J,IRL)=UP2(I,J,IRL)
     X -UP(I,K,IC)*E(J,K,JC)-UM(I,K,JC)*E(K,J,IC)
      UM2(I,J,IRL)=UM2(I,J,IRL)
     X -UM(I,K,IC)*E(K,J,JC)-UP(I,K,JC)*E(J,K,IC)
   13 CONTINUE
      ELSE
      UP2(I,J,IRL)=ZERO
      DO 12 K=1,NUMSCF
      UP2(I,J,IRL)=UP2(I,J,IRL)+UM(K,I,IC)*UM(K,J,JC)
     X                       +UP(K,I,JC)*UP(K,J,IC)
   12 CONTINUE
      UP2(I,J,IRL)=-HALF*UP2(I,J,IRL)
      UM2(J,I,IRL)=UP2(I,J,IRL)
      END IF
   10 CONTINUE
      write(6,*) ' IRL = ',IRL
      IF(IOPU.NE.0) THEN
      write(6,*) ' UP2 '
      CALL OUTMXD(UP2(1,1,IRL),NSIZ1,NUMSCF,NSIZO)
      write(6,*) ' UM2 '
      CALL OUTMXD(UM2(1,1,IRL),NSIZ1,NUMSCF,NSIZO)
      END IF
      IJ=0
      DO 15 I=1,NUMSCF
      DO 15 J=1,I
      IJ=IJ+1
C     DENPO(IJ)=ZERO
      FP(IJ) = ZERO
      FM(IJ) = ZERO
      DTPLOW= ZERO
      DTMLOW= ZERO
      DO 16 K=1,NOC
      DTPLOW=DTPLOW+ UP(I,K,IC)*UP(J,K,JC)+UM(I,K,JC)*UM(J,K,IC)
      DTMLOW=DTMLOW+ UM(I,K,IC)*UM(J,K,JC)+UP(I,K,JC)*UP(J,K,IC)
   16 CONTINUE
      DTPLOW=DTPLOW*TWO
      DTMLOW=DTMLOW*TWO
C ...... UP2(I,J)+UM2(J,I)=TWO*UP2(I,J) for I,J; occ
      IF(I.LE.NOC) DTPLOW = DTPLOW + FOUR*UP2(I,J,IRL)
      IF(I.LE.NOC) DTMLOW = DTMLOW + FOUR*UM2(I,J,IRL)
      DENP(IJ) = (DTPLOW+DTMLOW)/SQRT2
      DENM(IJ) = (DTPLOW-DTMLOW)/SQRT2
C     IF(I.LE.NOC) DENPO(IJ)=FOUR*(UP2(I,J,IRL)+UM2(I,J,IRL))/SQRT2
C     write(6,*) ' denp ',I,J,DENP(IJ),DENM(IJ)
   15 CONTINUE
      DO 17 M=1,3
   17  EHF(M,IRL)=ZERO
      DO 18 M=1,3
   18 EHF(M,IRL)= TRACEP(DENP,HMO(1,M),NUMSCF)/SQRT2
      WRITE(6,100)(EHF(I,IRL),I=1,3)
C     EHFZO= TRACEP(DENPO,HMO(1,3),NUMSCF)/SQRT2
C     WRITE(6,*) ' enrgy from o-o part ',EHFZO,' on Z '
  100 FORMAT(1H0,' CONSTANT ENERGY = ',6F15.7)
      IF(IFAMO.EQ.0) THEN
      CALL FMOK(DENP,FP,XX,IX,NINTMX,IA)
      CALL FMOL(DENM,FM,XX,IX,NINTMX,IA)
      ELSE
      CALL DENAO(NBASIS,EVEC,DENP,FP)
      CALL DEMAO(NBASIS,EVEC,DENM,FM)
      IF(IINDO.EQ.0) THEN
      CALL FNOK(DENP,EVEC,FP,NBASIS,NUMSCF,XX,IX,NINTMX,IA)
      CALL FNOL(DENM,EVEC,FM,NBASIS,NUMSCF,XX,IX,NINTMX,IA)
      ELSE
      CALL FINDO(NBASIS,NVO,IVRT,IOCC,EVEC,DENP,FP)
      CALL FIMDO(NBASIS,NVO,IVRT,IOCC,EVEC,DENM,FM)
      END IF
      END IF
      IJ=0
      DO 20 I=1,NUMSCF
      DO 20 J=1,I
      F2(I,J,IRL)=ZERO
      IJ=IJ+1
      IJL=(J-1)*NUMSCF+I
      IF(IFAMO.EQ.0) IJL=IJ
      F2(I,J,IRL)=(FP(IJL)+FM(IJL))/SQRT2
      F2(J,I,IRL)=(FP(IJL)-FM(IJL))/SQRT2
C     write(6,*) I,J,DENP(IJL),DENM(IJL),' FP ',FP(IJL),' FM ',FM(IJL)
   20 CONTINUE
      IF(IOPFE.NE.0) THEN
      WRITE(6,*) ' F2 '
      CALL OUTMXD(F2(1,1,IRL),NSIZ1,NUMSCF,NUMSCF)
      END IF
      DO 30 I=1,NOC
      DO 30 J=1,NOC
      E2(I,J,IRL)=ZERO
      DO 25 K=1,NUMSCF
      E2(I,J,IRL)=E2(I,J,IRL)+F(I,K,IC)*UM(K,J,JC)
     X +F(K,I,JC)*UP(K,J,IC)
   25 CONTINUE
      DO 26 K=1,NOC
      E2(I,J,IRL)=E2(I,J,IRL)
     X   -UP(I,K,IC)*E(J,K,JC)-UM(I,K,JC)*E(K,J,IC)
   26 CONTINUE
   30 CONTINUE
      DO 40 I=1,NUMSCF
      DO 40 J=1,NOC
      IF(I.GT.NOC) THEN
      UP2(I,J,IRL)=UP2(I,J,IRL)+F2(I,J,IRL)
      UM2(I,J,IRL)=UM2(I,J,IRL)+F2(J,I,IRL)
      ELSE
      E2(I,J,IRL)= E2(I,J,IRL) -UP2(I,J,IRL)*(EVAL(J)-EVAL(I))
      END IF
   40 CONTINUE
      IF(IOPFE.GE.2) THEN
      WRITE(6,*) ' E2 '
      CALL OUTMXD(E2(1,1,IRL),NSIZO,NOC,NOC)
      END IF
   50 CONTINUE
      RETURN
      END
