      SUBROUTINE DDIJAB(ICORE,MAXCOR,IUHF)
C
C DRIVER FOR THE FORMATION OF THE 1/D(ijab) ARRAY.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPY(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SHIFT/ ISHIFT,NDRGEO
      NBAS=NOCCO(1)+NVRTO(1)
C
C COMPUTE SIZE OF LARGEST IRREP OF DENOMINATOR ARRAY
C
      MAXAB=-1
      DO 5 ISPIN=3,3-2*IUHF,-1
       LISTD=13+ISPIN + ISHIFT 
       DO 10 IRREP=1,NIRREP
        ITMP1=IRPDPD(IRREP,ISYTYP(1,LISTD))
        ITMP2=IRPDPD(IRREP,ISYTYP(2,LISTD))
        ISIZE=ITMP1*ITMP2
        if (ISIZE.LT.0) call trap_intovf('DDIJAB',1)
        MAXAB=MAX(MAXAB,ISIZE)
10     CONTINUE
5     CONTINUE
C 
C COMPUTE SIZE OF SYMMETRY VECTORS USED IN DDIJAB
C
      ITMP1=NOCCO(1)*NOCCO(1)
      ITMP2=NVRTO(2)*NVRTO(2)
      ISIZE=ITMP1+ITMP2+2*NIRREP
      I000=1
      I010=I000+2*IINTFP*NBAS
      I020=I010+IINTFP*MAXAB
      I030=I020+ISIZE
      if (I030.LT.1) call trap_intovf('DDIJAB',2)
      CALL DIJAB(ICORE(I000),ICORE(I010),ICORE(I020),NBAS,IUHF)
      RETURN
      END
