      SUBROUTINE SXF(IRREPX,FD,F,SD,NUM)
C
C THIS ROUTINE CALCULATES THE FOLLOWING CONTRIBUTIONS
C TO THE ROHF-FOCK MATRIX DERIVATIVES
C
C   - 1/2 SUM R f(P,R) S(R,Q)^chi - 1/2 SUM R S(R,P)^chi f(R,Q)
C
C P,Q,R, ARE EITHER OCCUPIED OR VIRTUAL
C
CEND
C
C CODED APRIL/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DIRPRD
C
      DIMENSION FD(1),F(1),SD(1),NUM(8)
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
C
      DATA ONE,HALFM /1.D0,-0.5D0/ 
C
C LOOP OVER ALL IRREPS
C
      IOFFFD=1
      IOFFR=1
C
      DO 1000 IRREPR=1,NIRREP
C
       IRREPL=DIRPRD(IRREPX,IRREPR)
C
       IOFFL=1
       IOFFS=1
       DO 10 IRREP1=1,IRREPL-1
        IRREP2=DIRPRD(IRREP1,IRREPX)
        IOFFL=IOFFL+NUM(IRREP1)*NUM(IRREP1)
        IOFFS=IOFFS+NUM(IRREP1)*NUM(IRREP2)
10     CONTINUE
C
       NUMR=NUM(IRREPR)
       NUML=NUM(IRREPL)
C
C MULTIPLY BY RIGHT
C
       CALL XGEMM('T','N',NUML,NUMR,NUMR,HALFM,
     &            SD(IOFFS),NUMR,F(IOFFR),NUMR,
     &            ONE,FD(IOFFFD),NUML)
C
C MULTIPLY BY LEFT
C
       CALL XGEMM('N','N',NUML,NUMR,NUML,HALFM,
     &            F(IOFFL),NUML,SD(IOFFFD),NUML,
     &            ONE,FD(IOFFFD),NUML)
C
       IOFFFD=IOFFFD+NUML*NUMR
       IOFFR=IOFFR+NUMR*NUMR
C
1000  CONTINUE
C
      RETURN
      END
