      SUBROUTINE SXF3(IRREPX,FDAI,FAI,SDIJ,POP,VRT)
C
C THIS ROUTINE CALCULATES THE FOLLOWING CONTRIBUTIONS
C TO THE ROHF-FOCK MATRIX DERIVATIVES
C
C   - SUM J S(I,J)^chi F(A,J)
C
CEND
C
C CODED APRIL/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      INTEGER DIRPRD,POP,VRT
C
      DIMENSION SDIJ(1),FAI(1)
      DIMENSION FDAI(1),POP(8),VRT(8)
C
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
C
      DATA ONE,ONEM,HALFM /1.D0,-1.0D0,-0.5D0/ 
C
C LOOP OVER ALL IRREPS
C
      IOFFFD=1
      IOFFSIJ=1
C
      DO 1000 IRREPR=1,NIRREP
C
       IRREPL=DIRPRD(IRREPX,IRREPR)
C
       NUMR=POP(IRREPR)
       NUML=VRT(IRREPL)
       NUMOL=POP(IRREPL)
C
       IOFFAI2=1
       DO 10 IRREP=1,IRREPL-1
        IOFFAI2=IOFFAI2+POP(IRREP)*VRT(IRREP)
10     CONTINUE
C
C MULTIPLY BY RIGHT
C
       CALL XGEMM('N','N',NUML,NUMR,NUMOL,ONEM,
     &            FAI(IOFFAI2),NUML,SDIJ(IOFFSIJ),
     &            NUMOL,ONE,FDAI(IOFFFD),NUML)
C
       IOFFSIJ=IOFFSIJ+NUMOL*NUMR
       IOFFFD=IOFFFD+NUML*NUMR
C
1000  CONTINUE
C
      RETURN
      END
