      
C FOR RHF, THIS ROUTINE COMPUTES Q+Q(t), WHERE Q IS A RING INCREMENT
C AND OVERWRITES THE Q INCREMENT ON DISK.

      SUBROUTINE RHFQ(SCR,NSIZSC,LSTSCR)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      DIMENSION SCR(NSIZSC)

      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      INTEGER DIRPRD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)

      DO IRREP=1,NIRREP
         NROW=IRPDPD(IRREP,ISYTYP(1,LSTSCR))
cYAU         NCOL=NROW
cYAU         NSIZI=NROW*NCOL
         CALL GETLST(SCR,1,NROW,1,IRREP,LSTSCR)
         CALL MPMT(SCR,NROW)
         CALL PUTLST(SCR,1,NROW,1,IRREP,LSTSCR)
      END DO

      RETURN
      END

