      SUBROUTINE DENWT01(ICORE,MAXCOR,IUHF,SING)
C
C DRIVER FOR 0,1 SECTOR DENOMINATOR WEIGHTING
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL SING
      DIMENSION ICORE(MAXCOR)
C
      COMMON /INFO/ NOCCO(2),NVRTO(2)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /FSSYM/ POPA(8,2),POPI(8,2),VRTA(8,2),VRTI(8,2),
     &               NTAN(2),NTNA(2),NTAA(2),
     &               NTIN(2),NTNI(2),NTII(2),
     &               NTAI(2),NTIA(2),
     &               NF1AN(2),NF1AA(2),NF1IN(2),NF1II(2),NF1AI(2),
     &               NF2AN(2),NF2AA(2),NF2IN(2),NF2II(2),NF2AI(2)
C
      NBAS=NOCCO(1)+NVRTO(1)
      I000=1
      I010=I000+2*NBAS*IINTFP
      IF(SING)THEN
       CALL DENW101(ICORE(I000),ICORE(I010),IUHF,NBAS)
      ENDIF
      CALL DENW201(ICORE(I000),ICORE(I010),IUHF,NBAS)
      RETURN
      END
