      SUBROUTINE EXTPRT(ICORE,MAXCOR,IUHF,RLECYC,SINGLE,IENTRY,
     &                   RLETYP,LAMBDA)
C
C UPDATES THE RLE T AMPLITUDE AREA.
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL SINGLE,NONHF,LAMBDA
      DIMENSION ICORE(MAXCOR)
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NF(2),NF1(2)
      COMMON /SYMINF/ NSTART,NIRREP,IRRPES(255,2),DIRPRD(8,8)
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
      COMMON /EXTIO/ IOLDEST
      MAXORD=IFLAGS(12)
      IF(IENTRY.EQ.-1)THEN
      DO 100 ISPIN=4,4-3*IUHF,-1
       IOFF=1
       DO 101 IRREP=1,NIRREP
        IF(ISPIN.NE.3)THEN
         NUMDIS=FSDPDAN(IRREP,ISYTYP(2,95+ISPIN))
         CALL FSGET (ICORE(IOFF),1,NUMDIS,1,IRREP,95+ISPIN,'NNAN')
        ELSE
         NUMDIS=FSDPDNA(IRREP,ISYTYP(2,95+ISPIN))
         CALL FSGET (ICORE(IOFF),1,NUMDIS,1,IRREP,95+ISPIN,'NNNA')
        ENDIF
        DISSIZ =IRPDPD (IRREP,ISYTYP(1,95+ISPIN))
        IOFF=IOFF+NUMDIS*DISSIZ*IINTFP
101    CONTINUE
       IF(ISPIN.LT.3.OR.IUHF.EQ.0)THEN
        CALL FSGETT1(ICORE(IOFF),MIN(1+IUHF,ISPIN),94,
     &               'AI',20+MIN(1+IUHF,ISPIN))
       ENDIF
       CALL PUTLST(ICORE,1,1,1,ISPIN,77)
       IF(RLETYP.EQ.2)CALL PUTLST(ICORE,1,1,1,ISPIN+4,77)
c       CALL PUTLST(ICORE,1,1,1,ISPIN,89)
       IOLDEST=2
100   CONTINUE
      RETURN
      ENDIF 
C
c      DO 10 IDIST=1+MIN(MAXORD,RLECYC-1),2,-1
c       DO 20 ISPIN=4,4-3*IUHF,-1
c        CALL GETLST(ICORE,IDIST-1,1,1,ISPIN,77)
c        CALL PUTLST(ICORE,IOLDEST,1,1,ISPIN,77)
c        IF(RLETYP.EQ.2)THEN
c         CALL GETLST(ICORE,IDIST-1,1,1,ISPIN+4,77)
c         CALL PUTLST(ICORE,IOLDEST,1,1,ISPIN+4,77)
c        ENDIF
c20     CONTINUE
c10    CONTINUE
      DO 30 ISPIN=4,4-3*IUHF,-1
       IOFF=1
       DO 102 IRREP=1,NIRREP
        DISSIZ =IRPDPD (IRREP,ISYTYP(1,95+ISPIN))
        IF(ISPIN.NE.3)THEN
         NUMDIS=FSDPDAN(IRREP,ISYTYP(2,95+ISPIN))
         CALL FSGET (ICORE(IOFF),1,NUMDIS,1,IRREP,95+ISPIN,'NNAN')
        ELSE
         NUMDIS=FSDPDNA(IRREP,ISYTYP(2,95+ISPIN))
         CALL FSGET (ICORE(IOFF),1,NUMDIS,1,IRREP,95+ISPIN,'NNNA')
        ENDIF
        IOFF=IOFF+NUMDIS*DISSIZ*IINTFP
102    CONTINUE
       IF(ISPIN.LT.3.OR.IUHF.EQ.0)THEN
        CALL FSGETT1(ICORE(IOFF),MIN(1+IUHF,ISPIN),94,
     &               'AI',20+MIN(1+IUHF,ISPIN))
       ENDIF
       CALL PUTLST(ICORE,IOLDEST,1,1,ISPIN,77)
30    CONTINUE
      IOLDEST=1+MOD(IOLDEST,MAXORD+1)
      RETURN
      END
