      SUBROUTINE FSGETT1(Z,ILIST1,ILIST2,IOTYPE,SYMTYP)
C
C THIS ROUTINE READS A "STANDARD" TWO INDEX LIST IN A
C NONSTANDARD WAY.  IT ALLOWS ONE TO READ LISTS OF THE TYPE:
C
C           W(PQ)  WITH IOTYPE = 'N1'
C
C WHERE 1 IS A SPECIAL TYPE OF ORBITAL (ACTIVE OR INACTIVE).  ANY
C INDEX CAN REFER TO A "SPECIAL" ORBITAL
C
C  'N' - NORMAL CASE.  READ ALL ORBITALS OF THIS TYPE
C  'A' - ACTIVE ORBITALS ONLY.
C  'I' - INACTIVE ORBITALS ONLY.
C
CEND
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION Z(1)
      CHARACTER*2 IOTYPE
      CHARACTER*1 TYPE1,TYPE2
      COMMON // ICORE(1)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FSIOLOC/ IFSPOS(8,22,8),ISCRLC
      COMMON /SYMPOP  / IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /FSSYMPOP/ FSDPDAN(8,22),FSDPDNA(8,22),FSDPDAA(8,22),
     &                  FSDPDIN(8,22),FSDPDNI(8,22),FSDPDII(8,22),
     &                  FSDPDAI(8,22),FSDPDIA(8,22)
C
      IOFF=1
C
      TYPE1=IOTYPE(1:1)
      TYPE2=IOTYPE(2:2)
C
C DISTINGUISH INDEX TYPE AND SET UP POINTER ADDRESS
C
      IF(TYPE1.EQ.'A'.AND.TYPE2.EQ.'N')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,1)
       NSIZE=FSDPDAN(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'N'.AND.TYPE2.EQ.'A')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,2)
       NSIZE=FSDPDNA(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'A'.AND.TYPE2.EQ.'A')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,3)
       NSIZE=FSDPDAA(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'I'.AND.TYPE2.EQ.'N')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,4)
       NSIZE=FSDPDIN(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'N'.AND.TYPE2.EQ.'I')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,5)
       NSIZE=FSDPDNI(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'I'.AND.TYPE2.EQ.'I')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,6)
       NSIZE=FSDPDII(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'A'.AND.TYPE2.EQ.'I')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,7)
       NSIZE=FSDPDAI(1,SYMTYP)
      ELSEIF(TYPE1.EQ.'I'.AND.TYPE2.EQ.'A')THEN
       IPOSLEFT=IFSPOS(1,SYMTYP,8)
       NSIZE=FSDPDIA(1,SYMTYP)
      ENDIF
C
      CALL GETLST(ICORE(ISCRLC),1,1,1,ILIST1,ILIST2)
      CALL GATHER(NSIZE,Z,ICORE(ISCRLC),ICORE(IPOSLEFT))
C
      RETURN
      END
