      SUBROUTINE ADDHES(HESS,HESMOL,NCOORD)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION HESS(NCOORD*NCOORD),HESMOL(NCOORD*NCOORD)
      DO 100 I = 1, NCOORD*NCOORD
            HESMOL(I) = HESMOL(I) + HESS(I)
  100 CONTINUE
      RETURN
      END
