


                 

      SUBROUTINE BFLUSH(BUCK,IBUCK,NINBCK,IBKSIZ,NUMBUF)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      CHARACTER*8 NAME
      LOGICAL EXIST 
      COMMON/BFILE/IUNIT(24),NAME(24),EXIST(12)
      DIMENSION BUCK(IBKSIZ,NUMBUF),IBUCK(IBKSIZ,NUMBUF)
      DIMENSION NINBCK(NUMBUF)
      DO 10 NBUCK=1,NUMBUF
       IF(EXIST(NBUCK)) THEN
        IF(NINBCK(NBUCK).NE.0) THEN
         CALL WRSEQ(IUNIT(NBUCK),BUCK(1,NBUCK),IBUCK(1,NBUCK),
     &              NINBCK(NBUCK),IBKSIZ)
        ENDIF
        NINBCK(NBUCK)=-1
        CALL WRSEQ(IUNIT(NBUCK),BUCK(1,NBUCK),IBUCK(1,NBUCK),
     &             NINBCK(NBUCK),IBKSIZ)
       ENDIF
10    CONTINUE
C
      RETURN
      END
