      SUBROUTINE GABAB1(NIRREP,NTYPE,TYPE,NBAS,IOFFL,
     &           MULT,NRCSH,KHKTSH,INDGEN,ISTBSH,
     &           ISHLD,NNIJ,IJADD,
     &           NSTSH,NENDSH,
     &           BUF,SORT)
C
C  GABAB1 PERFORMS THE SORT OF THE GAMMA ELEMENTS OF SYMMETRY TYPE
C  ABAB. THIS IS THE INCORE VERSION
C 
CEND
C
C  CODED DEC/90/JG
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER AND,OR,XOR
      PARAMETER (IBIT08 = 255)
      INTEGER P, Q, R, S, PQ, RS, PQRS
      INTEGER TYPE
C
      DIMENSION NBAS(8),IOFFL(8) 
      DIMENSION TYPE(4,42,4)
      DIMENSION MULT(0:7),NRCSH(1),KHKTSH(1),INDGEN(1),ISTBSH(1)
      DIMENSION ISHLD(1),NNIJ(1),IJADD(1),NSTSH(8,1),NENDSH(8,1)
      DIMENSION BUF(1),SORT(1)
C
C  COMMON /MACHSP/ CONTAINS MACHINE DEPENDENT STUFF
C
      COMMON /MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
C STATEMENT FUNCTIONS FOR PACKING, UNPACKING AND ADDRESSING 
C
      IBTAND(I,J) = AND(I,J)
      IBTSHL(I,J) = ISHFT(I,J)
      IBTSHR(I,J) = ISHFT(I,-J)
      IPART(I,J) = IBTAND(IBTSHR(I,8*(J-1)),IBIT08)
      ISHLL(I)   = IBTAND(I,IBIT08)
      ICONTR(I)  = IBTAND(IBTSHR(I,8),IBIT08)
      IANG(I)    = IBTAND(IBTSHR(I,16),IBIT08)
      JRREP(I)   = IBTAND(IBTSHR(I,24),IBIT08)
      ICR1(I,J,K,L) = NRCP*(NRCQ*(NRCR*(L-1)+K-1)+J-1)+I
      IAR1(I,J,K,L) = KHKTP*(KHKTQ*(KHKTR*(L-1)+K-1)+J-1)+I
      IRR1(I,J,K,L) = MULP*(MULQ*(MULR*(L)+K)+J)+I+1
      ICR2(I,J,K,L) = NRCQ*(NRCP*(NRCS*(L-1)+K-1)+J-1)+I
      IAR2(I,J,K,L) = KHKTQ*(KHKTP*(KHKTS*(L-1)+K-1)+J-1)+I
      IRR2(I,J,K,L) = MULQ*(MULP*(MULS*(L)+K)+J)+I+1
      ICR3(I,J,K,L) = NRCP*(NRCQ*(NRCS*(L-1)+K-1)+J-1)+I
      IAR3(I,J,K,L) = KHKTP*(KHKTQ*(KHKTS*(L-1)+K-1)+J-1)+I
      IRR3(I,J,K,L) = MULP*(MULQ*(MULS*(L)+K)+J)+I+1
      ICR4(I,J,K,L) = NRCQ*(NRCP*(NRCR*(L-1)+K-1)+J-1)+I
      IAR4(I,J,K,L) = KHKTQ*(KHKTP*(KHKTR*(L-1)+K-1)+J-1)+I
      IRR4(I,J,K,L) = MULQ*(MULP*(MULR*(L)+K)+J)+I+1
      IADDRS(I,J,K) = NRCTOT*(MULTOT*(K-1)+J-1)+I
C
C  LOOP OVER ALL AABB SYMMETRY TYPES
C
        DO 100 IND=1,NTYPE
C
C  RESET THE COUNTER TO ZERO
C
         KCOUNT=0
C
C  DETERMINE THE IRREPS FOR THE CURRENT LOOP
C
         IRREP1=TYPE(3,IND,1)
         IRREP2=TYPE(3,IND,2)
C
C  DETERMINE THE NUMBER OF BASIS FUNCTIONS FOR THIS LOOP
C
         NBAS1=NBAS(IRREP1)
         NBAS2=NBAS(IRREP2)
C
C  DETERMINE OFFSETS FOR THE BASIS FUNCTIONS FOR THIS LOOP
C
         IOFFL1=IOFFL(IRREP1)
         IOFFL2=IOFFL(IRREP2)
C
C  LOOP OVER FIRST INDEX (P)
C
         DO 100 L1=IOFFL1+1,IOFFL1+NBAS1
C
C  GET PARAMETERS FOR THIS ORBITAL
C
          LAB1=INDGEN(L1)
          P=ISHLL(LAB1)
          MULP=MULT(ISTBSH(P))
          NRCP=NRCSH(P)
          KHKTP=KHKTSH(P)
          IP=ICONTR(LAB1)
          KP=IANG(LAB1)
          NP=JRREP(LAB1)
C
C  LOOP OVER SECOND INDEX (Q)
C
          DO 100 L2=IOFFL2+1,IOFFL2+NBAS2
C
C  GET PARAMETERS FOR THIS ORBITAL
C
           LAB2=INDGEN(L2)
           Q=ISHLL(LAB2)
           MULQ=MULT(ISTBSH(Q))
           NRCQ=NRCSH(Q)
           KHKTQ=KHKTSH(Q)
           IQ=ICONTR(LAB2)
           KQ=IANG(LAB2)
           NQ=JRREP(LAB2)
C
C  GET ADRESS OF SHELL COMBINATIONS P,Q
C
           IF(P.GE.Q) THEN
            PQ=(P*(P-1))/2+Q  
           ELSE
            PQ=(Q*(Q-1))/2+P
           ENDIF
C
C GET ADRESS WQHICH CORRESPONDS TO THE SHELLS PQ ON THE LEFT SIDE
C
           ISHLADPQ=0
           IF(PQ.NE.1) THEN 
            MAXPQ=PQ-1
            DO 301 M=1,MAXPQ
c             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M)
             ISHLADPQ=ISHLADPQ+NNIJ(M)*IJADD(M+1)
301         CONTINUE
           ENDIF
c            ISHLADPQ=ISHLD(PQ)
C
C  PICK UP A LIST FROM THE AOGAM VERSION OF MOINTS
C  INCREMENT FIRST KCOUNT
C
           KCOUNT=KCOUNT+1
C
           CALL GETLST(BUF,KCOUNT,1,1,3,IND)
C
           IF(P.GE.Q) THEN
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 200 L3=IOFFL1+1,NENDSH(IRREP1,P)
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP2,R) 
C
            IF(R.EQ.P) NMAX4=NENDSH(IRREP2,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 300 L4=IOFFL2+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL1-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR1(NRCP,NRCQ,NRCR,NRCS)
c              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,MULS-1)
              MULTOT=IRR1(MULP-1,MULQ-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR1(IP,IQ,IR,IS),
c     &             IRR1(NP,NQ,NR,NS),
     &             IRR1(NP,NQ,NR,0),
     &             IAR1(KP,KQ,KR,KS))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
300          CONTINUE
C
200         CONTINUE
C
C 
C REPEAT THE WHOLE PROCEDURE WITH L1 AND L2 INTERCHANGED
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 1200 L4=IOFFL2+1,NENDSH(IRREP2,P)
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB4=INDGEN(L4)
            S=ISHLL(LAB4)
            MULS=MULT(ISTBSH(S))
            NRCS=NRCSH(S)
            KHKTS=KHKTSH(S)
            IS=ICONTR(LAB4)
            KS=IANG(LAB4)
            NS=JRREP(LAB4)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX3=NENDSH(IRREP1,S)
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
             IF(P.EQ.S) NMAX3=NENDSH(IRREP1,Q)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1300 L3=IOFFL1+1,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL1-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
              ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR3(NRCP,NRCQ,NRCS,NRCR)
c              MULTOT=IRR3(MULP-1,MULQ-1,MULS-1,MULR-1)
              MULTOT=IRR3(MULP-1,MULQ-1,MULS-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR3(IP,IQ,IS,IR),
c     &             IRR3(NP,NQ,NS,NR),
     &             IRR3(NP,NQ,NS,0),
     &             IAR3(KP,KQ,KS,KR))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1300         CONTINUE
C
1200        CONTINUE
            ENDIF
C
C NOW TREAT AS WELL THE CASE P LE Q 
C
            IF(P.LE.Q) THEN 
C 
C REPEAT THE WHOLE PROCEDURE WITH L1 AND L2 INTERCHANGED
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 1500 L3=IOFFL1+1,NENDSH(IRREP1,Q)
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB3=INDGEN(L3)
            R=ISHLL(LAB3)
            MULR=MULT(ISTBSH(R))
            NRCR=NRCSH(R)
            KHKTR=KHKTSH(R)
            IR=ICONTR(LAB3)
            KR=IANG(LAB3)
            NR=JRREP(LAB3)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX4=NENDSH(IRREP2,R) 
C
            IF(R.EQ.Q) NMAX4=NENDSH(IRREP2,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 1600 L4=IOFFL2+1,NMAX4
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB4=INDGEN(L4)
              S=ISHLL(LAB4)
              MULS=MULT(ISTBSH(S))
              NRCS=NRCSH(S)
              KHKTS=KHKTSH(S)
              IS=ICONTR(LAB4)
              KS=IANG(LAB4)
              NS=JRREP(LAB4)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL1-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(R*(R-1))/2+S
C
C SHELL INDEX R IS ALWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
              ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR4(NRCQ,NRCP,NRCR,NRCS)
c              MULTOT=IRR4(MULQ-1,MULP-1,MULR-1,MULS-1)
              MULTOT=IRR4(MULQ-1,MULP-1,MULR-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR4(IQ,IP,IR,IS),
c     &             IRR4(NQ,NP,NR,NS),
     &             IRR4(NQ,NP,NR,0),
     &             IAR4(KQ,KP,KR,KS))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
1600          CONTINUE
C
1500         CONTINUE
C
C LOOP OVER ALL ELEMENTS IN THIS BUFFER WHICH ARE NEEDED
C
           DO 500 L4=IOFFL2+1,NENDSH(IRREP2,Q)
C
C  GET PARAMETERS OF THIRD ORBITAL
C
            LAB4=INDGEN(L4)
            S=ISHLL(LAB4)
            MULS=MULT(ISTBSH(S))
            NRCS=NRCSH(S)
            KHKTS=KHKTSH(S)
            IS=ICONTR(LAB4)
            KS=IANG(LAB4)
            NS=JRREP(LAB4)
C
C SET LIMITS FOR FOURTH INDEX ( ASURES SHELL R GE SHELL S ONLY)
C
            NMAX3=NENDSH(IRREP1,S)
C
C  CHECK CANONICAL ORDER, IF R LT P THE ORDER IS FIXED
C
             IF(Q.EQ.S) NMAX3=NENDSH(IRREP1,P)
C
C  LOOP OVER FOURTH INDEX
C
             DO 600 L3=IOFFL1+1,NMAX3
C
C  GET PARAMETERS FOR FOURTH ORBITAL
C
              LAB3=INDGEN(L3)
              R=ISHLL(LAB3)
              MULR=MULT(ISTBSH(R))
              NRCR=NRCSH(R)
              KHKTR=KHKTSH(R)
              IR=ICONTR(LAB3)
              KR=IANG(LAB3)
              NR=JRREP(LAB3)
C
C GET ADRESS OF THE REQUIRED GAMMA ELEMENT
C
              INDEX=(L4-IOFFL2)+(L3-IOFFL1-1)*NBAS2
C
C ADRESS FOR SHELL COMBINATIONS R,S
C
              RS=(S*(S-1))/2+R
C
C SHELL INDEX R IS LAWAYS GE S
C
C FINAL ADRESS IN FULL LIST OF SHELLS P,Q,R,S
C
              PQRS=(PQ*(PQ-1))/2+RS
C
C STARTING ADRESS OF SHELL COMBINATION P,Q,R,S IN THE LIST OF GAMMAS
C
c              ISHLAD=ISHLADPQ
c              IF(RS.NE.1) THEN
c               ISHLAD=ISHLAD+NNIJ(PQ)*IJADD(RS-1)
c              ENDIF
               ISHLAD=ISHLADPQ+NNIJ(PQ)*IJADD(RS)
C
C COMPUTE SORT ADRESS AND OFFSET
C
              NRCTOT=ICR2(NRCQ,NRCP,NRCS,NRCR)
c              MULTOT=IRR2(MULQ-1,MULP-1,MULS-1,MULR-1)
              MULTOT=IRR2(MULQ-1,MULP-1,MULS-1,0)
C
C ILOC IS THE ADRESS OF THIS ELEMENT IN THE CHAINING AREA
C
              ILOC=ISHLAD+IADDRS(ICR2(IQ,IP,IS,IR),
c     &             IRR2(NQ,NP,NS,NR),
     &             IRR2(NQ,NP,NS,0),
     &             IAR2(KQ,KP,KS,KR))
C
              SORT(ILOC)=BUF(INDEX)
C
C  END OF S LOOP FOR P GT R CASE
C
600         CONTINUE
C
500        CONTINUE
C
         ENDIF
C
100     CONTINUE
C
       RETURN
       END
