











C SUBROUTINE TO EVALUATE FOURTH-ORDER ENERGY FROM TRIPLES
C AMPLITUDES AND DENOMINATORS FOR GIVEN IJK.

c#define _DEBUG_E4TCTDIJK

      SUBROUTINE E4TCTDIJK(T3C,T3D,D3,LENGTH,DIJK,E4TRIP,caller)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION T3C(LENGTH), D3(LENGTH), T3D(LENGTH)
      character*(*) caller
      INTEGER ABC
      DO ABC = 1, LENGTH
         E4TRIP = E4TRIP + (DIJK - D3(ABC)) * T3C(ABC) * T3D(ABC)
      END DO
      RETURN
      END

