      SUBROUTINE T3WT314R(D3T3EXP,CORE,MAXCOR,ISPIN,LENEXP,
     1                    IADBLK,IRPI,IRPJ,IRPK,I,J,K,IRPIJK)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER VRT,POP,DIRPRD,DISSIZ,DISTSZ
      LOGICAL NONEQL,
     1        MJKEQL,MJEQL,MKEQL,JKEQL,MIKEQL,MIEQL,IKEQL,
     1        MIJEQL,            IJEQL
      DIMENSION D3T3EXP(LENEXP),CORE(1)
      DIMENSION IADBLK(8)
      DIMENSION IADT(8),LENT(8)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NT1(2),NFMI(2),NFEA(2)
      COMMON /FLAGS/  IFLAGS(100)
      EQUIVALENCE(ICLLVL,IFLAGS( 2))
      EQUIVALENCE(IDRLVL,IFLAGS( 3))
      COMMON /FILES/  LUOUT,MOINTS
C
      COMMON /AUXIO/  DISTSZ(8,100),NDISTS(8,100),INIWRD(8,100),LNPHYR,
     1                NRECS,LUAUX
      COMMON /T3OFF/  IOFFVV(8,8,10),IOFFOO(8,8,10),IOFFVO(8,8,4)
      COMMON /T3IOOF/ IJKPOS(8,8,8,2),IJKLEN(36,8,4),IJKOFF(36,8,4),
     1                NCOMB(4)
C
      INDEX(I) = I*(I-1)/2
C
      DO  100 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 100
      IF(POP(IRPM,ISPIN).LT.2.AND.(IRPM.EQ.IRPJ. OR.IRPM.EQ.IRPK))
     1                         GOTO 100
      IF(POP(IRPM,ISPIN).LT.3.AND. IRPM.EQ.IRPJ.AND.IRPM.EQ.IRPK )
     1                         GOTO 100
C
      IF(IRPM.LE.IRPJ) MJKPOS = IJKPOS(IRPM,IRPJ,IRPK,1)
      IF(IRPM.GE.IRPK) MJKPOS = IJKPOS(IRPJ,IRPK,IRPM,1)
      IF(IRPJ.LE.IRPM.AND.IRPM.LE.IRPK)
     1                 MJKPOS = IJKPOS(IRPJ,IRPM,IRPK,1)
C
      MJKEQL = .FALSE.
      NONEQL = .FALSE.
      MJEQL  = .FALSE.
      MKEQL  = .FALSE.
      JKEQL  = .FALSE.
      MJKEQL = IRPM.EQ.IRPJ.AND.IRPM.EQ.IRPK
      NONEQL = IRPM.NE.IRPJ.AND.IRPM.NE.IRPK.AND.IRPJ.NE.IRPK
      MJEQL  = IRPM.EQ.IRPJ.AND.IRPM.NE.IRPK
      MKEQL  = IRPM.EQ.IRPK.AND.IRPM.NE.IRPJ
      JKEQL  = IRPJ.EQ.IRPK.AND.IRPM.NE.IRPJ
C
      IRPJK  = DIRPRD(IRPJ,IRPK)
      IRPMJK = DIRPRD(IRPM,IRPJK)
C
      IOFF   = IJKOFF(MJKPOS,IRPMJK,1 + (ISPIN-1)*3)
C
      LN    = DISTSZ(IRPMJK,1 + 3*(ISPIN-1) + 4)
      LNEXP = 0
      DO 10 IRREP=1,NIRREP
      JRREP = DIRPRD(IRREP,IRPMJK)
      LNEXP = LNEXP + IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
      LENT(IRREP)   = IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
   10 CONTINUE
C
      DO 20 IRREP=1,NIRREP
      IF(IRREP.EQ.1)THEN
      IADT(IRREP) = 1
      ELSE
      IADT(IRREP) = IADT(IRREP-1) + LENT(IRREP-1)
      ENDIF
   20 CONTINUE
C
C     I000 -  W(C,E)
C     I010 - T3(A<B<E)
C     I020 - T3(A<B,E)
C
      IRPMI = DIRPRD(IRPI,IRPM)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMI,18 + ISPIN)
      I020 = I010 + LN
      I030 = I020 + LNEXP
      NEED = IINTFP * I030
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
 1010 FORMAT(' @T3WT314R-F, Insufficient memory. Need ',I10,' Got ',I10)
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO   90    M=1,POP(IRPM,ISPIN)
C
      SIGN =  1.0D+00
C
      IF(MJKEQL.AND.(M.EQ.J.OR.M.EQ.K)) GOTO 90
      IF(MJEQL .AND. M.EQ.J           ) GOTO 90
      IF(MKEQL .AND. M.EQ.K           ) GOTO 90
C
      MI = IOFFOO(IRPI,IRPMI,2+ISPIN) + (I-1)*POP(IRPM,ISPIN) + M
      LISTW = 53 + ISPIN
      CALL GETLST(CORE(I000),MI,1,2,IRPMI,LISTW)
C
      IF(NONEQL)THEN
       IF(IRPM.LT.IRPJ)THEN
       MJKVAL = IOFF + (K-1)*POP(IRPJ,ISPIN)*POP(IRPM,ISPIN) +
     1                 (J-1)*POP(IRPM,ISPIN) + M
       ENDIF
       IF(IRPM.GT.IRPK)THEN
       MJKVAL = IOFF + (M-1)*POP(IRPK,ISPIN)*POP(IRPJ,ISPIN) +
     1                 (K-1)*POP(IRPJ,ISPIN) + J
       ENDIF
       IF(IRPM.GT.IRPJ.AND.IRPM.LT.IRPK)THEN
       MJKVAL = IOFF + (K-1)*POP(IRPM,ISPIN)*POP(IRPJ,ISPIN) +
     1                 (M-1)*POP(IRPJ,ISPIN) + J
       SIGN = - SIGN
       ENDIF
      ENDIF
C
      IF(MJKEQL)THEN
      MAXVAL = MAX(M,J,K)
      MINVAL = MIN(M,J,K)
      IF(M.GT.K) MIDVAL = K
      IF(M.LT.J) MIDVAL = J
      IF(M.GT.J.AND.M.LT.K)THEN
      MIDVAL = M
      SIGN = - SIGN
      ENDIF
      MJKVAL = IOFF + ((MAXVAL-1)*(MAXVAL-2)*(MAXVAL-3))/6 +
     1                INDEX(MIDVAL-1) + MINVAL
      ENDIF
C
      IF(MJEQL)THEN
       IF(M.LT.J)THEN
       MJ = INDEX(J-1) + M
       ELSE
       MJ = INDEX(M-1) + J
       SIGN = - SIGN
       ENDIF
       MJKVAL = IOFF + (K-1)*((POP(IRPM,ISPIN)*(POP(IRPM,ISPIN)-1))/2)
     1               + MJ
      ENDIF
C
      IF(MKEQL)THEN
       IF(M.LT.K)THEN
       MK = INDEX(K-1) + M
       SIGN = - SIGN
       ELSE
       MK = INDEX(M-1) + K
       ENDIF
       MJKVAL = IOFF + (MK-1)*POP(IRPJ,ISPIN) + J
      ENDIF
C
      IF(JKEQL)THEN
       IF(IRPM.GT.IRPK)THEN
       MJKVAL = IOFF + (M-1)*((POP(IRPK,ISPIN)*(POP(IRPK,ISPIN)-1))/2)
     1               + INDEX(K-1) + J
       ELSE
       MJKVAL = IOFF + (INDEX(K-1) + J - 1)*POP(IRPM,ISPIN) + M
       ENDIF
      ENDIF
C
      CALL GETLIST(CORE(I010),MJKVAL,1,1,IRPMJK,1 + 3*(ISPIN-1) + 4)
C
      CALL ZERO(CORE(I020),LNEXP)
      CALL SYMEXPT3(CORE(I010),CORE(I020),IADT,ISPIN,IRPMJK)
C
      IOFFT = I020
      DO 80 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN).EQ.0) GOTO 80
C
      IRPC  = DIRPRD(IRPE,IRPMI)
      IRPCE = IRPMI
C     IOFFW = IOFFVV(IRPE,IRPCE,ISPIN + 2) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,ISPIN + 2) + 1
      IRPAB = DIRPRD(IRPE,IRPMJK)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
   80 CONTINUE
   90 CONTINUE
  100 CONTINUE
C
      DO  200 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 200
      IF(POP(IRPM,ISPIN).LT.2.AND.(IRPM.EQ.IRPI. OR.IRPM.EQ.IRPK))
     1                         GOTO 200
      IF(POP(IRPM,ISPIN).LT.3.AND. IRPM.EQ.IRPI.AND.IRPM.EQ.IRPK )
     1                         GOTO 200
C
      IF(IRPM.LE.IRPI) MIKPOS = IJKPOS(IRPM,IRPI,IRPK,1)
      IF(IRPM.GE.IRPK) MIKPOS = IJKPOS(IRPI,IRPK,IRPM,1)
      IF(IRPI.LE.IRPM.AND.IRPM.LE.IRPK)
     1                 MIKPOS = IJKPOS(IRPI,IRPM,IRPK,1)
C
      MIKEQL = .FALSE.
      NONEQL = .FALSE.
      MIEQL  = .FALSE.
      MKEQL  = .FALSE.
      IKEQL  = .FALSE.
      MIKEQL = IRPM.EQ.IRPI.AND.IRPM.EQ.IRPK
      NONEQL = IRPM.NE.IRPI.AND.IRPM.NE.IRPK.AND.IRPI.NE.IRPK
      MIEQL  = IRPM.EQ.IRPI.AND.IRPM.NE.IRPK
      MKEQL  = IRPM.EQ.IRPK.AND.IRPM.NE.IRPI
      IKEQL  = IRPI.EQ.IRPK.AND.IRPM.NE.IRPI
C
      IRPIK  = DIRPRD(IRPI,IRPK)
      IRPMIK = DIRPRD(IRPM,IRPIK)
C
      IOFF   = IJKOFF(MIKPOS,IRPMIK,1 + (ISPIN-1)*3)
C
      LN    = DISTSZ(IRPMIK,1 + 3*(ISPIN-1) + 4)
      LNEXP = 0
      DO 110 IRREP=1,NIRREP
      JRREP = DIRPRD(IRREP,IRPMIK)
      LNEXP = LNEXP + IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
      LENT(IRREP)   = IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
  110 CONTINUE
C
      DO 120 IRREP=1,NIRREP
      IF(IRREP.EQ.1)THEN
      IADT(IRREP) = 1
      ELSE
      IADT(IRREP) = IADT(IRREP-1) + LENT(IRREP-1)
      ENDIF
  120 CONTINUE
C
C     I000 -  W(C,E)
C     I010 - T3(A<B<E)
C     I020 - T3(A<B,E)
C
      IRPMJ = DIRPRD(IRPJ,IRPM)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMJ,18 + ISPIN)
      I020 = I010 + LN
      I030 = I020 + LNEXP
      NEED = IINTFP * I030
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO  190    M=1,POP(IRPM,ISPIN)
C
      SIGN = -1.0D+00
C
      IF(MIKEQL.AND.(M.EQ.I.OR.M.EQ.K)) GOTO 190
      IF(MIEQL .AND. M.EQ.I           ) GOTO 190
      IF(MKEQL .AND. M.EQ.K           ) GOTO 190
C
      MJ = IOFFOO(IRPJ,IRPMJ,2+ISPIN) + (J-1)*POP(IRPM,ISPIN) + M
      LISTW = 53 + ISPIN
      CALL GETLST(CORE(I000),MJ,1,2,IRPMJ,LISTW)
C
      IF(NONEQL)THEN
       IF(IRPM.LT.IRPI)THEN
       MIKVAL = IOFF + (K-1)*POP(IRPI,ISPIN)*POP(IRPM,ISPIN) +
     1                 (I-1)*POP(IRPM,ISPIN) + M
       ENDIF
       IF(IRPM.GT.IRPK)THEN
       MIKVAL = IOFF + (M-1)*POP(IRPK,ISPIN)*POP(IRPI,ISPIN) +
     1                 (K-1)*POP(IRPI,ISPIN) + I
       ENDIF
       IF(IRPM.GT.IRPI.AND.IRPM.LT.IRPK)THEN
       MIKVAL = IOFF + (K-1)*POP(IRPM,ISPIN)*POP(IRPI,ISPIN) +
     1                 (M-1)*POP(IRPI,ISPIN) + I
       SIGN = - SIGN
       ENDIF
      ENDIF
C
      IF(MIKEQL)THEN
      MAXVAL = MAX(M,I,K)
      MINVAL = MIN(M,I,K)
      IF(M.GT.K) MIDVAL = K
      IF(M.LT.I) MIDVAL = I
      IF(M.GT.I.AND.M.LT.K)THEN
      MIDVAL = M
      SIGN = - SIGN
      ENDIF
      MIKVAL = IOFF + ((MAXVAL-1)*(MAXVAL-2)*(MAXVAL-3))/6 +
     1                INDEX(MIDVAL-1) + MINVAL
      ENDIF
C
      IF(MIEQL)THEN
       IF(M.LT.I)THEN
       MI = INDEX(I-1) + M
       ELSE
       MI = INDEX(M-1) + I
       SIGN = - SIGN
       ENDIF
       MIKVAL = IOFF + (K-1)*((POP(IRPM,ISPIN)*(POP(IRPM,ISPIN)-1))/2)
     1               + MI
      ENDIF
C
      IF(MKEQL)THEN
       IF(M.LT.K)THEN
       MK = INDEX(K-1) + M
       SIGN = - SIGN
       ELSE
       MK = INDEX(M-1) + K
       ENDIF
       MIKVAL = IOFF + (MK-1)*POP(IRPI,ISPIN) + I
      ENDIF
C
      IF(IKEQL)THEN
       IF(IRPM.GT.IRPK)THEN
       MIKVAL = IOFF + (M-1)*((POP(IRPK,ISPIN)*(POP(IRPK,ISPIN)-1))/2)
     1               + INDEX(K-1) + I
       ELSE
       MIKVAL = IOFF + (INDEX(K-1) + I - 1)*POP(IRPM,ISPIN) + M
       ENDIF
      ENDIF
C
      CALL GETLIST(CORE(I010),MIKVAL,1,1,IRPMIK,1 + 3*(ISPIN-1) + 4)
C
      CALL ZERO(CORE(I020),LNEXP)
      CALL SYMEXPT3(CORE(I010),CORE(I020),IADT,ISPIN,IRPMIK)
C
      IOFFT = I020
      DO 180 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN).EQ.0) GOTO 180
C
      IRPC  = DIRPRD(IRPE,IRPMJ)
      IRPCE = IRPMJ
C     IOFFW = IOFFVV(IRPE,IRPCE,ISPIN + 2) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,ISPIN + 2) + 1
      IRPAB = DIRPRD(IRPE,IRPMIK)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
  180 CONTINUE
  190 CONTINUE
  200 CONTINUE
C
      DO  300 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN).EQ.0) GOTO 300
      IF(POP(IRPM,ISPIN).LT.2.AND.(IRPM.EQ.IRPI. OR.IRPM.EQ.IRPJ))
     1                         GOTO 300
      IF(POP(IRPM,ISPIN).LT.3.AND. IRPM.EQ.IRPI.AND.IRPM.EQ.IRPJ )
     1                         GOTO 300
C
      IF(IRPM.LE.IRPI) MIJPOS = IJKPOS(IRPM,IRPI,IRPJ,1)
      IF(IRPM.GE.IRPJ) MIJPOS = IJKPOS(IRPI,IRPJ,IRPM,1)
      IF(IRPI.LE.IRPM.AND.IRPM.LE.IRPJ)
     1                 MIJPOS = IJKPOS(IRPI,IRPM,IRPJ,1)
C
      MIJEQL = .FALSE.
      NONEQL = .FALSE.
      MIEQL  = .FALSE.
      MJEQL  = .FALSE.
      IJEQL  = .FALSE.
      MIJEQL = IRPM.EQ.IRPI.AND.IRPM.EQ.IRPJ
      NONEQL = IRPM.NE.IRPI.AND.IRPM.NE.IRPJ.AND.IRPI.NE.IRPJ
      MIEQL  = IRPM.EQ.IRPI.AND.IRPM.NE.IRPJ
      MJEQL  = IRPM.EQ.IRPJ.AND.IRPM.NE.IRPI
      IJEQL  = IRPI.EQ.IRPJ.AND.IRPM.NE.IRPI
C
      IRPIJ  = DIRPRD(IRPI,IRPJ)
      IRPMIJ = DIRPRD(IRPM,IRPIJ)
C
      IOFF   = IJKOFF(MIJPOS,IRPMIJ,1 + (ISPIN-1)*3)
C
      LN    = DISTSZ(IRPMIJ,1 + 3*(ISPIN-1) + 4)
      LNEXP = 0
      DO 210 IRREP=1,NIRREP
      JRREP = DIRPRD(IRREP,IRPMIJ)
      LNEXP = LNEXP + IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
      LENT(IRREP)   = IRPDPD(JRREP,ISPIN) * VRT(IRREP,ISPIN)
  210 CONTINUE
C
      DO 220 IRREP=1,NIRREP
      IF(IRREP.EQ.1)THEN
      IADT(IRREP) = 1
      ELSE
      IADT(IRREP) = IADT(IRREP-1) + LENT(IRREP-1)
      ENDIF
  220 CONTINUE
C
C     I000 -  W(C,E)
C     I010 - T3(A<B<E)
C     I020 - T3(A<B,E)
C
      IRPMK = DIRPRD(IRPK,IRPM)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMK,18 + ISPIN)
      I020 = I010 + LN
      I030 = I020 + LNEXP
      NEED = IINTFP * I030
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO  290    M=1,POP(IRPM,ISPIN)
C
      SIGN =  1.0D+00
C
      IF(MIJEQL.AND.(M.EQ.I.OR.M.EQ.J)) GOTO 290
      IF(MIEQL .AND. M.EQ.I           ) GOTO 290
      IF(MJEQL .AND. M.EQ.J           ) GOTO 290
C
      MK = IOFFOO(IRPK,IRPMK,2+ISPIN) + (K-1)*POP(IRPM,ISPIN) + M
      LISTW = 53 + ISPIN
      CALL GETLST(CORE(I000),MK,1,2,IRPMK,LISTW)
C
      IF(NONEQL)THEN
       IF(IRPM.LT.IRPI)THEN
       MIJVAL = IOFF + (J-1)*POP(IRPI,ISPIN)*POP(IRPM,ISPIN) +
     1                 (I-1)*POP(IRPM,ISPIN) + M
       ENDIF
       IF(IRPM.GT.IRPJ)THEN
       MIJVAL = IOFF + (M-1)*POP(IRPJ,ISPIN)*POP(IRPI,ISPIN) +
     1                 (J-1)*POP(IRPI,ISPIN) + I
       ENDIF
       IF(IRPM.GT.IRPI.AND.IRPM.LT.IRPJ)THEN
       MIJVAL = IOFF + (J-1)*POP(IRPM,ISPIN)*POP(IRPI,ISPIN) +
     1                 (M-1)*POP(IRPI,ISPIN) + I
       SIGN = - SIGN
       ENDIF
      ENDIF
C
      IF(MIJEQL)THEN
      MAXVAL = MAX(M,I,J)
      MINVAL = MIN(M,I,J)
      IF(M.GT.J) MIDVAL = J
      IF(M.LT.I) MIDVAL = I
      IF(M.GT.I.AND.M.LT.J)THEN
      MIDVAL = M
      SIGN = - SIGN
      ENDIF
      MIJVAL = IOFF + ((MAXVAL-1)*(MAXVAL-2)*(MAXVAL-3))/6 +
     1                INDEX(MIDVAL-1) + MINVAL
      ENDIF
C
      IF(MIEQL)THEN
       IF(M.LT.I)THEN
       MI = INDEX(I-1) + M
       ELSE
       MI = INDEX(M-1) + I
       SIGN = - SIGN
       ENDIF
       MIJVAL = IOFF + (J-1)*((POP(IRPM,ISPIN)*(POP(IRPM,ISPIN)-1))/2)
     1               + MI
      ENDIF
C
      IF(MJEQL)THEN
       IF(M.LT.J)THEN
       MJ = INDEX(J-1) + M
       SIGN = - SIGN
       ELSE
       MJ = INDEX(M-1) + J
       ENDIF
       MIJVAL = IOFF + (MJ-1)*POP(IRPI,ISPIN) + I
      ENDIF
C
      IF(IJEQL)THEN
       IF(IRPM.GT.IRPJ)THEN
       MIJVAL = IOFF + (M-1)*((POP(IRPJ,ISPIN)*(POP(IRPJ,ISPIN)-1))/2)
     1               + INDEX(J-1) + I
       ELSE
       MIJVAL = IOFF + (INDEX(J-1) + I - 1)*POP(IRPM,ISPIN) + M
       ENDIF
      ENDIF
C
      CALL GETLIST(CORE(I010),MIJVAL,1,1,IRPMIJ,1 + 3*(ISPIN-1) + 4)
C
      CALL ZERO(CORE(I020),LNEXP)
      CALL SYMEXPT3(CORE(I010),CORE(I020),IADT,ISPIN,IRPMIJ)
C
      IOFFT = I020
      DO 280 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN).EQ.0) GOTO 280
C
      IRPC  = DIRPRD(IRPE,IRPMK)
      IRPCE = IRPMK
C     IOFFW = IOFFVV(IRPE,IRPCE,ISPIN + 2) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,ISPIN + 2) + 1
      IRPAB = DIRPRD(IRPE,IRPMIJ)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
  280 CONTINUE
  290 CONTINUE
  300 CONTINUE
C
C      RETURN
C
C     Now deal with the piece that uses case 2 or case 3 triples.
C
      IF(ISPIN.EQ.1)THEN
      ISPIN1 = 1
      ISPIN2 = 2
      ELSE
      ISPIN1 = 2
      ISPIN2 = 1
      ENDIF
C
      SIGN = 1.0D+00
      DO 400 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN2).EQ.0) GOTO 400
C
      IRPJK  = DIRPRD(IRPJ,IRPK)
      IRPJKM = DIRPRD(IRPJK,IRPM)
C
      JKMPOS = IJKPOS(IRPJ,IRPK,IRPM,2)
      IOFF   = IJKOFF(JKMPOS,IRPJKM,ISPIN1 + 1)
C
      IF(IRPJ.EQ.IRPK)THEN
      LNJK = (POP(IRPK,ISPIN)*(POP(IRPK,ISPIN) - 1))/2
      JK   = INDEX(K-1) + J
      ELSE
      LNJK =  POP(IRPJ,ISPIN)* POP(IRPK,ISPIN)
      JK   = (K-1)*POP(IRPJ,ISPIN) + J
      ENDIF
      LNJKM  = DISTSZ(IRPJKM,ISPIN1 + 1)
C
C     I000 -  W(C,e)   or  W(c,E)
C     I010 - T3(A<B,e) or T3(a<b,E)
C
      IRPMI = DIRPRD(IRPM,IRPI)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMI,13)
      I020 = I010 + LNJKM
      NEED = IINTFP * I020
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO 390 M=1,POP(IRPM,ISPIN2)
C
      JKMVAL = IOFF + (M-1)*LNJK + JK
      CALL GETLIST(CORE(I010),JKMVAL,1,1,IRPJKM,4 + ISPIN1 + 1)
C
      MI = IOFFOO(IRPI,IRPMI,7-ISPIN) + (I-1)*POP(IRPM,ISPIN2) + M
      LISTW = 58 - ISPIN
      CALL GETLST(CORE(I000),MI,1,2,IRPMI,LISTW)
C
      IOFFT = I010
      DO 380 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN2).EQ.0) GOTO 380
C
      IRPC  = DIRPRD(IRPE,IRPMI)
      IRPCE = IRPMI
C     IOFFW = IOFFVV(IRPE,IRPCE,4+ISPIN) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,7-ISPIN) + 1
      IRPAB = DIRPRD(IRPE,IRPJKM)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN2)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
  380 CONTINUE
  390 CONTINUE
  400 CONTINUE
C
      SIGN = -1.0D+00
      DO 500 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN2).EQ.0) GOTO 500
C
      IRPIK  = DIRPRD(IRPI,IRPK)
      IRPIKM = DIRPRD(IRPIK,IRPM)
C
      IKMPOS = IJKPOS(IRPI,IRPK,IRPM,2)
      IOFF   = IJKOFF(IKMPOS,IRPIKM,ISPIN1 + 1)
C
      IF(IRPI.EQ.IRPK)THEN
      LNIK = (POP(IRPK,ISPIN)*(POP(IRPK,ISPIN) - 1))/2
      IK   = INDEX(K-1) + I
      ELSE
      LNIK =  POP(IRPI,ISPIN)* POP(IRPK,ISPIN)
      IK   = (K-1)*POP(IRPI,ISPIN) + I
      ENDIF
      LNIKM  = DISTSZ(IRPIKM,ISPIN1 + 1)
C
C     I000 -  W(C,e)   or  W(c,E)
C     I010 - T3(A<B,e) or T3(a<b,E)
C
      IRPMJ = DIRPRD(IRPM,IRPJ)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMJ,13)
      I020 = I010 + LNIKM
      NEED = IINTFP * I020
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO 490 M=1,POP(IRPM,ISPIN2)
C
      IKMVAL = IOFF + (M-1)*LNIK + IK
      CALL GETLIST(CORE(I010),IKMVAL,1,1,IRPIKM,4 + ISPIN1 + 1)
C
      MJ = IOFFOO(IRPJ,IRPMJ,7-ISPIN) + (J-1)*POP(IRPM,ISPIN2) + M
      LISTW = 58 - ISPIN
      CALL GETLST(CORE(I000),MJ,1,2,IRPMJ,LISTW)
C
      IOFFT = I010
      DO 480 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN2).EQ.0) GOTO 480
C
      IRPC  = DIRPRD(IRPE,IRPMJ)
      IRPCE = IRPMJ
C     IOFFW = IOFFVV(IRPE,IRPCE,4+ISPIN) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,7-ISPIN) + 1
      IRPAB = DIRPRD(IRPE,IRPIKM)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN2)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
  480 CONTINUE
  490 CONTINUE
  500 CONTINUE
C
      SIGN = 1.0D+00
      DO 600 IRPM=1,NIRREP
C
      IF(POP(IRPM,ISPIN2).EQ.0) GOTO 600
C
      IRPIJ  = DIRPRD(IRPI,IRPJ)
      IRPIJM = DIRPRD(IRPIJ,IRPM)
C
      IJMPOS = IJKPOS(IRPI,IRPJ,IRPM,2)
      IOFF   = IJKOFF(IJMPOS,IRPIJM,ISPIN1 + 1)
C
      IF(IRPI.EQ.IRPJ)THEN
      LNIJ = (POP(IRPJ,ISPIN)*(POP(IRPJ,ISPIN) - 1))/2
      IJ   = INDEX(J-1) + I
      ELSE
      LNIJ =  POP(IRPI,ISPIN)* POP(IRPJ,ISPIN)
      IJ   = (J-1)*POP(IRPI,ISPIN) + I
      ENDIF
      LNIJM  = DISTSZ(IRPIJM,ISPIN1 + 1)
C
C     I000 -  W(C,e)   or  W(c,E)
C     I010 - T3(A<B,e) or T3(a<b,E)
C
      IRPMK = DIRPRD(IRPM,IRPK)
      I000 = 1
      I010 = I000 + IRPDPD(IRPMK,13)
      I020 = I010 + LNIJM
      NEED = IINTFP * I020
      IF(NEED.GT.MAXCOR)THEN
      WRITE(LUOUT,1010) NEED,MAXCOR
      CALL INSMEM('T3WT314R',NEED,MAXCOR)
      ENDIF
C
      DO 590 M=1,POP(IRPM,ISPIN2)
C
      IJMVAL = IOFF + (M-1)*LNIJ + IJ
      CALL GETLIST(CORE(I010),IJMVAL,1,1,IRPIJM,4 + ISPIN1 + 1)
C
      MK = IOFFOO(IRPK,IRPMK,7-ISPIN) + (K-1)*POP(IRPM,ISPIN2) + M
      LISTW = 58 - ISPIN
      CALL GETLST(CORE(I000),MK,1,2,IRPMK,LISTW)
C
      IOFFT = I010
      DO 580 IRPE=1,NIRREP
C
      IF(VRT(IRPE,ISPIN2).EQ.0) GOTO 580
C
      IRPC  = DIRPRD(IRPE,IRPMK)
      IRPCE = IRPMK
C     IOFFW = IOFFVV(IRPE,IRPCE,4+ISPIN) + 1
      IOFFW = IOFFVV(IRPC,IRPCE,7-ISPIN) + 1
      IRPAB = DIRPRD(IRPE,IRPIJM)
      DISSIZ = IRPDPD(IRPAB,ISPIN)
      NDIS   = VRT(IRPC,ISPIN)
      NSUM   = VRT(IRPE,ISPIN2)
      IOFFDT = IADBLK(IRPC)
C
C      CALL XGEMM('N','T',DISSIZ,NDIS,NSUM,SIGN,
C     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NDIS,1.0D+00,
C     1           D3T3EXP(IOFFDT),DISSIZ)
      CALL XGEMM('N','N',DISSIZ,NDIS,NSUM,SIGN,
     1           CORE(IOFFT),DISSIZ,CORE(IOFFW),NSUM,1.0D+00,
     1           D3T3EXP(IOFFDT),DISSIZ)
C
      IOFFT = IOFFT + DISSIZ * NSUM
  580 CONTINUE
  590 CONTINUE
  600 CONTINUE
      RETURN
      END
