      SUBROUTINE CHKSMG(CORE,IUHF)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION CORE(1),VAL
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     1                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     1                NF1BB,NF2BB
      COMMON /INFO/   NOCCO(2),NVRTO(2)
      COMMON /FLAGS/  IFLAGS(100)
      EQUIVALENCE(IDRLVL,IFLAGS( 3))
C
      COMMON /GAMLIS/ LISGO1,LISGO2,LISGO3,LISGO4,LISGV1,LISGV2,
     1                LISGV3,LISGV4
      if (iflags(1).lt.10) return
C
C     ROUTINE TO COMPUTE CHECK SUMS OF GAMMA LISTS WHICH HAVE A
C     CONTRIBUTION FROM T3 IN MBPT(4), CCSD+T(CCSD), CCSD(T)
C     or QCISD(T) GRADIENTS.
C
      WRITE(6,1000)
 1000 FORMAT(' @CHKSMG-I, Evaluating check sums of T3 gamma lists ')
C
      LISGO1 = 107
      LISGO2 = 108
      LISGO3 = 109
      LISGO4 = 110
      LISGV1 = 127
      LISGV2 = 128
      LISGV3 = 129
      LISGV4 = 130
      IF(IUHF.GT.0)THEN
C
      VAL = 0.0D+00
      DO   20 IRREP=1,NIRREP
      LIST   = LISGO1
      DISSIZ = IRPDPD(IRREP, 3)
      NDIS   = IRPDPD(IRREP, 9)
C
      DO   10 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
   10 CONTINUE
   20 CONTINUE
      WRITE(6,1010) LIST,VAL
 1010 FORMAT(' @CHKSMG-I, List ',I5,' Check sum is ',F20.12)
C
      VAL = 0.0D+00
      DO   40 IRREP=1,NIRREP
      LIST   = LISGO2
      DISSIZ = IRPDPD(IRREP, 4)
      NDIS   = IRPDPD(IRREP,10)
C
      DO   30 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
   30 CONTINUE
   40 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      VAL = 0.0D+00
      DO   60 IRREP=1,NIRREP
      LIST   = LISGO3
      DISSIZ = IRPDPD(IRREP,14)
      NDIS   = IRPDPD(IRREP,11)
C
      DO   50 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
   50 CONTINUE
   60 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      ENDIF
C
      VAL = 0.0D+00
      DO   80 IRREP=1,NIRREP
      LIST   = LISGO4
      DISSIZ = IRPDPD(IRREP,14)
      NDIS   = IRPDPD(IRREP,12)
C
      DO   70 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
   70 CONTINUE
   80 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      IF(IUHF.GT.0)THEN
C
      VAL = 0.0D+00
      DO  120 IRREP=1,NIRREP
      LIST   = LISGV1
      DISSIZ = IRPDPD(IRREP, 1)
      NDIS   = IRPDPD(IRREP, 9)
C
      DO  110 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
  110 CONTINUE
  120 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      VAL = 0.0D+00
      DO  140 IRREP=1,NIRREP
      LIST   = LISGV2
      DISSIZ = IRPDPD(IRREP, 2)
      NDIS   = IRPDPD(IRREP,10)
C
      DO  130 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
  130 CONTINUE
  140 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      VAL = 0.0D+00
      DO  160 IRREP=1,NIRREP
      LIST   = LISGV3
      DISSIZ = IRPDPD(IRREP,13)
      NDIS   = IRPDPD(IRREP,12)
C
      DO  150 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
  150 CONTINUE
  160 CONTINUE
      WRITE(6,1010) LIST,VAL
C
      ENDIF
C
      VAL = 0.0D+00
      DO  180 IRREP=1,NIRREP
      LIST   = LISGV4
      DISSIZ = IRPDPD(IRREP,13)
      NDIS   = IRPDPD(IRREP,11)
C
      DO  170 IDIS=1,NDIS
      CALL GETLST(CORE,IDIS,1,2,IRREP,LIST)
      CALL CHKSUM2(CORE,DISSIZ,VAL)
  170 CONTINUE
  180 CONTINUE
      WRITE(6,1010) LIST,VAL
      RETURN
      END
