      SUBROUTINE EXPVV(T2,W,IADT2E,IOFFAB,IRPIJ,ISPIN)
      IMPLICIT INTEGER (A-Z)
      DOUBLE PRECISION T2(1),W(1)
      DIMENSION IADT2E(8),IOFFAB(8,8)
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     1                DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     1                NF1BB,NF2BB
      COMMON /INFO/   NOCCO(2),NVRTO(2)
C
      INDEX(I) = I*(I-1)/2
C
C     THIS ROUTINE DOES THE CONTRACTION
C
C     T2(A<B) = W(A,B) - W(B,A)
C
C     IN SYMMETRY. NOTE THAT IT IS NOT ASSUMED THAT DIRPRD(A,B) = 1.
C
      IRPAB = IRPIJ
C
      IF(IRPAB.NE.1)THEN
C
      DO 1120 IRPB=2,NIRREP
      IRPA =  DIRPRD(IRPAB,IRPB)
      IF(IRPA.GT.IRPB) GOTO 1120
C
      IOFFT2 = IOFFAB(IRPB,IRPAB)
C
      CALL EXPWVV(T2(IOFFT2+1),
     1             W(IADT2E(IRPB)-IADT2E(1)+1),
     1             W(IADT2E(IRPA)-IADT2E(1)+1),
     1            IRPDPD(IRPAB,ISPIN),VRT(IRPA,ISPIN),
     1            VRT(IRPB,ISPIN))
C
 1120 CONTINUE
C
      ELSE
C
C     IRPAB = 1 (IE IRPA = IRPB)
C
      DO 1130 IRPB=1,NIRREP
      IRPA = IRPB
C
      IOFFT2 = IOFFAB(IRPB,IRPAB)
C
      CALL EXPW2VV(T2(IOFFT2+1),
     1             W(IADT2E(IRPB)-IADT2E(1)+1),
     1             IRPDPD(IRPAB,ISPIN),
     1             VRT(IRPA,ISPIN),VRT(IRPB,ISPIN))
C
 1130 CONTINUE
C
      ENDIF
C
 1150 CONTINUE
      RETURN
      END
