      SUBROUTINE TSPLST(CORE,MAXCOR,LIST,IRREPX)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER BUFSIZ,DIRPRD,POP,VRT,SYTYPL,SYTYPR,DISSIZ
      DIMENSION CORE(1),IPOS(8)
      LOGICAL CHANGE
C
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYM/    POP(8,2),VRT(8,2),NTAA,NTBB,NF1AA,NF2AA,
     &                NF1BB,NF2BB
      COMMON /FLAGS/  IFLAGS(100)
C
      CHANGE = .TRUE.
C
CYAU - less output...
      WRITE(6,1000) LIST
 1000 FORMAT(' @TSPLST-I, List ',I3,' is being transposed. ')
C
      BUFSIZ = 0
      DO 10 IRREP=1,NIRREP
      BUFSIZ = MAX0(BUFSIZ,IRPDPD(IRREP,ISYTYP(1,LIST)),
     &                     IRPDPD(IRREP,ISYTYP(2,LIST)))
   10 CONTINUE
C
      I000 = 1
      I010 = I000 + BUFSIZ
      DO 80 IRPR=1,NIRREP
      IRPL   = DIRPRD(IRREPX,IRPR)
C
C Dimensions of list currently on disk.
C
      DISSIZ = IRPDPD(IRPL,ISYTYP(1,LIST))
      NDIS   = IRPDPD(IRPR,ISYTYP(2,LIST))
      IPOS(IRPL) = I010
      IF(DISSIZ.EQ.0.OR.NDIS.EQ.0) GOTO 80
      CALL GETTRN(CORE(I010),CORE(I000),DISSIZ,NDIS,2,IRPR,LIST)
C
      I010 = I010 + DISSIZ * NDIS
      NEED = I010 * IINTFP
C
      IF(NEED.GT.MAXCOR)THEN
      WRITE(6,1020)
      STOP
      ENDIF
   80 CONTINUE
C
C     Alter the list parameters.
C
      SYTYPL = ISYTYP(2,LIST)
      SYTYPR = ISYTYP(1,LIST)
      CALL NEWTYP2(IRREPX,LIST,SYTYPL,SYTYPR,CHANGE)
C
      I000 = 1
      I010 = I000 + BUFSIZ
      DO 90 IRPR=1,NIRREP
      IRPL   = DIRPRD(IRREPX,IRPR)
C
C Dimensions of list to be written on disk.
C
      DISSIZ = IRPDPD(IRPL,ISYTYP(1,LIST))
      NDIS   = IRPDPD(IRPR,ISYTYP(2,LIST))
      IF(DISSIZ.EQ.0.OR.NDIS.EQ.0) GOTO 90
      CALL PUTLST(CORE(IPOS(IRPR)),1,NDIS,2,IRPR,LIST)
C
      I010 = I010 + DISSIZ * NDIS
      NEED = I010 * IINTFP
C
      IF(NEED.GT.MAXCOR)THEN
      WRITE(6,1020)
      STOP
      ENDIF
   90 CONTINUE
C
 1020 FORMAT(' @TSPLST-F, Insufficient memory to continue. ')
 1030 FORMAT(' @SETOOOV-I, Memory required ',I10,' double words. ')
      RETURN
      END
