 
      SUBROUTINE REORDR(IRERDR,BUFIN,BUFOUT,NLONG,NBAS)
C
C THIS ROUTINE REORDERS EIGENVALUES OR EIGENVECTORS FROM AN
C   SCF CALCULATION.
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DIMENSION BUFIN(NLONG,NBAS),BUFOUT(NLONG,NBAS),IRERDR(NBAS)
      DO 10 I=1,NBAS
       DO 20 J=1,NLONG
        BUFOUT(J,IRERDR(I))=BUFIN(J,I)
20     CONTINUE
10    CONTINUE
      RETURN
      END
