
      SUBROUTINE GETARGS(NLIST,IFIRST,ISECOND)
      IMPLICIT INTEGER (A-Z)
      IF(NLIST.EQ.34)THEN
       IFIRST=1
       ISECOND=1
      ELSEIF(NLIST.EQ.35)THEN
       IFIRST=2
       ISECOND=2
      ELSEIF(NLIST.EQ.36.OR.NLIST.EQ.38)THEN
       IFIRST=2
       ISECOND=1
      ELSEIF(NLIST.EQ.37.OR.NLIST.EQ.39)THEN
       IFIRST=1
       ISECOND=2
      ENDIF
      RETURN
      END
