      SUBROUTINE RNGDRV2(ICORE,MAXCOR,LISTW,LISTT,CALMOD,MAXSIZ,
     &                  INCREM,LSTSCR,ADD41)
      IMPLICIT INTEGER (A-Z)
      LOGICAL ADD41
      DOUBLE PRECISION ONE ,TWO,HALF
      CHARACTER*3 CALMOD
      DIMENSION ICORE(MAXCOR)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      DATA ONE /1.0/
      DATA TWO /2.0/
      DATA HALF/0.5/
C
C LOOP OVER IRREPS.
C
       DO 100 IRREP=1,NIRREP
        DISSYW=IRPDPD(IRREP,ISYTYP(1,LISTW))
        DISSYT=IRPDPD(IRREP,ISYTYP(1,LISTT))
        NUMSYW=IRPDPD(IRREP,ISYTYP(2,LISTW))
        NUMSYT=IRPDPD(IRREP,ISYTYP(2,LISTT))
        DISSYQ=DISSYT
        NUMSYQ=NUMSYW
        if (NUMSYQ*DISSYQ.LT.0) call trap_intovf('RNGDRV2',1)
        MAXSIZ=MAX(NUMSYQ*DISSYQ,MAXSIZ)
        I000=1
        I010=I000+IINTFP*NUMSYQ*DISSYQ
        I020=I010+IINTFP*MAX(NUMSYT*DISSYT,NUMSYQ*DISSYQ)
        I030=I020+IINTFP*DISSYW*NUMSYW
C
C CAN WE DO IT IN CORE?
C
        if (I030.LT.0) call trap_intovf('RNGDRV2',2)
        IF(I030.LT.MAXCOR)THEN
C
C FORM THE SYMMETRY PACKED Q VECTOR.
C
         CALL RNGPRD(ICORE(I020),ICORE(I010),ICORE(I000),
     &               ICORE(I030),MAXCOR-I030,
     &               DISSYW,NUMSYW,DISSYT,NUMSYT,DISSYQ,NUMSYQ,
     &               LISTW,LISTT,IRREP,CALMOD,.FALSE.)
        ELSE
         CALL INSMEM('RNGDRV2',I090,MAXCOR)
        ENDIF
        CALL PUTLST(ICORE(I000),1,NUMSYQ,1,IRREP,LSTSCR)
100    CONTINUE
C
C NOW ADD IN SSTRNGED PIECE NEEDED TO COMPLETE THIS INCREMENT
C
       ISIZE=ISYMSZ(ISYTYP(1,LSTSCR),ISYTYP(2,LSTSCR))
       I000=1
       I010=I000+ISIZE*IINTFP
       I020=I010+ISIZE*IINTFP
       CALL GETALL(ICORE(I000),ISIZE,1,LSTSCR)
       CALL SSTRNG(ICORE(I000),ICORE(I010),ISIZE,ISIZE,ICORE(I020),
     &             'AAAA')
       CALL SAXPY(ISIZE,HALF,ICORE(I010),1,ICORE(I000),1)
C
C ADD IN PIECE FROM T1*T1*W FOR CCSD
C
       IF(ADD41)THEN
        CALL GETALL(ICORE(I010),ISIZE,1,41)
        CALL SAXPY(ISIZE,ONE,ICORE(I010),1,ICORE(I000),1)
       ENDIF
C
C SYMMETRIZE
C
       IOFF=I000
       DO 200 IRREP=1,NIRREP
        NUMSYQ=IRPDPD(IRREP,ISYTYP(2,LISTW))
        CALL MPMT(ICORE(IOFF),NUMSYQ)
        IOFF=IOFF+NUMSYQ*NUMSYQ*IINTFP
        if (IOFF.LT.0) call trap_intovf('RNGDRV2',3)
200    CONTINUE
       CALL PUTALL(ICORE(I000),1,1,LSTSCR)
C        
       RETURN
       END
