      SUBROUTINE DINTRN6(EVEC,AODINT,BUF,RHF,NSTART,NEND,
     &                   IRREPX,ISPIN)
C
C THIS ROUTINE TRANSFORMS DERIVATIVE INTEGRALS FROM THE AO TO THE MO
C BASIS. THIS IS THE IJII VERSION.
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD,AOPOP,AODSZ,AODIS,POP,VRT
      LOGICAL RHF
      CHARACTER*2 SP
C
      DIMENSION AODINT(1),EVEC(1),BUF(1)
      DIMENSION NSTART(8),NEND(8)
      DIMENSION IREORD(8)
      DIMENSION SP(2)
C
      COMMON/SYM/POP(8,2),VRT(8,2),NDUM(6)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON/SYMINF/NDUMY,NIRREP,IRREPS(255,2),DIRPRD(8,8)
      COMMON/AOPOPS/AOPOP(8)
      COMMON/AOOFST/INDOCC(8,2)
      COMMON/INFO/NOCCO(2),NVRTO(2)
      COMMON/INFOI/TIMEI,NWRITI
      COMMON /TIMEINFO/ TIMEIN, TIMENOW, TIMETOT, TIMENEW 
C
      DATA ONE/1.0D0/
      DATA ZILCH/0.0D0/
      DATA SP/'AA','BB'/
C
      CALL TIMER(1)
C
      IOFF1=1
      IOFF2=1
C
      DO 1000 IRREP1=1,NIRREP
C
       IOFF4I=IOFF2
C
       IRREP2=DIRPRD(IRREP1,IRREPX)
C
       NAO1=AOPOP(IRREP1)
       NMO1=AOPOP(IRREP1)
       NAO2=AOPOP(IRREP2)
       NMO2=AOPOP(IRREP2)
       AODSZ=NAO1*NAO1
       MODSZ=NMO1*NMO1
       NSTART1=NSTART(IRREP1)
       NEND1=NEND(IRREP1)
       NUMDIS=NMO2*(NEND1-NSTART1+1)    
       IX=NAO1*NAO1+1
       IOFFC1=INDOCC(IRREP1,ISPIN)
       IOFFC2=INDOCC(IRREP2,ISPIN)
C
C TRANSFORM THE LHS TO THE (ISPIN,ISPIN) SPIN CASE
C
C
C LOOP OVER (XX) BLOCKS ON LHS AND TRANSFORM THEM TO (PI)
C
       DO 20 IOCC=NSTART1,NEND1
        CALL XGEMM('T','N',NMO2,AODSZ,NAO2,ONE,EVEC(IOFFC2),
     &             NAO2,AODINT(IOFF1),NAO2,ZILCH,BUF,NMO2)
        CALL TRANSP(BUF,AODINT(IOFF2),AODSZ,NMO2)
        IOFF1=IOFF1+NAO2*AODSZ
        IOFF2=IOFF2+NMO2*AODSZ
20     CONTINUE
C
C NOW WE HAVE (PI,XX) INTEGRALS.  TRANSPOSE TO (XX,PI)
C
C TRANSFORM NEW LHS (XX) TO (PQ) [SPIN CASE (ISPIN,ISPIN)]
C
       IOFF5=IOFF4I
       IOFF6=IOFF4I
       DO 21 IDIS=1,NUMDIS
c YAU : old
c       CALL ICOPY(NAO1*NAO1*IINTFP,AODINT(IOFF5),1,BUF,1)
c YAU : new
        CALL DCOPY(NAO1*NAO1,AODINT(IOFF5),1,BUF,1)
c YAU : end
        CALL GHTRAN(BUF,BUF,EVEC,IOFFC1,IOFFC1,1,1,
     &             BUF(IX),0,1,NAO1,NAO1,NMO1,NMO1)
c YAU : old
c       CALL ICOPY(NMO1*NMO1*IINTFP,BUF,1,AODINT(IOFF6),1)
c YAU : new
        CALL DCOPY(NMO1*NMO1,BUF,1,AODINT(IOFF6),1)
c YAU : end
        IOFF5=IOFF5+AODSZ
        IOFF6=IOFF6+MODSZ
21     CONTINUE
C
C END LOOP OVER IRREPS
C
1000  CONTINUE
C
C ALLOCATE MEMORY
C
      IOFFBUF1=1
      DO 1010 IRREP1=1,NIRREP
       IRREP2=DIRPRD(IRREPX,IRREP1)
       IOFFBUF1=MAX(IOFFBUF1,1+AOPOP(IRREP2)*AOPOP(IRREP1)*
     &              AOPOP(IRREP1))
1010  CONTINUE
C
      IOFFBUF2=IOFFBUF1
      DO 1020 IRREP=1,NIRREP
       IRREP2=DIRPRD(IRREPX,IRREP)
       IOFFBUF2=MAX(IOFFBUF2,      
     &              IOFFBUF1+2*POP(IRREP,1)*POP(IRREP,1),
     &              IOFFBUF1+2*POP(IRREP2,1)*POP(IRREP,1),
     &              IOFFBUF1+2*VRT(IRREP,1)*VRT(IRREP,1),
     &              IOFFBUF1+2*VRT(IRREP,1)*POP(IRREP,1),
     &              IOFFBUF1+2*VRT(IRREP,1)*VRT(IRREP2,1),
     &              IOFFBUF1+2*VRT(IRREP2,1)*POP(IRREP,1))
1020  CONTINUE
C
      CALL DUMP6(AODINT,BUF,BUF(IOFFBUF1),BUF(IOFFBUF2),
     &           NSTART,NEND,IRREPX)
C
      CALL TIMER(1)
      TIMEI=TIMEI+TIMENEW
C
      RETURN
      END
