      SUBROUTINE DINTVO1(DIVO,DOO,DVV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C DRIVES THE CALCULATION OF ALL d<PQ||RS>/d chi PIECES TO THE
C d I(A,I)/d chi INTERMEDIATE
C
C IN THIS FORM ONLY REQUIRED FOR THE GIAO-CC/MBPT METHODS
C
CEND
C
C CODED JUNE/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,ANTI
C
      DIMENSION ICORE(MAXCOR),DIVO(1)
C
      COMMON/METH/MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /TIMEINFO/ TIMEIN, TIMENOW, TIMETOT, TIMENEW 
C
      CALL TIMER(1)
C
C CALCULATE FIRST CONTRIBUTIONS TO DI(A,I)
C
      CALL DIVO11(DIVO,DOO,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C CALCULATE SECOND CONTRIBUTIONS TO DI(A,I)
C
      CALL DIVO12(DIVO,DVV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C CALCULATE THIRD CONTRIBUTIONS TO DI(A,I)
C
      CALL DIVO13(DIVO,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C FOR HIGHER ORDER PERTURBATION THEORY AND CC METHODS, ADDITIONAL TERMS
C HAVE TO BE CONSIDERED
C
      IF(.NOT.MBPT2) THEN
C
c       CALL DIVO14(DIVO,ICORE,MAXCOR,IUHF,IP,ANTI)
c       CALL DIVO15(DIVO,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C ADDITIONAL TERMS FOR FOURTH ORDER AND QCISD AND CCSD
C
       IF(.NOT.MBPT3.AND..NOT.CCD) THEN
C
c        CALL DIVO16(DIVO,ICORE,MAXCOR,IUHF,IP,ANTI)
c        CALL DIVO17(DIVO,ICORE,MAXCOR,IUHF,IP.ANTI)
c        CALL DIVO18(DIVO,ICORE,MAXCOR,IUHF,IP,ANTI)
C
       ENDIF
      ENDIF
C
C ALL DONE
C
      CALL TIMER(1)
      write(6,6001) timenew
6001  FORMAT(' Calculation of the contribution of d<pq||rs>/d chi',
     &       ' to d I(a,i)/d chi',/,' required ',f5.1,' seconds.')
      RETURN
C
      END 
