      SUBROUTINE DINTOV1(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C THIS ROUTINE DRIVES THE CALCULATIONS OF ALL PIECES
C OF THE d I(I,A)/d chi INTERMEDIATE WHICH INVOLVE
C THE INTEGRAL DERIVATIVES d <PQ||RS>/d chi. 
C
CEND
C
C CODED JUNE/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD,ANTI
C
      DIMENSION ICORE(MAXCOR),DIOV(1)
C
      COMMON/METH/MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /TIMEINFO/ TIMEIN, TIMENOW, TIMETOT, TIMENEW 
C
      CALL TIMER(1)
C
C CALCULATE FIRST CONTRIBUTIONS TO DI(I,A) (ALL METHODS)
C
      CALL DIOV11(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C FOR HIGHER ORDER PERTURBATION THEORY AND CC METHODS, ADDITIONAL TERMS
C HAVE TO BE CONSIDERED
C
      IF(.NOT.MBPT2) THEN
C
c       CALL DIOV12(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
c       CALL DIOV13(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
C ADDITIONAL TERMS FOR FOURTH ORDER AND QCISD AND CCSD
C
       IF(.NOT.MBPT3.AND..NOT.CCD) THEN
C
c        CALL DIOV14(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
c        CALL DIOV15(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
c        CALL DIOV16(DIOV,ICORE,MAXCOR,IUHF,IP,ANTI)
C
       ENDIF
      ENDIF
C
C ALL DONE
C
      CALL TIMER(1)
      write(6,6001) TIMENEW
6001  FORMAT(' Calculation of the contribution of d<pq||rs>/ dchi',
     &       ' to d I(i,a)/d chi',/,' required ',f5.1,' seconds.')
      RETURN
C
      END 
