      SUBROUTINE INIDG(IRREPX,IUHF)
C
C  THIS ROUTINE CREATES THE LISTS FOR THE DERIVATIVES OF
C  T1 AND T2 AMPITUDES
C 
CEND
C
      IMPLICIT INTEGER (A-Z)
      LOGICAL ROHF,QRHF,SEMI
      COMMON/REF/ROHF,QRHF,SEMI
      COMMON/SYMINF/NSTART,NIRREP,IRREPA(255,2),DIRPRD(8,8)
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
C
C NOW CREATE PERTURBED T2 LISTS
C
C  THE STRUCTURE IS THE FOLLOWING
C
c      IENTER=1
c      IOFF=-1
      call aces_io_remove(54,'DERGAM')
      IENTER=0
      IOFF=0
      IBOT=1
      IF(IUHF.EQ.0) IBOT=3
      DO 40 ISPIN=IBOT,3
       RPOINT=2+ISPIN
       LPOINT=ISPIN
       IF(ISPIN.EQ.3) THEN
        RPOINT=14
        LPOINT=13
       ENDIF
       LIST=443+ISPIN
C
C LIST FOR DT2
C
       CALL INIPCK(IRREPX,LPOINT,RPOINT,LIST,IENTER,IOFF,1)
C
       IENTER=0
       IOFF=0
C
C LIST FOR CORRESPONDING DENOMINATOR LIST
C
       CALL INIPCK(IRREPX,LPOINT,RPOINT,LIST+4,IENTER,IOFF,1)
C
40    CONTINUE
C
C FOR ROHF CREATE PERTURBED T1 LISTS
C
      IF(ROHF) THEN
C
       LIST=490
       CALL UPDMOI(1,IRPDPD(IRREPX,9),1,LIST,0,0)
       CALL UPDMOI(1,IRPDPD(IRREPX,10),2,LIST,0,0)
       CALL UPDMOI(1,IRPDPD(IRREPX,9),9,448,0,0)
       CALL UPDMOI(1,IRPDPD(IRREPX,10),9,449,0,0)
C
      ENDIF
      RETURN
      END
