      SUBROUTINE UXINT2(UAIA,UAIB,UIAA,UIAB,SIJA,SIJB,SABA,SABB,
     &                  GRAD,ICORE,MAXCOR,IRREPX,IPERT,STERM,
     &                  IUHF,ANTI)
C
C THIS ROUTINE DRIVES THE EVALUATION OF THE FOLLOWING CONTRIBUTION
C TO THE INTEGRAL DERIVATIVES :
C
C  d <pq//rs>                   chi 
C  ------------ <===   + SUM ( U    <tq//rs>
C    d chi                t     tp
C
C      chi             chi             chi
C   + U    <pt//rs> + U    <pq//ts> + U     <pq//rt>  )
C      tq              tr              ts
C
CEND
C
C AUGUST/91 JG
C
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      LOGICAL MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      LOGICAL STERM,ANTI
C
      DIMENSION UAIA(1),UAIB(1),UIAA(1),UIAB(1),SIJA(1),SIJB(1),
     &          ICORE(1)
C
      COMMON /METH/ MBPT2,MBPT3,M4DQ,M4SDQ,M4SDTQ,CCD,QCISD,CCSD
      COMMON /TIMEINFO/ TIMEIN, TIMENOW, TIMETOT, TIMENEW 
C
      CALL TIMER(1)
C
      write(6,20000)
20000 FORMAT(' Total derivatives of 2e integrals are formed:')
C
C FORM THE d <IJ//AB>/d chi     INTEGRALS
C
      CALL D2IJAB(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,
     &            ICORE,MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI,GRAD)
C
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE
C
      IF(IUHF.EQ.1) THEN
C
       CALL D1IJAB(UAIA,SIJA,UIAA,SABA,ICORE,MAXCOR,IRREPX,
     &             IPERT,1,STERM,ANTI,GRAD)
       CALL D1IJAB(UAIB,SIJB,UIAB,SABB,ICORE,MAXCOR,IRREPX,
     &             IPERT,2,STERM,ANTI,GRAD)
C
      ENDIF
C
C FORM THE d <IJ//KA>/d chi INTEGRALS
C
C  FORM FIRST d<Ij|Ka> / d chi
C
      CALL D2IJKA(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,
     &            ICORE,MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
C
C FOR UHF FORM IN ADDITION d <Ij|Ak> / d chi INTEGRALS
C
      IF(IUHF.EQ.1) THEN
C
       CALL D2IJAK(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,
     &             ICORE,MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI) 
C 
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE 
C
       CALL D1IJKA(UAIA,SIJA,UIAA,SABA,ICORE,MAXCOR,IRREPX,
     &             IPERT,1,STERM,ANTI)
       CALL D1IJKA(UAIB,SIJB,UIAB,SABB,ICORE,MAXCOR,IRREPX,
     &             IPERT,2,STERM,ANTI)
C
      ENDIF
C
C FORM THE d <IA//BC>/d chi INTEGRALS
C
C FORM FIRST d <Ab|Ci> / d chi
C
      CALL D2ABCI(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
     &            MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
C
C FOR UHF FORM IN ADDITION d <Ab|Ic> / d chi
C
      IF(IUHF.EQ.1) THEN

       CALL D2ABIC(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
     &             MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
C
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE
C
       CALL D1ABCI(UAIA,SIJA,UIAA,SABA,ICORE,MAXCOR,IRREPX,IPERT,
     &             1,STERM,ANTI)
       CALL D1ABCI(UAIB,SIJB,UIAB,SABB,ICORE,MAXCOR,IRREPX,IPERT,
     &             2,STERM,ANTI)
C
      ENDIF
C
      IF(ANTI.OR.(.NOT.MBPT2)) THEN
C
C FORM THE d <Ai//Bj>/d chi INTEGRALS
C
       CALL D2IAJB(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
     &             MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
       CALL D2IABJ(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
     &             MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
C
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE
C
       IF(IUHF.EQ.1) THEN
C 
C FOR UHF FORM IN ADDITION d <Ia//Jb> INTEGALS
C 
        CALL D3IAJB(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
     &              MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
c       CALL D3IABJ(UAIA,UAIB,SIJA,SIJB,UIAA,UIAB,SABA,SABB,ICORE,
c     &             MAXCOR,IRREPX,IPERT,IUHF,STERM,ANTI)
C
C FORM ADDITION AAAA AND BBBB SPIN CASES
C
        CALL D1IAJB(UAIA,SIJA,UIAA,SABA,ICORE,MAXCOR,IRREPX,IPERT,
     &              1,STERM,ANTI)
        CALL D1IAJB(UAIB,SIJB,UIAB,SABB,ICORE,MAXCOR,IRREPX,IPERT,
     &              2,STERM,ANTI)
C
       ENDIF
      ENDIF
C
      IF(.NOT.MBPT2) THEN
C
C FORM THE d <IJ//KL>/d chi INTEGRALS
C
       CALL D2IJKL(UAIA,UAIB,SIJA,SIJB,ICORE,MAXCOR,IRREPX,IPERT,
     &             IUHF,STERM,ANTI)
C
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE
C
       IF(IUHF.EQ.1) THEN
C
        CALL D1IJKL(UAIA,SIJA,ICORE,MAXCOR,IRREPX,IPERT,1,STERM,ANTI)
        CALL D1IJKL(UAIB,SIJB,ICORE,MAXCOR,IRREPX,IPERT,2,STERM,ANTI)
C
       ENDIF
C
C FORM THE d <AB//CD>/d chi INTEGRALS
C
       CALL D2ABCD(UIAA,UIAB,SABA,SABB,ICORE,MAXCOR,IRREPX,IPERT,
     &             IUHF,STERM,ANTI)
C
C  FOR UHF FORM IN ADDITION INTEGRALS FOR THE AAAA AND BBBB SPIN CASE
C
       IF(IUHF.EQ.1) THEN
C
        CALL D1ABCD(UIAA,SABA,ICORE,MAXCOR,IRREPX,IPERT,1,STERM,ANTI)
        CALL D1ABCD(UIAB,SABB,ICORE,MAXCOR,IRREPX,IPERT,2,STERM,ANTI)
C
       ENDIF
C
      ENDIF
C
      CALL TIMER(1)
C
      write(6,20100) TIMENEW
20100 FORMAT(' Formation of total 2e integral derivatives completed',
     &       ' in ',f5.1,' seconds.')
C
      RETURN
C
      END 
