C
C  CALCULATES THE FULL T2 AMPLITUDE IN MBPT(3) REQUIRED FOR GRADIENT
C  CALCULATION 
C
C  MBPT(3)  T2(IJ,AB) = T1(IJ,AB) + DELTA T2(IJ,AB)
C
C CODED AUGUST/90  JG
C 
      SUBROUTINE FORMT2(ICORE,MAXCOR,IUHF,LIST1,LIST2)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DIRPRD
      DIMENSION ICORE(MAXCOR)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),
     &DIRPRD(8,8)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),NTOT(18)
      COMMON /CONTROL/ IPRNT,IXXX,IXXX2
C
      DATA ONE /1.0D0/
      MXCOR=MAXCOR
C
C  AA AND BB SPIN CASES
C
       DO 100 ISPIN=1,3,2-IUHF
        LISTT2=LIST2+ISPIN
        LISTT1=LIST1+ISPIN
        NSIZE=ISYMSZ(ISYTYP(1,LISTT1),ISYTYP(2,LISTT1))
        I001=1
        I002=I001+IINTFP*NSIZE
        I003=I002+IINTFP*NSIZE
        IF(MXCOR.LT.I003) STOP 'FORMT2'
        CALL GETALL(ICORE(I001),NSIZE,1,LISTT2)
        CALL GETALL(ICORE(I002),NSIZE,1,LISTT1)
        CALL SAXPY(NSIZE,ONE,ICORE(I002),1,ICORE(I001),1)
        CALL PUTALL(ICORE(I001),NSIZE,1,LISTT2)
100    CONTINUE
C
      RETURN
      END
