      SUBROUTINE OSL2IAA(L,T,T1,G,ISPIN,VRTL,VRTT,VRT,NVRTSQ,
     $   DISSYW,DISSYT,NUMSYW,NUMSYT,LISTL,LISTT,IRREP,FACT)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      DOUBLE PRECISION L
      INTEGER DISSYT, DISSYW, DIRPRD,POP,VRT,VRTL,VRTT
      DIMENSION L(NUMSYW,DISSYW),T(NUMSYT,DISSYT)
      DIMENSION T1(DISSYT,NUMSYT),G(NVRTSQ)
      DIMENSION VRT(8),VRTL(8),VRTT(8)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /SYMINF/ NSTART,NIRREP,IRREPA(255),IRREPB(255),DIRPRD(8,8)
C
      DATA ONEM,ONE,HALF /-1.0D0,1.D0,0.5D0/
C
      CALL FSGET(T1,1,NUMSYW,2,IRREP,LISTL,'IIII')
      CALL TRANSP(T1,L,NUMSYW,DISSYW)
C 
      CALL FSGET(T1,1,NUMSYT,1,IRREP,LISTT,'IAII')
      CALL TRANSP(T1,T,NUMSYT,DISSYT)
C 
      IOFF=1
      JOFFL=1
      JOFFT=1
      DO 90 IRREPJ=1,NIRREP
C          
         NVRTL=VRTL(IRREPJ)
         NVRTT=VRTT(IRREPJ)
C
         IRREPI=DIRPRD(IRREP,IRREPJ)
         NVRTI=VRT(IRREPI)
C
         IF(MIN(NVRTI,NVRTT,NVRTL).NE.0) THEN
C
            CALL XGEMM('T','N',NVRTT,NVRTL,NVRTI*NUMSYW,FACT*HALF,
     &         T(1,JOFFT),NVRTI*NUMSYW,L(1,JOFFL),
     &         NVRTI*NUMSYW,ONE,G(IOFF),NVRTT)
         ENDIF
C
         JOFFL=JOFFL+NVRTI*NVRTL
         JOFFT=JOFFT+NVRTI*NVRTT
         IOFF=IOFF+NVRTT*NVRTL
C
 90   CONTINUE
C
      RETURN
      END
