      SUBROUTINE BCKDSK(IUHF)
C
C  THIS ROUTINE WRITES THE LIST WHICH ARE HELD IN CORE BACK TO
C  DISK
C
CEND
      IMPLICIT INTEGER (A-Z)
      COMMON / / ICORE(1)
      COMMON /LISTS/ MOIO(10,500),MOIOWD(10,500),MOIOSZ(10,500),
     &               MOIODS(10,500),MOIOFL(10,500)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /INCORE/ ICREC(2),USEC,IXT(2),IMOD(2)
      COMMON /IOSTAT/ NOPBUF,NOPDSK
      COMMON /FILSPC/ ILNBUF,IPRCLN,IPRCWD
      COMMON /IOPOS/ ICRSIZ,ICHCSZ,IOFF(2),LENREC
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /AUXCACHE/ QUIKGET(10,500)
      COMMON /SYM/ POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON /SYMINF/ NSTART,NIRREP,IRREPS(255,2),DIRPRD(8,8)
C
      DO 10 ILIST=1,500
      DO 10 ISPIN=1,10
       IF(QUIKGET(ISPIN,ILIST).NE.0) THEN
        IADR=QUIKGET(ISPIN,ILIST)
        QUIKGET(ISPIN,ILIST)=0
        CALL PUTLST(ICORE(IADR),1,MOIODS(ISPIN,ILIST),1,ISPIN,ILIST)
       ENDIF
10    CONTINUE
C        
      RETURN
      END
