      SUBROUTINE R1L2Y2(ICORE,MAXCOR,IUHF,LISTL2,LISTL2RS,LISTR1,
     &   LISTR1OFF,LISTR2,LISTR2RS)
C
C DRIVER FOR CALCULATING CONTRIBUTIONS OF R2 AND L2 VECTORS
C TO THE Y1 INTERMEDIATE.
C
CEND
      IMPLICIT INTEGER (A-Z)
      LOGICAL MBPT2,CC
      DIMENSION ICORE(MAXCOR),I0R(2),I0F(2),I0Q(2)
      COMMON/STATSYM/IRREPX
      COMMON/REFTYPE/MBPT2,CC
      COMMON/SYMPOP/IRPDPD(8,22),ISYTYP(2,500),ID(18)
      COMMON/SYM/POP(8,2),VRT(8,2),NT(2),NFMI(2),NFEA(2)
      COMMON/MACHSP/IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      I0R(1)=1
      CALL GETLST(ICORE(I0R(1)),1,1,1,1+LISTR1OFF,LISTR1)
      IF(IUHF.NE.0)THEN
       I0R(2)=I0R(1)+IINTFP*IRPDPD(IRREPX,9)
       CALL GETLST(ICORE(I0R(2)),1,1,1,2+LISTR1OFF,LISTR1)
      ELSE
       I0R(2)=I0R(1)
      ENDIF
      I0F(1)=I0R(2)+IINTFP*IRPDPD(IRREPX,10)
      CALL GETLST(ICORE(I0F(1)),1,1,1,1,93)
      IF(IUHF.NE.0)THEN
       I0F(2)=I0F(1)+IINTFP*NT(1)
       CALL GETLST(ICORE(I0F(2)),1,1,1,2,93)
      ELSE
       I0F(2)=I0F(1)
      ENDIF
      I0Q(1)=I0F(2)+IINTFP*NT(2)
      IF(IUHF.NE.0)THEN
       I0Q(2)=I0Q(1)+IINTFP*NT(1)
      ELSE
       I0Q(2)=I0Q(1)
      ENDIF
      I000=I0Q(2)+IINTFP*NT(2)
      MXCOR=MAXCOR-I000+1
C
C CALCULATE Q(AI) = R(ME)*L(IM,AE) INTERMEDIATES AND HOLD IN CORE
C R contracted with L and not H
c       CALL GT2XF(ICORE(I0Q(1)),IRREPX,IRREPX,LISTL2RS,LISTR1,LISTR1OFF,
c     &   ICORE(I000),MXCOR,IUHF,0)
C
C CALCULATE CONTRACTIONS
C
       IF(.NOT.MBPT2)THEN
C R only contracted with L
c        CALL R1L2Y2A(ICORE(I0Q(1)),ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF)
c        CALL R1L2Y2B(ICORE(I0Q(1)),ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF)
       ENDIF
       CALL R1L2Y2C(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,LISTL2)
       CALL R1L2Y2D(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,LISTL2)
       CALL R1L2Y2F(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,LISTL2)
       CALL R1L2Y2E(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,LISTL2)
cc       CALL R1L2Y2G(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF)
       CALL FORMX4HA(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF)
       CALL FORMX4HB(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF)
       CALL R1L2Y2H(ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,LISTL2RS)
C Unnecessary resorts
c       CALL RESORT(ICORE(I000),MXCOR,IUHF,IRREPX,LISTL2,LISTL2RS)
c       CALL RESORT(ICORE(I000),MXCOR,IUHF,IRREPX,LISTR2,LISTR2RS)
       IF (.NOT.MBPT2) THEN
        CALL R1L2Y2I(ICORE(I0F(1)),ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF
     &       ,LISTL2)
        CALL R1L2Y2J(ICORE(I0F(1)),ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF
     &     ,LISTL2)
C R only contracted with L
c        CALL R1L2Y2K(ICORE(I0Q(1)),ICORE(I0F(1)),ICORE(I0R(1)),
c     &     ICORE(I000),MXCOR,IUHF)
C R and H fully contracted, need H to have an open line
c        CALL R1L2Y2L(ICORE(I0F(1)),ICORE(I0R(1)),ICORE(I000),MXCOR,IUHF,
c     &     LISTL2)
       ENDIF
      RETURN
      END
