      SUBROUTINE AUXIOO(REMOVE)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER DISTSZ
      LOGICAL REMOVE
      COMMON /FILES/ LUOUT,MOINTS
      COMMON /AUXIO/ DISTSZ(8,100),NDISTS(8,100),INIWRD(8,100),LNPHYR,
     1               NRECS,LUAUX
C
      IF(REMOVE)THEN
      WRITE(LUOUT,1010)
      CLOSE(UNIT=LUAUX,STATUS='DELETE')
      ELSE
      WRITE(LUOUT,1020)
      CLOSE(UNIT=LUAUX,STATUS='KEEP')
      ENDIF
C
 1010 FORMAT(' @AUXIOO-I, Deleting the T3 file. ')
 1020 FORMAT(' @AUXIOO-I, Closing and keeping the T3 file. ')
      RETURN
      END
