      SUBROUTINE NATORB(DENS,BUF,NMO,IUHF)
C
C DIAGONALIZES RELAXED DENSITY MATRIX TO OBTAIN OCCUPATION NUMBERS
C  AND NATURAL ORBITALS
C
C
C  DENS - NMOxNMO MATRIX TO HOLD RELAXED DENSITY
C   BUF - A SCRATCH VECTOR OF LENGTH 3*NBAS*NBAS, WHERE NBAS IS THE
C            NUMBER OF BASIS FUNCTIONS
C   NMO - THE NUMBER OF ACTIVE MOLECULAR ORBITALS
C  IUHF - RHF/UHF FLAG 
C
CEND
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C  
      COMMON /FLAGS/ IFLAGS(100)
      COMMON /MACHSP/ IINTLN,IFLTLN,IINTFP,IALONE,IBITWD
C
      DIMENSION DENS(NMO*NMO),BUF(1)
C
      DATA ONE   /1.0/
      DATA ZILCH /0.0/ 
C
      IONE=1
      WRITE(6,1000)
      WRITE(6,1001)
      WRITE(6,1000)
C SG 2/96
      IF (IUHF.EQ.1) THEN
       WRITE(6,1002)
       WRITE(6,1000)
      ENDIF
      CALL GETREC(20,'JOBARC','NBASTOT ',IONE,NBAS)
      CALL GETREC(20,'JOBARC','RELDENSA',NMO*NMO*IINTFP,DENS)
      CALL GETREC(20,'JOBARC','SCFEVECA',NMO*NBAS*IINTFP,BUF(IOFFB))
      CALL XGEMM('N','N',NBAS,NMO,NMO,ONE,BUF(IOFFB),NBAS,
     &           DENS,NMO,ZILCH,BUF(IOFFB2),NBAS)
      CALL XGEMM('N','T',NBAS,NMO,NMO,ONE,BUF(IOFFB2),NBAS,
     &           BUF(IOFFB),NMO,ZILCH,BUF,NBAS)

      CALL GETREC(20,'JOBARC','NBASTOT ',IONE,NBAS)
      IOFFB=NBAS*NBAS+1
      IOFFB2=NBAS*NBAS+IOFFB
      CALL EIG(DENS,BUF,NMO,NMO,-1)
      WRITE(6,2000)(DENS(I),I=1,NMO*NMO,NMO+1)
      TRACE=SSUM(NMO,DENS,NMO+1)
      WRITE(6,2001)TRACE
C      CALL GETREC(20,'JOBARC','SCFEVECA',NMO*NBAS*IINTFP,BUF(IOFFB))
C      CALL XGEMM('N','N',NBAS,NMO,NMO,ONE,BUF(IOFFB),NBAS,
C     &           BUF,NMO,ZILCH,BUF(IOFFB2),NBAS)
C      CALL XGEMM('N','T',NBAS,NMO,NMO,ONE,BUF(IOFFB2),NBAS,
C     &           BUF(IOFFB),NMO,ZILCH,BUF,NBAS)

      CALL PUTREC(20,'JOBARC','AONTORBA',NBAS*NMO*IINTFP,BUF)
      CALL SCOPY (NMO,DENS,NMO+1,BUF(IOFFB),1)
      CALL PUTREC(20,'JOBARC','OCCNUM_A',NMO*IINTFP,BUF(IOFFB)) 
c antiquated.
c      IF(IFLAGS(42).NE.0)THEN
c        CALL NEWEVC(BUF(IOFFB2),BUF(1),NBAS,1)
c        CALL PUTREC(20,'JOBARC','SCFEVCA0',NBAS*NMO*IINTFP,BUF(IOFFB2))
c        IFLAGS(16)=0
c        IFLAGS(38)=1
c      ENDIF
C SG 2/96
C changed so that Beta spin natural orbitals are not printed out for
C   RHF calculation
      IF (IUHF.EQ.1) THEN
       WRITE(6,1000)
       WRITE(6,1003)
       WRITE(6,1000)
       CALL GETREC(20,'JOBARC','RELDENSB',NMO*NMO*IINTFP,DENS)
       CALL GETREC(20,'JOBARC','SCFEVECB',NMO*NBAS*IINTFP,BUF(IOFFB))
       CALL XGEMM('N','N',NBAS,NMO,NMO,ONE,BUF(IOFFB),NBAS,
     &           DENS,NMO,ZILCH,BUF(IOFFB2),NBAS)
       CALL XGEMM('N','T',NBAS,NMO,NMO,ONE,BUF(IOFFB2),NBAS,
     &           BUF(IOFFB),NMO,ZILCH,BUF,NBAS)
       CALL EIG(DENS,BUF,NMO,NMO,-1)
C       CALL GETREC(20,'JOBARC','SCFEVECB',NMO*NBAS*IINTFP,BUF(IOFFB))
C       CALL XGEMM('N','N',NBAS,NMO,NMO,ONE,BUF(IOFFB),NBAS,
C     &            BUF,NMO,ZILCH,BUF(IOFFB2),NBAS)
C       caLL XGEMM('N','T',NBAS,NMO,NMO,ONE,BUF(IOFFB2),NBAS,
C     &           BUF(IOFFB),NMO,ZILCH,BUF,NBAS)
       CALL PUTREC(20,'JOBARC','AONTORBB',NBAS*NMO*IINTFP,BUF)
       CALL SCOPY (NMO,DENS,NMO+1,BUF(IOFFB),1)
       CALL PUTREC(20,'JOBARC','OCCNUM_B',NMO*IINTFP,BUF(IOFFB)) 
c antiquated.
c       IF(IFLAGS(42).NE.0)THEN
c        CALL NEWEVC(BUF(IOFFB2),BUF(1),NBAS,2)
c        CALL PUTREC(20,'JOBARC','SCFEVCB0',NBAS*NMO*IINTFP,BUF(IOFFB2))
c        IFLAGS(16)=0
c        IFLAGS(38)=1
c       ENDIF
       WRITE(6,2000)(DENS(I),I=1,NMO*NMO,NMO+1)
       TRACE=SSUM(NMO,DENS,NMO+1)
       WRITE(6,2001)TRACE
      ENDIF
      WRITE(6,1000)
      ISIZE=100
      CALL PUTREC(20,'JOBARC','IFLAGS  ',ISIZE,IFLAGS)
      RETURN
1000  FORMAT(T3,70('-'))
1001  FORMAT(T18,'Natural orbital occupation numbers')
1002  FORMAT(T29,'Alpha spin')
1003  FORMAT(T29,'Beta spin')
2000  FORMAT((8(2X,F7.5)))
2001  FORMAT(T3,'Trace of density matrix : ',F14.10,'.')
      END
