      SUBROUTINE EXITEA(ICORE, MAXCOR, IUHF)
C
      IMPLICIT INTEGER (A-Z)
      DIMENSION ICORE(MAXCOR)
      DOUBLE PRECISION TSSTGEN, TEADAVID, TEADIR, ONE, ONEM
C
      COMMON /TIMSUB/ TSSTGEN, TEADAVID, TEADIR
      COMMON /SYMPOP/ IRPDPD(8,22),ISYTYP(2,500),ID(18)
C
      ONE = 1.0D0
      ONEM = -1.0D0
C
C
C  TRANFORM BACK THE PHPH INTEGRALS
C
      CALL MODWPHPH(ICORE, MAXCOR, IUHF, -1.0D0, 91, 92)
C
C  SUBTRACT AGAIN THE DIAGONAL PARTS IN LISTS 91 AND 92
C
      CALL MODF(ICORE, MAXCOR, IUHF, -1)
C
      CALL ACES_IO_REMOVE(54,'DERGAM')
C
      WRITE(6,*) 'EA-EOM CALCULATIONS FINISHED:  ALL DONE'
C
      RETURN
 1300 FORMAT(/)
      END
